from config.constants import (
    AMOUNTS_FIXED, AMOUNTS_BY_PAX,
    SERVICE_CATEGORY_EXTRA, SERVICE_CATEGORY_ALLOTMENT, SERVICE_CATEGORY_TRANSFER)


BASE_BOOKING_SERVICE_CATEGORY_BOOKING_ALLOTMENT = 'BA'
BASE_BOOKING_SERVICE_CATEGORY_BOOKING_TRANSFER = 'BT'
BASE_BOOKING_SERVICE_CATEGORY_BOOKING_EXTRA = 'BE'
BASE_BOOKING_SERVICE_CATEGORY_BOOKING_PACKAGE = 'BP'
BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_ALLOTMENT = 'PA'
BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_TRANSFER = 'PT'
BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_EXTRA = 'PE'
BASE_BOOKING_SERVICE_CATEGORIES = (
    (BASE_BOOKING_SERVICE_CATEGORY_BOOKING_ALLOTMENT, 'Booking Allotment'),
    (BASE_BOOKING_SERVICE_CATEGORY_BOOKING_TRANSFER, 'Booking Transfer'),
    (BASE_BOOKING_SERVICE_CATEGORY_BOOKING_EXTRA, 'Booking Extra'),
    (BASE_BOOKING_SERVICE_CATEGORY_BOOKING_PACKAGE, 'Booking Package'),
    (BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_ALLOTMENT, 'Booking Package Allotment'),
    (BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_TRANSFER, 'Booking Package Transfer'),
    (BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_EXTRA, 'Booking Package Extra'),
)

SERVICE_CATEGORY_PACKAGE = 'P'
SERVICE_CATEGORIES = (
    (SERVICE_CATEGORY_ALLOTMENT, 'Allotment'),
    (SERVICE_CATEGORY_TRANSFER, 'Transfer'),
    (SERVICE_CATEGORY_EXTRA, 'Extra'),
    (SERVICE_CATEGORY_PACKAGE, 'Package'),
)

QUOTE_STATUS_DRAFT = 'DR'
QUOTE_STATUS_READY = 'RD'
QUOTE_STATUS_LIST = (
    (QUOTE_STATUS_DRAFT, 'Draft'),
    (QUOTE_STATUS_READY, 'Ready'),
)

BOOKING_STATUS_PENDING = 'PD'
BOOKING_STATUS_REQUEST = 'RQ'
BOOKING_STATUS_CONFIRMED = 'OK'
BOOKING_STATUS_COORDINATED = 'CD'
BOOKING_STATUS_NOSHOW = 'NS'
BOOKING_STATUS_CANCELLED = 'CN'
BOOKING_STATUS_LIST = (
    (BOOKING_STATUS_PENDING, 'Pending'),
    (BOOKING_STATUS_REQUEST, 'Requested'),
    (BOOKING_STATUS_CONFIRMED, 'Confirmed'),
    (BOOKING_STATUS_COORDINATED, 'Coordinated'),
    (BOOKING_STATUS_NOSHOW, 'No Show'),
    (BOOKING_STATUS_CANCELLED, 'Cancelled'),
)

SERVICE_STATUS_PENDING = 'PD'
SERVICE_STATUS_REQUEST = 'RQ'
SERVICE_STATUS_PHONE_CONFIRMED = 'PH'
SERVICE_STATUS_CONFIRMED = 'OK'
SERVICE_STATUS_COORDINATED = 'CD'
SERVICE_STATUS_NOSHOW = 'NS'
SERVICE_STATUS_CANCELLED = 'CN'
SERVICE_STATUS_LIST = (
    (SERVICE_STATUS_PENDING, 'Pending'),
    (SERVICE_STATUS_REQUEST, 'Requested'),
    (SERVICE_STATUS_PHONE_CONFIRMED, 'Phone Confirmed'),
    (SERVICE_STATUS_CONFIRMED, 'Confirmed'),
    (SERVICE_STATUS_COORDINATED, 'Coordinated'),
    (SERVICE_STATUS_NOSHOW, 'No Show'),
    (SERVICE_STATUS_CANCELLED, 'Cancelled'),
)

BOOTSTRAP_STYLE_QUOTE_STATUS_MAPPING = {
    QUOTE_STATUS_DRAFT: '',
    QUOTE_STATUS_READY: 'success',
}

BOOTSTRAP_STYLE_BOOKING_STATUS_MAPPING = {
    BOOKING_STATUS_PENDING: 'table-danger',
    BOOKING_STATUS_REQUEST: 'table-warning',
    BOOKING_STATUS_CONFIRMED: '',
    BOOKING_STATUS_COORDINATED: 'table-success',
    BOOKING_STATUS_NOSHOW: '',
    BOOKING_STATUS_CANCELLED: 'table-active',
}

BOOTSTRAP_STYLE_BOOKING_SERVICE_STATUS_MAPPING = {
    SERVICE_STATUS_PENDING: 'table-danger',
    SERVICE_STATUS_REQUEST: 'table-warning',
    SERVICE_STATUS_PHONE_CONFIRMED: '',
    SERVICE_STATUS_CONFIRMED: '',
    SERVICE_STATUS_COORDINATED: 'table-success',
    SERVICE_STATUS_NOSHOW: '',
    SERVICE_STATUS_CANCELLED: 'table-active',
}

PACKAGESERVICE_TYPES = {
    SERVICE_CATEGORY_ALLOTMENT: 'packageallotment',
    SERVICE_CATEGORY_TRANSFER: 'packagetransfer',
    SERVICE_CATEGORY_EXTRA: 'packageextra',
}

QUOTESERVICE_TYPES = {
    SERVICE_CATEGORY_ALLOTMENT: 'newquoteallotment',
    SERVICE_CATEGORY_TRANSFER: 'newquotetransfer',
    SERVICE_CATEGORY_EXTRA: 'newquoteextra',
    SERVICE_CATEGORY_PACKAGE: 'quoteextrapackage',
}

QUOTEPACKAGESERVICE_TYPES = {
    SERVICE_CATEGORY_ALLOTMENT: 'newquoteallotment',
    SERVICE_CATEGORY_TRANSFER: 'newquotetransfer',
    SERVICE_CATEGORY_EXTRA: 'newquoteextra',
}

BOOKINGSERVICE_TYPES = {
    SERVICE_CATEGORY_ALLOTMENT: 'bookingprovidedallotment',
    SERVICE_CATEGORY_TRANSFER: 'bookingprovidedtransfer',
    SERVICE_CATEGORY_EXTRA: 'bookingprovidedextra',
    SERVICE_CATEGORY_PACKAGE: 'bookingextrapackage',
}

BOOKINGPACKAGESERVICE_TYPES = {
    SERVICE_CATEGORY_ALLOTMENT: 'bookingprovidedallotment',
    SERVICE_CATEGORY_TRANSFER: 'bookingprovidedtransfer',
    SERVICE_CATEGORY_EXTRA: 'bookingprovidedextra',
}

ACTIONS = {
    'vouchers': 'BookingSiteModel.config_vouchers',
}

INVOICE_FORMAT_COMPACT = 'C'
INVOICE_FORMAT_SERVICES = 'S'
INVOICE_FORMAT_DETAILS = 'D'
INVOICE_FORMATS = (
    (INVOICE_FORMAT_COMPACT, 'Compact'),
    (INVOICE_FORMAT_SERVICES, 'Services'),
    (INVOICE_FORMAT_DETAILS, 'Details'),
)

QUOTE_BOOK_DETAIL_CATEGORIES = {
    SERVICE_CATEGORY_ALLOTMENT: 'quotebookdetailallotment',
    SERVICE_CATEGORY_TRANSFER: 'quotebookdetailtransfer',
    SERVICE_CATEGORY_EXTRA: 'quotebookdetailextra',
}

BOOKING_BOOK_DETAIL_CATEGORIES = {
    SERVICE_CATEGORY_ALLOTMENT: 'bookingbookdetailallotment',
    SERVICE_CATEGORY_TRANSFER: 'bookingbookdetailtransfer',
    SERVICE_CATEGORY_EXTRA: 'bookingbookdetailextra',
}

