from config.constants import (SERVICE_CATEGORY_EXTRA,
                              SERVICE_CATEGORY_ALLOTMENT,
                              SERVICE_CATEGORY_TRANSFER)

BOOKING_STATUS_PENDING = 'PD'
BOOKING_STATUS_REQUEST = 'RQ'
BOOKING_STATUS_CONFIRMED = 'OK'
BOOKING_STATUS_COORDINATED = 'CD'
BOOKING_STATUS_CANCELLED = 'CN'
BOOKING_STATUS_LIST = (
    (BOOKING_STATUS_PENDING, 'Pending'),
    (BOOKING_STATUS_REQUEST, 'Requested'),
    (BOOKING_STATUS_CONFIRMED, 'Confirmed'),
    (BOOKING_STATUS_COORDINATED, 'Coordinated'),
    (BOOKING_STATUS_CANCELLED, 'Cancelled'),
)

SERVICE_STATUS_PENDING = 'PD'
SERVICE_STATUS_REQUEST = 'RQ'
SERVICE_STATUS_PHONE_CONFIRMED = 'PH'
SERVICE_STATUS_CONFIRMED = 'OK'
SERVICE_STATUS_COORDINATED = 'CD'
SERVICE_STATUS_CANCELLED = 'CN'
SERVICE_STATUS_LIST = (
    (SERVICE_STATUS_PENDING, 'Pending'),
    (SERVICE_STATUS_REQUEST, 'Requested'),
    (SERVICE_STATUS_PHONE_CONFIRMED, 'Phone Confirmed'),
    (SERVICE_STATUS_CONFIRMED, 'Confirmed'),
    (SERVICE_STATUS_COORDINATED, 'Coordinated'),
    (SERVICE_STATUS_CANCELLED, 'Cancelled'),
)

BOOKINGSERVICE_TYPES = {
    SERVICE_CATEGORY_ALLOTMENT: 'bookingallotment',
    SERVICE_CATEGORY_TRANSFER: 'bookingtransfer',
    SERVICE_CATEGORY_EXTRA: 'bookingextra',
}
