# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocumentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Accounting Document History',
                'verbose_name_plural': 'Accountings Documents History',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='AgencyMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Agency Match',
                'verbose_name_plural': 'Agencies Matches',
            },
        ),
        migrations.CreateModel(
            name='FinantialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(choices=[('-------', '-------'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('CURRENCY_EXCHANGE', 'Currency Exchange'), ('TRANSFER', 'Transfer'), ('LOAN_DEPOSIT', 'Loan Deposit'), ('LOAN_WITHDRAW', 'Loan Withdraw'), ('LOAN_ACCOUNT_DEPOSIT', 'Loan Account Deposit'), ('LOAN_ACCOUNT_WITHDRAW', 'Loan Account Withdraw'), ('AGENCY_INVOICE', 'Agency Invoice'), ('AGENCY_PAYMENT', 'Agency Payment'), ('AGENCY_DEVOLUTION', 'Agency Devolution'), ('AGENCY_DISCOUNT', 'Agency Discount'), ('PROVIDER_INVOICE', 'Provider Invoice'), ('PROVIDER_PAYMENT', 'Provider Payment'), ('PROVIDER_DEVOLUTION', 'Provider Devolution'), ('PROVIDER_DISCOUNT', 'Provider Discount')], default='-------', max_length=50)),
                ('name', models.CharField(default='Finantial Document', max_length=200)),
                ('date', models.DateTimeField()),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('R', 'Ready'), ('C', 'Cancelled')], default='D', max_length=2)),
            ],
            options={
                'verbose_name': 'Finantial Document',
                'verbose_name_plural': 'Finantials Documents',
            },
        ),
        migrations.CreateModel(
            name='FinantialDocumentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('old_status', models.CharField(blank=True, choices=[('D', 'Draft'), ('R', 'Ready'), ('C', 'Cancelled')], max_length=2, null=True)),
                ('new_status', models.CharField(choices=[('D', 'Draft'), ('R', 'Ready'), ('C', 'Cancelled')], max_length=2)),
            ],
            options={
                'verbose_name': 'Finantial Document History',
                'verbose_name_plural': 'Finantials Documents History',
            },
        ),
        migrations.CreateModel(
            name='LoanAccountMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Account Match',
                'verbose_name_plural': 'Loans Accounts Matches',
            },
        ),
        migrations.CreateModel(
            name='LoanMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Match',
                'verbose_name_plural': 'Loans Matches',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='ProviderMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Provider Match',
                'verbose_name_plural': 'Providers Matches',
            },
        ),
        migrations.CreateModel(
            name='AgencyDocument',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
            ],
            options={
                'verbose_name': 'Agency Document',
                'verbose_name_plural': 'Agencies Documents',
            },
            bases=('finance.finantialdocument',),
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('exchange_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_account', to='accounting.Account')),
            ],
            options={
                'verbose_name': 'Currency Exchange',
                'verbose_name_plural': 'Currencies Exchanges',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='LoanDeposit',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Deposit',
                'verbose_name_plural': 'Loans Deposits',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='LoanWithdraw',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Withdraw',
                'verbose_name_plural': 'Loans Withdraws',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
            ],
            options={
                'verbose_name': 'Provider Document',
                'verbose_name_plural': 'Providers Documents',
            },
            bases=('finance.finantialdocument',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
                ('transfer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_account', to='accounting.Account')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Withdraw',
                'verbose_name_plural': 'Withdraws',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.AddField(
            model_name='finantialdocumenthistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinantialDocument'),
        ),
        migrations.AddField(
            model_name='finantialdocumenthistory',
            name='user',
            field=models.ForeignKey(help_text='User who did the operation.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingdocumenthistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinantialDocument'),
        ),
        migrations.AddField(
            model_name='accountingdocumenthistory',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation'),
        ),
        migrations.CreateModel(
            name='AgencyCreditDocument',
            fields=[
                ('agencydocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDocument')),
            ],
            options={
                'verbose_name': 'Agency Credit Document',
                'verbose_name_plural': 'Agencies Credits Documents',
            },
            bases=('finance.agencydocument',),
        ),
        migrations.CreateModel(
            name='AgencyDebitDocument',
            fields=[
                ('agencydocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDocument')),
            ],
            options={
                'verbose_name': 'Agency Debit Document',
                'verbose_name_plural': 'Agencies Debits Documents',
            },
            bases=('finance.agencydocument',),
        ),
        migrations.CreateModel(
            name='LoanAccountDeposit',
            fields=[
                ('loandeposit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.LoanDeposit')),
                ('withdraw_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_account', to='accounting.Account')),
            ],
            options={
                'verbose_name': 'Loan Account Deposit',
                'verbose_name_plural': 'Loans Accounts Deposits',
            },
            bases=('finance.loandeposit',),
        ),
        migrations.CreateModel(
            name='LoanAccountWithdraw',
            fields=[
                ('loanwithdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.LoanWithdraw')),
                ('deposit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_account', to='accounting.Account')),
            ],
            options={
                'verbose_name': 'Loan Account Withdraw',
                'verbose_name_plural': 'Loans Accounts Withdraws',
            },
            bases=('finance.loanwithdraw',),
        ),
        migrations.CreateModel(
            name='ProviderCreditDocument',
            fields=[
                ('providerdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDocument')),
            ],
            options={
                'verbose_name': 'Provider Credit Document',
                'verbose_name_plural': 'Providers Credits Documents',
            },
            bases=('finance.providerdocument',),
        ),
        migrations.CreateModel(
            name='ProviderDebitDocument',
            fields=[
                ('providerdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDocument')),
            ],
            options={
                'verbose_name': 'Provider Debit Document',
                'verbose_name_plural': 'Providers Debits Documents',
            },
            bases=('finance.providerdocument',),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='loanwithdraw',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='loanwithdraw',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation'),
        ),
        migrations.AddField(
            model_name='loanmatch',
            name='loan_deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanDeposit'),
        ),
        migrations.AddField(
            model_name='loanmatch',
            name='loan_withdraw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanWithdraw'),
        ),
        migrations.AddField(
            model_name='loandeposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='loandeposit',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation'),
        ),
        migrations.AddField(
            model_name='agencydocument',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency'),
        ),
        migrations.CreateModel(
            name='AgencyDevolution',
            fields=[
                ('agencydebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDebitDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Agency Devolution',
                'verbose_name_plural': 'Agencies Devolutions',
            },
            bases=('finance.agencydebitdocument', models.Model),
        ),
        migrations.CreateModel(
            name='AgencyDiscount',
            fields=[
                ('agencycreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyCreditDocument')),
            ],
            options={
                'verbose_name': 'Agency Discount',
                'verbose_name_plural': 'Agencies Discounts',
            },
            bases=('finance.agencycreditdocument',),
        ),
        migrations.CreateModel(
            name='AgencyInvoice',
            fields=[
                ('agencydebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDebitDocument')),
            ],
            options={
                'verbose_name': 'Agency Invoice',
                'verbose_name_plural': 'Agencies Invoices',
            },
            bases=('finance.agencydebitdocument',),
        ),
        migrations.CreateModel(
            name='AgencyPayment',
            fields=[
                ('agencycreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyCreditDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Agency Payment',
                'verbose_name_plural': 'Agencies Payments',
            },
            bases=('finance.agencycreditdocument', models.Model),
        ),
        migrations.CreateModel(
            name='ProviderDevolution',
            fields=[
                ('providerdebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDebitDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Provider Devolution',
                'verbose_name_plural': 'Providers Devolutions',
            },
            bases=('finance.providerdebitdocument', models.Model),
        ),
        migrations.CreateModel(
            name='ProviderDiscount',
            fields=[
                ('providercreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderCreditDocument')),
            ],
            options={
                'verbose_name': 'Provider Discount',
                'verbose_name_plural': 'Providers Discounts',
            },
            bases=('finance.providercreditdocument',),
        ),
        migrations.CreateModel(
            name='ProviderInvoice',
            fields=[
                ('providerdebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDebitDocument')),
            ],
            options={
                'verbose_name': 'Provider Invoice',
                'verbose_name_plural': 'Providers Invoices',
            },
            bases=('finance.providerdebitdocument',),
        ),
        migrations.CreateModel(
            name='ProviderPayment',
            fields=[
                ('providercreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderCreditDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Provider Payment',
                'verbose_name_plural': 'Providers Payments',
            },
            bases=('finance.providercreditdocument', models.Model),
        ),
        migrations.AddField(
            model_name='providermatch',
            name='credit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderCreditDocument'),
        ),
        migrations.AddField(
            model_name='providermatch',
            name='debit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderDebitDocument'),
        ),
        migrations.AddField(
            model_name='loanaccountmatch',
            name='loan_account_deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanAccountDeposit'),
        ),
        migrations.AddField(
            model_name='loanaccountmatch',
            name='loan_account_withdraw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanAccountWithdraw'),
        ),
        migrations.AddField(
            model_name='agencymatch',
            name='credit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.AgencyCreditDocument'),
        ),
        migrations.AddField(
            model_name='agencymatch',
            name='debit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.AgencyDebitDocument'),
        ),
    ]
