# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocumentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Accounting Document History',
                'verbose_name_plural': 'Accountings Documents History',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='AgencyCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=5)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
            ],
            options={
                'verbose_name': 'Agency Currency',
                'verbose_name_plural': 'Agencies Currencies',
            },
        ),
        migrations.CreateModel(
            name='AgencyDocumentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Agency Document Match',
                'verbose_name_plural': 'Agencies Documents Matches',
            },
        ),
        migrations.CreateModel(
            name='FinantialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer'), ('CURRENCY_EXCHANGE', 'Currency Exchange'), ('LOAN_ENTITY_DEPOSIT', 'Loan Entity Deposit'), ('LOAN_ENTITY_WITHDRAW', 'Loan Entity Withdraw'), ('LOAN_ACCOUNT_DEPOSIT', 'Loan Account Deposit'), ('LOAN_ACCOUNT_WITHDRAW', 'Loan Account Withdraw'), ('AGENCY_INVOICE', 'Agency Invoice'), ('AGENCY_PAYMENT', 'Agency Payment'), ('AGENCY_DEVOLUTION', 'Agency Devolution'), ('AGENCY_DISCOUNT', 'Agency Discount'), ('PROVIDER_INVOICE', 'Provider Invoice'), ('PROVIDER_PAYMENT', 'Provider Payment'), ('PROVIDER_DEVOLUTION', 'Provider Devolution'), ('PROVIDER_DISCOUNT', 'Provider Discount')], max_length=50)),
                ('name', models.CharField(default='Finantial Document', max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('R', 'Ready'), ('C', 'Cancelled')], default='D', max_length=5)),
            ],
            options={
                'verbose_name': 'Finantial Document',
                'verbose_name_plural': 'Finantials Documents',
            },
        ),
        migrations.CreateModel(
            name='FinantialDocumentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('old_status', models.CharField(blank=True, choices=[('D', 'Draft'), ('R', 'Ready'), ('C', 'Cancelled')], max_length=5, null=True)),
                ('new_status', models.CharField(choices=[('D', 'Draft'), ('R', 'Ready'), ('C', 'Cancelled')], max_length=5)),
            ],
            options={
                'verbose_name': 'Finantial Document History',
                'verbose_name_plural': 'Finantials Documents History',
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
            options={
                'verbose_name': 'Finantial Account',
                'verbose_name_plural': 'Finantials Accounts',
            },
        ),
        migrations.CreateModel(
            name='LoanAccountMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Account Match',
                'verbose_name_plural': 'Loans Accounts Matches',
            },
        ),
        migrations.CreateModel(
            name='LoanEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Loan Entity',
                'verbose_name_plural': 'Loans Entities',
            },
        ),
        migrations.CreateModel(
            name='LoanEntityCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=5)),
                ('loan_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanEntity')),
            ],
            options={
                'verbose_name': 'Loan Entity Currency',
                'verbose_name_plural': 'Loans Entities Currencies',
            },
        ),
        migrations.CreateModel(
            name='LoanEntityMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Entity Match',
                'verbose_name_plural': 'Loans Entities Matches',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='ProviderCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=5)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider')),
            ],
            options={
                'verbose_name': 'Provider Currency',
                'verbose_name_plural': 'Providers Currencies',
            },
        ),
        migrations.CreateModel(
            name='ProviderDocumentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Provider Document Match',
                'verbose_name_plural': 'Providers Documents Matches',
            },
        ),
        migrations.CreateModel(
            name='AgencyDocument',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Agency Document',
                'verbose_name_plural': 'Agencies Documents',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('exchange_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_account', to='accounting.Account')),
            ],
            options={
                'verbose_name': 'Currency Exchange',
                'verbose_name_plural': 'Currencies Exchanges',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='LoanAccountDocument',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Account document',
                'verbose_name_plural': 'Loans Accounts Documents',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='LoanEntityDocument',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Loan Entity Document',
                'verbose_name_plural': 'Loans Entities Documents',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Provider Document',
                'verbose_name_plural': 'Providers Documents',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
                ('transfer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_account', to='accounting.Account')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('finantialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.FinantialDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Withdraw',
                'verbose_name_plural': 'Withdraws',
            },
            bases=('finance.finantialdocument', models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='loanentity',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='finantialdocumenthistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinantialDocument'),
        ),
        migrations.AddField(
            model_name='finantialdocumenthistory',
            name='user',
            field=models.ForeignKey(help_text='User who did the operation.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='accountingdocumenthistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinantialDocument'),
        ),
        migrations.AddField(
            model_name='accountingdocumenthistory',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation'),
        ),
        migrations.CreateModel(
            name='AgencyCreditDocument',
            fields=[
                ('agencydocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDocument')),
            ],
            options={
                'verbose_name': 'Agency Credit Document',
                'verbose_name_plural': 'Agencies Credits Documents',
            },
            bases=('finance.agencydocument',),
        ),
        migrations.CreateModel(
            name='AgencyDebitDocument',
            fields=[
                ('agencydocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDocument')),
            ],
            options={
                'verbose_name': 'Agency Debit Document',
                'verbose_name_plural': 'Agencies Debits Documents',
            },
            bases=('finance.agencydocument',),
        ),
        migrations.CreateModel(
            name='LoanAccountDeposit',
            fields=[
                ('loanaccountdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.LoanAccountDocument')),
            ],
            options={
                'verbose_name': 'Loan Account Deposit',
                'verbose_name_plural': 'Loans Accounts Deposits',
            },
            bases=('finance.loanaccountdocument',),
        ),
        migrations.CreateModel(
            name='LoanAccountWithdraw',
            fields=[
                ('loanaccountdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.LoanAccountDocument')),
            ],
            options={
                'verbose_name': 'Loan Account Withdraw',
                'verbose_name_plural': 'Loans Accounts Withdraws',
            },
            bases=('finance.loanaccountdocument',),
        ),
        migrations.CreateModel(
            name='LoanEntityDeposit',
            fields=[
                ('loanentitydocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.LoanEntityDocument')),
            ],
            options={
                'verbose_name': 'Loan Entity Deposit',
                'verbose_name_plural': 'Loans Entities Deposits',
            },
            bases=('finance.loanentitydocument',),
        ),
        migrations.CreateModel(
            name='LoanEntityWithdraw',
            fields=[
                ('loanentitydocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.LoanEntityDocument')),
            ],
            options={
                'verbose_name': 'Loan Entity Withdraw',
                'verbose_name_plural': 'Loans Entities Withdraws',
            },
            bases=('finance.loanentitydocument',),
        ),
        migrations.CreateModel(
            name='ProviderCreditDocument',
            fields=[
                ('providerdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDocument')),
            ],
            options={
                'verbose_name': 'Provider Credit Document',
                'verbose_name_plural': 'Providers Credits Documents',
            },
            bases=('finance.providerdocument',),
        ),
        migrations.CreateModel(
            name='ProviderDebitDocument',
            fields=[
                ('providerdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDocument')),
            ],
            options={
                'verbose_name': 'Provider Debit Document',
                'verbose_name_plural': 'Providers Debits Documents',
            },
            bases=('finance.providerdocument',),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AlterUniqueTogether(
            name='providercurrency',
            unique_together=set([('provider', 'currency')]),
        ),
        migrations.AddField(
            model_name='loanentitydocument',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='loanentitydocument',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation'),
        ),
        migrations.AddField(
            model_name='loanentitydocument',
            name='loan_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanEntity'),
        ),
        migrations.AlterUniqueTogether(
            name='loanentitycurrency',
            unique_together=set([('loan_entity', 'currency')]),
        ),
        migrations.AddField(
            model_name='loanaccountdocument',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='loanaccountdocument',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation'),
        ),
        migrations.AddField(
            model_name='loanaccountdocument',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='accounting.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='loanaccount',
            unique_together=set([('loan_account',)]),
        ),
        migrations.AddField(
            model_name='agencydocument',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency'),
        ),
        migrations.AlterUniqueTogether(
            name='agencycurrency',
            unique_together=set([('agency', 'currency')]),
        ),
        migrations.CreateModel(
            name='AgencyDevolution',
            fields=[
                ('agencydebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDebitDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Agency Devolution',
                'verbose_name_plural': 'Agencies Devolutions',
            },
            bases=('finance.agencydebitdocument', models.Model),
        ),
        migrations.CreateModel(
            name='AgencyDiscount',
            fields=[
                ('agencycreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyCreditDocument')),
            ],
            options={
                'verbose_name': 'Agency Discount',
                'verbose_name_plural': 'Agencies Discounts',
            },
            bases=('finance.agencycreditdocument',),
        ),
        migrations.CreateModel(
            name='AgencyInvoice',
            fields=[
                ('agencydebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyDebitDocument')),
            ],
            options={
                'verbose_name': 'Agency Invoice',
                'verbose_name_plural': 'Agencies Invoices',
            },
            bases=('finance.agencydebitdocument',),
        ),
        migrations.CreateModel(
            name='AgencyPayment',
            fields=[
                ('agencycreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyCreditDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Agency Payment',
                'verbose_name_plural': 'Agencies Payments',
            },
            bases=('finance.agencycreditdocument', models.Model),
        ),
        migrations.CreateModel(
            name='ProviderDevolution',
            fields=[
                ('providerdebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDebitDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Provider Devolution',
                'verbose_name_plural': 'Providers Devolutions',
            },
            bases=('finance.providerdebitdocument', models.Model),
        ),
        migrations.CreateModel(
            name='ProviderDiscount',
            fields=[
                ('providercreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderCreditDocument')),
            ],
            options={
                'verbose_name': 'Provider Discount',
                'verbose_name_plural': 'Providers Discounts',
            },
            bases=('finance.providercreditdocument',),
        ),
        migrations.CreateModel(
            name='ProviderInvoice',
            fields=[
                ('providerdebitdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderDebitDocument')),
            ],
            options={
                'verbose_name': 'Provider Invoice',
                'verbose_name_plural': 'Providers Invoices',
            },
            bases=('finance.providerdebitdocument',),
        ),
        migrations.CreateModel(
            name='ProviderPayment',
            fields=[
                ('providercreditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.ProviderCreditDocument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('current_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Provider Payment',
                'verbose_name_plural': 'Providers Payments',
            },
            bases=('finance.providercreditdocument', models.Model),
        ),
        migrations.AddField(
            model_name='providerdocumentmatch',
            name='credit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderCreditDocument'),
        ),
        migrations.AddField(
            model_name='providerdocumentmatch',
            name='debit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderDebitDocument'),
        ),
        migrations.AddField(
            model_name='loanentitymatch',
            name='loan_entity_deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanEntityDeposit'),
        ),
        migrations.AddField(
            model_name='loanentitymatch',
            name='loan_entity_withdraw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanEntityWithdraw'),
        ),
        migrations.AddField(
            model_name='loanaccountmatch',
            name='loan_account_deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanAccountDeposit'),
        ),
        migrations.AddField(
            model_name='loanaccountmatch',
            name='loan_account_withdraw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.LoanAccountWithdraw'),
        ),
        migrations.AddField(
            model_name='agencydocumentmatch',
            name='credit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.AgencyCreditDocument'),
        ),
        migrations.AddField(
            model_name='agencydocumentmatch',
            name='debit_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.AgencyDebitDocument'),
        ),
        migrations.AlterUniqueTogether(
            name='providerdocumentmatch',
            unique_together=set([('credit_document', 'debit_document')]),
        ),
        migrations.AlterUniqueTogether(
            name='loanentitymatch',
            unique_together=set([('loan_entity_deposit', 'loan_entity_withdraw')]),
        ),
        migrations.AlterUniqueTogether(
            name='loanaccountmatch',
            unique_together=set([('loan_account_deposit', 'loan_account_withdraw')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencydocumentmatch',
            unique_together=set([('credit_document', 'debit_document')]),
        ),
    ]
