# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-25 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finantialdocument',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
