# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-14 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_finantialdocument_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
