# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20181114_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydocument',
            name='matched_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Matched'),
        ),
        migrations.AlterField(
            model_name='loanaccountdocument',
            name='matched_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Matched'),
        ),
        migrations.AlterField(
            model_name='loanentitydocument',
            name='matched_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Matched'),
        ),
        migrations.AlterField(
            model_name='providerdocument',
            name='matched_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Matched'),
        ),
    ]
