# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20181118_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerinvoice',
            options={'verbose_name': 'Provider Invoice', 'verbose_name_plural': 'Provider Invoices'},
        ),
    ]
