# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_agencyinvoiceline_agencyinvoicepartial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyinvoice',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyinvoice',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyinvoice',
            name='detail1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencyinvoice',
            name='detail2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencyinvoiceline',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyinvoiceline',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
