# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20191201_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
