# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20181224_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='gain_percent',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
