# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-21 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_office_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='finantialdocument',
            name='content_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
