# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_transfer_operation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyinvoice',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='agencyinvoice',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='agencyinvoice',
            name='detail1',
        ),
        migrations.RemoveField(
            model_name='agencyinvoice',
            name='detail2',
        ),
    ]
