# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models


def update_all_booking_invoices(apps, schema_editor):
    BookingInvoice = apps.get_model('booking', 'BookingInvoice')

    for bi in BookingInvoice.objects.all().filter(status='R'):
            bi.content_date = bi.invoice_booking.date_from
            bi.content_ref = '%s' % (20000 + int(bi.invoice_booking.id))
            bi.save(force_update=True, update_fields=['content_date',
                                                      'content_ref'])


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_finantialdocument_content_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finantialdocument',
            name='content_ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(update_all_booking_invoices, backwards_function),
    ]
