# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20190219_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyinvoiceline',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='agencyinvoicepartial',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='AgencyInvoiceLine',
        ),
        migrations.DeleteModel(
            name='AgencyInvoicePartial',
        ),
    ]
