# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_finantialdocument_content_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finantialdocument',
            name='content_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finantialdocument',
            name='content_ref',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ref.'),
        ),
        migrations.AlterField(
            model_name='finantialdocument',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
    ]
