# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20190219_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], default=b'USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='agencycurrency',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finantialdocument',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='loanentitycurrency',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], default=b'CUC', max_length=5),
        ),
        migrations.AlterField(
            model_name='providercurrency',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], max_length=5),
        ),
    ]
