# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20190327_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='agencycurrency',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='finantialdocument',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='loanentitycurrency',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], default='CUC', max_length=5),
        ),
        migrations.AlterField(
            model_name='providercurrency',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], max_length=5),
        ),
    ]
