# Generated by Django 2.2.28 on 2023-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20200706_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='bank_details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
