# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20190402_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'TTOO', 'verbose_name_plural': 'TTOOs'},
        ),
        migrations.AlterModelOptions(
            name='agencyinvoice',
            options={'verbose_name': 'TTOO Invoice', 'verbose_name_plural': 'TTOO Invoices'},
        ),
        migrations.AlterModelOptions(
            name='agencypayment',
            options={'verbose_name': 'TTOO Payment', 'verbose_name_plural': 'TTOO Payments'},
        ),
    ]
