# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_office_default_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='exchange_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_account', to='accounting.Account', verbose_name='Origin Account'),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='exchange_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Origin Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_account', to='accounting.Account', verbose_name='Origin Account'),
        ),
    ]
