# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20190616_0752'),
        ('finance', '0018_auto_20190610_1534'),
    ]

    operations = [
    ]
