# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_merge_20190619_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
