# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_provider_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
