# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-24 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_agency_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
