CURRENCY_CUC = 'CUC'
CURRENCY_USD = 'USD'
CURRENCY_EUR = 'EUR'
CURRENCIES = (
    (CURRENCY_CUC, 'cuc'),
    (CURRENCY_USD, 'usd'),
    (CURRENCY_EUR, 'eur'),
)

MOVEMENT_TYPE_DEPOSIT = 'D'
MOVEMENT_TYPE_WITHDRAW = 'W'
MOVEMENT_TYPES = (
    (MOVEMENT_TYPE_DEPOSIT, 'Deposit'),
    (MOVEMENT_TYPE_WITHDRAW, 'Withdraw'),
)

