CURRENCY_CUC = 'CUC'
CURRENCY_USD = 'USD'
CURRENCY_EUR = 'EUR'

CURRENCIES = (
    (CURRENCY_CUC, 'CUC'),
    (CURRENCY_USD, 'USD'),
    (CURRENCY_EUR, 'EUR'),
)

MOVEMENT_TYPE_INPUT = 'I'
MOVEMENT_TYPE_OUTPUT = 'O'

MOVEMENT_TYPES = (
    (MOVEMENT_TYPE_INPUT, 'Input'),
    (MOVEMENT_TYPE_OUTPUT, 'Output'),
)

CONCEPT_EMPTY = '-------'
CONCEPT_DEPOSIT = 'DEPOSIT'
CONCEPT_WITHDRAW = 'WITHDRAW'
CONCEPT_CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE'
CONCEPT_TRANSFER = 'TRANSFER'
CONCEPT_LOAN_DEPOSIT = 'LOAN_DEPOSIT'
CONCEPT_LOAN_WITHDRAW = 'LOAN_WITHDRAW'
CONCEPT_LOAN_ACCOUNT_DEPOSIT = 'LOAN_ACCOUNT_DEPOSIT'
CONCEPT_LOAN_ACCOUNT_WITHDRAW = 'LOAN_ACCOUNT_WITHDRAW'
CONCEPT_AGENCY_INVOICE = 'AGENCY_INVOICE'
CONCEPT_AGENCY_PAYMENT = 'AGENCY_PAYMENT'
CONCEPT_AGENCY_DEVOLUTION = 'AGENCY_DEVOLUTION'
CONCEPT_AGENCY_DISCOUNT = 'AGENCY_DISCOUNT'
CONCEPT_PROVIDER_INVOICE = 'PROVIDER_INVOICE'
CONCEPT_PROVIDER_PAYMENT = 'PROVIDER_PAYMENT'
CONCEPT_PROVIDER_DEVOLUTION = 'PROVIDER_DEVOLUTION'
CONCEPT_PROVIDER_DISCOUNT = 'PROVIDER_DISCOUNT'
CONCEPT_DEPOSIT_REVERTION = 'DEPOSIT_REVERTION'
CONCEPT_WITHDRAW_REVERTION = 'WITHDRAW_REVERTION'
CONCEPT_CURRENCY_EXCHANGE_REVERTION = 'CURRENCY_EXCHANGE_REVERTION'
CONCEPT_TRANSFER_REVERTION = 'TRANSFER_REVERTION'
CONCEPT_LOAN_DEPOSIT_REVERTION = 'LOAN_DEPOSIT_REVERTION'
CONCEPT_LOAN_WITHDRAW_REVERTION = 'LOAN_WITHDRAW_REVERTION'
CONCEPT_LOAN_ACCOUNT_DEPOSIT_REVERTION = 'LOAN_ACCOUNT_DEPOSIT_REVERTION'
CONCEPT_LOAN_ACCOUNT_WITHDRAW_REVERTION = 'LOAN_ACCOUNT_WITHDRAW_REVERTION'
CONCEPT_AGENCY_INVOICE_REVERTION = 'AGENCY_INVOICE_REVERTION'
CONCEPT_AGENCY_PAYMENT_REVERTION = 'AGENCY_PAYMENT_REVERTION'
CONCEPT_AGENCY_DEVOLUTION_REVERTION = 'AGENCY_DEVOLUTION_REVERTION'
CONCEPT_AGENCY_DISCOUNT_REVERTION = 'AGENCY_DISCOUNT_REVERTION'
CONCEPT_PROVIDER_INVOICE_REVERTION = 'PROVIDER_INVOICE_REVERTION'
CONCEPT_PROVIDER_PAYMENT_REVERTION = 'PROVIDER_PAYMENT_REVERTION'
CONCEPT_PROVIDER_DEVOLUTION_REVERTION = 'PROVIDER_DEVOLUTION_REVERTION'
CONCEPT_PROVIDER_DISCOUNT_REVERTION = 'PROVIDER_DISCOUNT_REVERTION'

CONCEPTS = (
    (CONCEPT_EMPTY, '-------'),
    (CONCEPT_DEPOSIT, 'Deposit'),
    (CONCEPT_WITHDRAW, 'Withdraw'),
    (CONCEPT_CURRENCY_EXCHANGE, 'Currency Exchange'),
    (CONCEPT_TRANSFER, 'Transfer'),
    (CONCEPT_LOAN_DEPOSIT, 'Loan Deposit'),
    (CONCEPT_LOAN_WITHDRAW, 'Loan Withdraw'),
    (CONCEPT_LOAN_ACCOUNT_DEPOSIT, 'Loan Account Deposit'),
    (CONCEPT_LOAN_ACCOUNT_WITHDRAW, 'Loan Account Withdraw'),
    (CONCEPT_AGENCY_INVOICE, 'Agency Invoice'),
    (CONCEPT_AGENCY_PAYMENT, 'Agency Payment'),
    (CONCEPT_AGENCY_DEVOLUTION, 'Agency Devolution'),
    (CONCEPT_AGENCY_DISCOUNT, 'Agency Discount'),
    (CONCEPT_PROVIDER_INVOICE, 'Provider Invoice'),
    (CONCEPT_PROVIDER_PAYMENT, 'Provider Payment'),
    (CONCEPT_PROVIDER_DEVOLUTION, 'Provider Devolution'),
    (CONCEPT_PROVIDER_DISCOUNT, 'Provider Discount'),
    (CONCEPT_DEPOSIT_REVERTION, 'Revertion of Deposit'),
    (CONCEPT_WITHDRAW_REVERTION, 'Revertion of Withdraw'),
    (CONCEPT_CURRENCY_EXCHANGE_REVERTION, 'Revertion of Currency Exchange'),
    (CONCEPT_TRANSFER_REVERTION, 'Revertion of Transfer'),
    (CONCEPT_LOAN_DEPOSIT_REVERTION, 'Revertion of Loan Deposit'),
    (CONCEPT_LOAN_WITHDRAW_REVERTION, 'Revertion of Loan Withdraw'),
    (CONCEPT_LOAN_ACCOUNT_DEPOSIT_REVERTION, 'Revertion of Loan Account Deposit'),
    (CONCEPT_LOAN_ACCOUNT_WITHDRAW_REVERTION, 'Revertion of Loan Account Withdraw'),
    (CONCEPT_AGENCY_INVOICE_REVERTION, 'Revertion of Agency Invoice'),
    (CONCEPT_AGENCY_PAYMENT_REVERTION, 'Revertion of Agency Payment'),
    (CONCEPT_AGENCY_DEVOLUTION_REVERTION, 'Revertion of Agency Devolution'),
    (CONCEPT_AGENCY_DISCOUNT_REVERTION, 'Revertion of Agency Discount'),
    (CONCEPT_PROVIDER_INVOICE_REVERTION, 'Revertion of Provider Invoice'),
    (CONCEPT_PROVIDER_PAYMENT_REVERTION, 'Revertion of Provider Payment'),
    (CONCEPT_PROVIDER_DEVOLUTION_REVERTION, 'Revertion of Provider Devolution'),
    (CONCEPT_PROVIDER_DISCOUNT_REVERTION, 'Revertion of Provider Discount'),
)
