CURRENCY_CUC = 'CUC'
CURRENCY_USD = 'USD'
CURRENCY_EUR = 'EUR'

CURRENCIES = (
    (CURRENCY_CUC, 'CUC'),
    (CURRENCY_USD, 'USD'),
    (CURRENCY_EUR, 'ÉUR'),
)

MOVEMENT_TYPE_DEPOSIT = 'D'
MOVEMENT_TYPE_WITHDRAW = 'W'

MOVEMENT_TYPES = (
    (MOVEMENT_TYPE_DEPOSIT, 'Deposit'),
    (MOVEMENT_TYPE_WITHDRAW, 'Withdraw'),
)

CONCEPT_DEPOSIT = 'DEPOSIT'
CONCEPT_WITHDRAW = 'WITHDRAW'
CONCEPT_CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE'
CONCEPT_TRANSFER = 'TRANSFER'
CONCEPT_LOAN_DEPOSIT = 'LOAN_DEPOSIT'
CONCEPT_LOAN_WITHDRAW = 'LOAN_WITHDRAW'
CONCEPT_LOAN_ACCOUNT_DEPOSIT = 'LOAN_ACCOUNT_DEPOSIT'
CONCEPT_LOAN_ACCOUNT_WITHDRAW = 'LOAN_ACCOUNT_WITHDRAW'
CONCEPT_AGENCY_INVOICE = 'AGENCY_INVOICE'
CONCEPT_AGENCY_PAYMENT = 'AGENCY_PAYMENT'
CONCEPT_AGENCY_DEVOLUTION = 'AGENCY_DEVOLUTION'
CONCEPT_AGENCY_DISCOUNT = 'AGENCY_DISCOUNT'
CONCEPT_PROVIDER_INVOICE = 'PROVIDER_INVOICE'
CONCEPT_PROVIDER_PAYMENT = 'PROVIDER_PAYMENT'
CONCEPT_PROVIDER_DEVOLUTION = 'PROVIDER_DEVOLUTION'
CONCEPT_PROVIDER_DISCOUNT = 'PROVIDER_DISCOUNT'

CONCEPTS = (
    (CONCEPT_DEPOSIT, 'Deposit'),
    (CONCEPT_WITHDRAW, 'Withdraw'),
    (CONCEPT_CURRENCY_EXCHANGE, 'Currency Exchange'),
    (CONCEPT_TRANSFER, 'Transfer'),
    (CONCEPT_LOAN_DEPOSIT, 'Loan Deposit'),
    (CONCEPT_LOAN_WITHDRAW, 'Loan Withdraw'),
    (CONCEPT_LOAN_ACCOUNT_DEPOSIT, 'Loan Account Deposit'),
    (CONCEPT_LOAN_ACCOUNT_WITHDRAW, 'Loan Account Withdraw'),
    (CONCEPT_AGENCY_INVOICE, 'Agency Invoice'),
    (CONCEPT_AGENCY_PAYMENT, 'Agency Payment'),
    (CONCEPT_AGENCY_DEVOLUTION, 'Agency Devolution'),
    (CONCEPT_AGENCY_DISCOUNT, 'Agency Discount'),
    (CONCEPT_PROVIDER_INVOICE, 'Provider Invoice'),
    (CONCEPT_PROVIDER_PAYMENT, 'Provider Payment'),
    (CONCEPT_PROVIDER_DEVOLUTION, 'Provider Devolution'),
    (CONCEPT_PROVIDER_DISCOUNT, 'Provider Discount'),
)
