# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('link_label', models.CharField(max_length=250)),
                ('link_url', models.CharField(max_length=250)),
                ('link_icon', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', '-link_time'),
                'verbose_name_plural': 'Recents Entries',
                'verbose_name': 'Recent Entry',
            },
        ),
        migrations.AlterUniqueTogether(
            name='recentlink',
            unique_together=set([('user', 'link_url')]),
        ),
        migrations.AlterIndexTogether(
            name='recentlink',
            index_together=set([('user', 'link_time')]),
        ),
    ]
