# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentlink',
            options={'ordering': ['user', '-link_time'], 'verbose_name': 'Recent Entry', 'verbose_name_plural': 'Recents Entries'},
        ),
    ]
