# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_new_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Organization = apps.get_model('common', 'Organization')
    Vinculation = apps.get_model('common', 'Vinculation')

    # create main organization
    main = Organization(name="TheNatureXperts", short_name="TNX")
    main.save()

    for user in User.objects.all():
        vinculation = Vinculation(user=user, organization=main)
        vinculation.save()


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organization_vinculation'),
    ]

    operations = [

        migrations.RunPython(migrate_new_data, backwards_function),

    ]
