# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-28 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=250)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CN', 'Cancelled')], default='PD', max_length=5)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('currency_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'default_permissions': ('add', 'change'),
            },
        ),
        migrations.CreateModel(
            name='BookingPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_name', models.CharField(max_length=50)),
                ('pax_age', models.SmallIntegerField(blank=True, null=True)),
                ('pax_group', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Booking Pax',
                'verbose_name_plural': 'Bookings Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Booking Service', max_length=250)),
                ('description', models.CharField(default='', max_length=1000)),
                ('datetime_from', models.DateTimeField(blank=True, null=True)),
                ('datetime_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CN', 'Cancelled')], default='PD', max_length=5)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Booking Service',
                'verbose_name_plural': 'Bookings Services',
                'default_permissions': ('add', 'change'),
            },
        ),
        migrations.CreateModel(
            name='BookingServicePax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Booking Service Pax',
                'verbose_name_plural': 'Bookings Services Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingServiceSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Booking Service Supplement',
                'verbose_name_plural': 'Bookings Services Supplements',
            },
        ),
        migrations.CreateModel(
            name='ServiceSupplementBookingPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_qtty', models.SmallIntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
                ('booking_pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingPax')),
            ],
            options={
                'verbose_name': 'Service Supplement Booking Pax',
                'verbose_name_plural': 'Services Supplements Bookings Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingAllotment',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
            ],
            options={
                'verbose_name': 'Booking Allotment',
                'verbose_name_plural': 'Bookings Allotments',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('quantity', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Booking Extra',
                'verbose_name_plural': 'Bookings Extras',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingTransfer',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Booking Transfer',
                'verbose_name_plural': 'Bookings Transfers',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingTransferSupplement',
            fields=[
                ('bookingservicesupplement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingServiceSupplement')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Booking Transfer Line Supplement',
                'verbose_name_plural': 'Bookings Transfers Lines Supplements',
            },
            bases=('booking.bookingservicesupplement',),
        ),
        migrations.AddField(
            model_name='servicesupplementbookingpax',
            name='service_supplment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingServiceSupplement'),
        ),
        migrations.AddField(
            model_name='bookingservicesupplement',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingService'),
        ),
    ]
