# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-09 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'booking', '0001_initial'), (b'booking', '0002_auto_20181003_1553'), (b'booking', '0003_auto_20181011_1750'), (b'booking', '0004_auto_20181019_1757'), (b'booking', '0005_bookingextra_parameter'), (b'booking', '0006_auto_20181029_1002'), (b'booking', '0007_auto_20181030_0937'), (b'booking', '0008_auto_20181030_1652'), (b'booking', '0009_auto_20181031_1208'), (b'booking', '0010_auto_20181106_1906'), (b'booking', '0011_auto_20181106_2003'), (b'booking', '0012_auto_20181106_2032'), (b'booking', '0013_auto_20181114_1443'), (b'booking', '0014_bookingservice_conf_number'), (b'booking', '0015_auto_20181118_1805'), (b'booking', '0016_auto_20181210_2206'), (b'booking', '0017_auto_20190126_2244'), (b'booking', '0018_auto_20190128_2036'), (b'booking', '0019_auto_20190128_2038'), (b'booking', '0020_auto_20190205_1258'), (b'booking', '0021_auto_20190205_1443'), (b'booking', '0022_auto_20190205_1532'), (b'booking', '0023_auto_20190205_1800'), (b'booking', '0024_auto_20190211_1039'), (b'booking', '0025_auto_20190215_1423'), (b'booking', '0026_auto_20190215_1656'), (b'booking', '0027_auto_20190215_1706'), (b'booking', '0028_auto_20190217_0823'), (b'booking', '0029_auto_20190219_1329'), (b'booking', '0030_bookinginvoiceline_bookinginvoicepartial'), (b'booking', '0031_auto_20190219_1342'), (b'booking', '0032_auto_20190219_1343'), (b'booking', '0033_quotepaxvariant_price_percent'), (b'booking', '0034_auto_20190301_1734'), (b'booking', '0035_auto_20190302_0806'), (b'booking', '0036_auto_20190309_0758'), (b'booking', '0037_auto_20190309_0833'), (b'booking', '0038_booking_p_notes'), (b'booking', '0039_auto_20190315_0003'), (b'booking', '0040_auto_20190322_1419'), (b'booking', '0041_auto_20190322_1708'), (b'booking', '0042_bookingpackageservice_conf_number'), (b'booking', '0043_auto_20190323_1206'), (b'booking', '0044_auto_20190324_2015'), (b'booking', '0045_auto_20190327_1214'), (b'booking', '0046_auto_20190402_0637'), (b'booking', '0047_auto_20190404_1649'), (b'booking', '0048_auto_20190404_1716'), (b'booking', '0049_auto_20190404_1723'), (b'booking', '0050_auto_20190405_1352'), (b'booking', '0051_auto_20190409_1230')]

    initial = True

    dependencies = [
        ('finance', '0013_auto_20190219_1436'),
        ('finance', '0002_finantialdocument_details'),
        ('config', '0019_auto_20190219_1026'),
        ('config', '0013_auto_20190205_1258'),
        ('finance', '0011_transfer_operation_cost'),
        ('config', '0007_auto_20181120_1510'),
        ('config', '0017_auto_20190215_1416'),
        ('config', '0005_auto_20181030_0937'),
        ('finance', '0001_initial'),
        ('config', '0001_initial'),
        ('config', '0018_auto_20190215_1522'),
        ('finance', '0015_auto_20190402_0637'),
        ('config', '0021_service_infant_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=25, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('currency_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
                ('name', models.CharField(default='Ronny Larsen x2', max_length=100)),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_name', models.CharField(max_length=50)),
                ('pax_age', models.SmallIntegerField(blank=True, null=True)),
                ('pax_group', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Booking Pax',
                'verbose_name_plural': 'Bookings Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Booking Service', max_length=250)),
                ('description', models.CharField(default='', max_length=1000)),
                ('datetime_from', models.DateTimeField(blank=True, null=True)),
                ('datetime_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CN', 'Cancelled')], default='PD', max_length=5)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Service',
                'verbose_name_plural': 'Bookings Services',
            },
        ),
        migrations.CreateModel(
            name='BookingServicePax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Booking Service Pax',
                'verbose_name_plural': 'Bookings Services Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingServiceSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Booking Service Supplement',
                'verbose_name_plural': 'Bookings Services Supplements',
            },
        ),
        migrations.CreateModel(
            name='ServiceSupplementBookingPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_qtty', models.SmallIntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
                ('booking_pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingPax')),
            ],
            options={
                'verbose_name': 'Service Supplement Booking Pax',
                'verbose_name_plural': 'Services Supplements Bookings Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingAllotment',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Accomodation',
                'verbose_name_plural': 'Bookings Accomodations',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('time', models.TimeField(blank=True, null=True)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Extra',
                'verbose_name_plural': 'Bookings Extras',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingTransfer',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='config.Location')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='config.Location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'verbose_name': 'Booking Transfer',
                'verbose_name_plural': 'Booking Transfers',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingTransferSupplement',
            fields=[
                ('bookingservicesupplement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingServiceSupplement')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Booking Transfer Line Supplement',
                'verbose_name_plural': 'Booking Transfer Line Supplements',
            },
            bases=('booking.bookingservicesupplement',),
        ),
        migrations.AddField(
            model_name='servicesupplementbookingpax',
            name='service_supplment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingServiceSupplement'),
        ),
        migrations.AddField(
            model_name='bookingservicesupplement',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingService'),
        ),
        migrations.AddField(
            model_name='bookingservicesupplement',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceSupplement'),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='booking_pax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingPax'),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingService'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.Booking'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderInvoice'),
        ),
        migrations.AddField(
            model_name='bookingpax',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='booking.Booking'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpax',
            unique_together=set([('booking', 'pax_name')]),
        ),
        migrations.AlterModelOptions(
            name='bookingservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Service', 'verbose_name_plural': 'Booking Services'},
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service_type',
            field=models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='status',
            field=models.CharField(choices=[(b'PD', b'Pending'), (b'RQ', b'Requested'), (b'PH', b'Phone Confirmed'), (b'OK', b'Confirmed'), (b'CD', b'Coordinated'), (b'CN', b'Cancelled')], default=b'PD', max_length=5),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=250)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('currency_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_quantity', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order')),
            ],
            options={
                'verbose_name': 'Order Pax',
                'verbose_name_plural': 'Orders Paxes',
            },
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='orderpax',
            unique_together=set([]),
        ),
        migrations.CreateModel(
            name='OrderPaxVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_quantity', models.SmallIntegerField()),
                ('cost_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Cost Single')),
                ('cost_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Cost Double')),
                ('cost_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Cost Triple')),
                ('price_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order')),
            ],
            options={
                'verbose_name': 'Order Pax',
                'verbose_name_plural': 'Orders Paxes',
            },
        ),
        migrations.RemoveField(
            model_name='orderpax',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderPax',
        ),
        migrations.AlterUniqueTogether(
            name='orderpaxvariant',
            unique_together=set([('order', 'pax_quantity')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'PD', b'Pending'), (b'RQ', b'Requested'), (b'OK', b'Confirmed')], default=b'PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_paxvariants', to='booking.Order'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_double_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Price Double'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Price Single'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Price Triple'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed')], default='PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='cost_double_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Double'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='cost_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Single'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='cost_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Triple'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_double_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Double'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Single'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Triple'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=250)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('RD', 'Ready')], default='DR', max_length=5)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('currency_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='QuotePaxVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_quantity', models.SmallIntegerField()),
                ('cost_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost SGL')),
                ('cost_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost DBL')),
                ('cost_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost TPL')),
                ('price_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price SGL')),
                ('price_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price DBL')),
                ('price_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price TPL')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_paxvariants', to='booking.Quote')),
                ('price_percent', models.SmallIntegerField(blank=True, null=True, verbose_name='Price %')),
            ],
            options={
                'verbose_name': 'Quote Pax',
                'verbose_name_plural': 'Quotes Paxes',
            },
        ),
        migrations.CreateModel(
            name='QuoteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quote Service', max_length=250)),
                ('service_type', models.CharField(blank=True, choices=[('E', 'Extra'), ('A', 'Allotment'), ('T', 'Transfer')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('datetime_from', models.DateTimeField(blank=True, null=True)),
                ('datetime_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Quote Service',
                'verbose_name_plural': 'Quote Services',
            },
        ),
        migrations.CreateModel(
            name='QuoteAllotment',
            fields=[
                ('quoteservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Quote Accomodation',
                'verbose_name_plural': 'Quotes Accomodations',
            },
            bases=('booking.quoteservice',),
        ),
        migrations.CreateModel(
            name='QuoteExtra',
            fields=[
                ('quoteservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteService')),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Quote Extra',
                'verbose_name_plural': 'Quotes Extras',
            },
            bases=('booking.quoteservice',),
        ),
        migrations.CreateModel(
            name='QuoteTransfer',
            fields=[
                ('quoteservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteService')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_location_to', to='config.Location', verbose_name='Location to')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Quote Transfer',
                'verbose_name_plural': 'Quotes Transfers',
            },
            bases=('booking.quoteservice',),
        ),
        migrations.AddField(
            model_name='quoteservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='quoteservice',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_services', to='booking.Quote'),
        ),
        migrations.AlterUniqueTogether(
            name='quotepaxvariant',
            unique_together=set([('quote', 'pax_quantity')]),
        ),
        migrations.RemoveField(
            model_name='order',
            name='agency',
        ),
        migrations.AlterUniqueTogether(
            name='orderpaxvariant',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderpaxvariant',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderPaxVariant',
        ),
        migrations.AlterModelOptions(
            name='bookingpax',
            options={'verbose_name': 'Booking Pax', 'verbose_name_plural': 'Booking Rooming List'},
        ),
        migrations.AlterModelOptions(
            name='bookingservicepax',
            options={'verbose_name': 'Booking Service Pax', 'verbose_name_plural': 'Booking Service Rooming'},
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='conf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_pickup', to='config.Allotment'),
        ),
        migrations.AlterModelOptions(
            name='bookingtransfer',
            options={'verbose_name': 'Booking Transfer', 'verbose_name_plural': 'Bookings Transfers'},
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='booking.BookingService'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date From'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date To'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date From'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date To'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Cost'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='pax_age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=b'Age'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='pax_group',
            field=models.SmallIntegerField(verbose_name=b'Room'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Price'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Cost'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='group',
            field=models.SmallIntegerField(verbose_name=b'Room'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Price'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='pax_age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='pax_group',
            field=models.SmallIntegerField(verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='group',
            field=models.SmallIntegerField(verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_to', to='config.Schedule'),
        ),
        migrations.CreateModel(
            name='BookingInvoice',
            fields=[
                ('agencyinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyInvoice')),
                ('booking_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=25, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking Invoice',
                'verbose_name_plural': 'Bookings Invoices',
            },
            bases=('finance.agencyinvoice',),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInvoice'),
        ),
        migrations.CreateModel(
            name='BookingInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('bookingservice_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('qtty', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInvoice')),
            ],
            options={
                'verbose_name': 'Booking Invoice Line',
                'verbose_name_plural': 'Bookings Invoices Lines',
            },
        ),
        migrations.CreateModel(
            name='BookingInvoicePartial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_name', models.CharField(blank=True, max_length=100, null=True)),
                ('detail2', models.CharField(blank=True, max_length=100, null=True)),
                ('partial_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInvoice')),
            ],
            options={
                'verbose_name': 'Booking Invoice Partial',
                'verbose_name_plural': 'Bookings Invoices Partials',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.Service')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
            bases=('config.service',),
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Base Service', max_length=250)),
                ('days_after', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Days after')),
                ('days_duration', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Days duration')),
                ('service_type', models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Package Service',
                'verbose_name_plural': 'Packages Services',
            },
        ),
        migrations.CreateModel(
            name='QuotePackage',
            fields=[
                ('quoteservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteService')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
                ('price_by_package_catalogue', models.BooleanField(default=False, verbose_name='By Catalogue')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Quote Package',
                'verbose_name_plural': 'Quotes Packages',
            },
            bases=('booking.quoteservice',),
        ),
        migrations.CreateModel(
            name='QuotePackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Base Service', max_length=250)),
                ('service_type', models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('datetime_from', models.DateField(blank=True, null=True, verbose_name='Date From')),
                ('datetime_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Quote Package Service',
                'verbose_name_plural': 'Quotes Packages Services',
            },
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='name',
            field=models.CharField(default='Base Service', max_length=250),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='name',
            field=models.CharField(default='Base Service', max_length=250),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='service_type',
            field=models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='PackageAllotment',
            fields=[
                ('packageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.PackageService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'verbose_name': 'Package Accomodation',
                'verbose_name_plural': 'Packages Accomodations',
            },
            bases=('booking.packageservice', models.Model),
        ),
        migrations.CreateModel(
            name='PackageExtra',
            fields=[
                ('packageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.PackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
            ],
            options={
                'verbose_name': 'Package Extra',
                'verbose_name_plural': 'Packages Extras',
            },
            bases=('booking.packageservice', models.Model),
        ),
        migrations.CreateModel(
            name='PackageTransfer',
            fields=[
                ('packageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.PackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_location_to', to='config.Location', verbose_name='Location to')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'verbose_name': 'Package Transfer',
                'verbose_name_plural': 'Packages Transfers',
            },
            bases=('booking.packageservice', models.Model),
        ),
        migrations.CreateModel(
            name='QuotePackageAllotment',
            fields=[
                ('quotepackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuotePackageService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Quote Package Accomodation',
                'verbose_name_plural': 'Quotes Packages Accomodations',
            },
            bases=('booking.quotepackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='QuotePackageExtra',
            fields=[
                ('quotepackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuotePackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Quote Package Extra',
                'verbose_name_plural': 'Quotes Packages Extras',
            },
            bases=('booking.quotepackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='QuotePackageTransfer',
            fields=[
                ('quotepackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuotePackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_package_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_package_location_to', to='config.Location', verbose_name='Location to')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Quote Package Transfer',
                'verbose_name_plural': 'Quotes Packages Transfers',
            },
            bases=('booking.quotepackageservice', models.Model),
        ),
        migrations.AddField(
            model_name='quotepackageservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='quotepackageservice',
            name='quote_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_package_services', to='booking.QuotePackage'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='booking.Package'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_pickup', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_schedule_to', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_package_price',
            field=models.BooleanField(default=False, verbose_name='Package Price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_dbl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price DBL'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_sgl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price SGL'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_tpl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price TPL'),
        ),
        migrations.AddField(
            model_name='booking',
            name='p_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Private Notes'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='p_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Private Notes'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Provider Notes'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='v_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Voucher Notes'),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='is_cost_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='is_price_free',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
                ('price_by_package_catalogue', models.BooleanField(default=True, verbose_name='Use Catalogue Price')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Package',
                'verbose_name_plural': 'Bookings Packages',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingPackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateField(blank=True, null=True, verbose_name='Date From')),
                ('datetime_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('name', models.CharField(default='Base Service', max_length=250)),
                ('service_type', models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Booking Package Service',
                'verbose_name_plural': 'Bookingss Packages Services',
            },
        ),
        migrations.CreateModel(
            name='BookingPackageAllotment',
            fields=[
                ('bookingpackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingPackageService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Package Accomodation',
                'verbose_name_plural': 'Bookings Packages Accomodations',
            },
            bases=('booking.bookingpackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='BookingPackageExtra',
            fields=[
                ('bookingpackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingPackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Package Extra',
                'verbose_name_plural': 'Bookings Packages Extras',
            },
            bases=('booking.bookingpackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='BookingPackageTransfer',
            fields=[
                ('bookingpackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingPackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('dropoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_transfer_dropoff', to='config.Allotment')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_location_to', to='config.Location', verbose_name='Location to')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_transfer_pickup', to='config.Allotment')),
                ('place_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_place_from', to='config.Place')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_place_to', to='config.Place')),
                ('schedule_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_schedule_from', to='config.Schedule')),
                ('schedule_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_schedule_to', to='config.Schedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Package Transfer',
                'verbose_name_plural': 'Bookingss Packages Transfers',
            },
            bases=('booking.bookingpackageservice', models.Model),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='booking_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_services', to='booking.BookingPackage'),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='conf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], default=b'CUC', max_length=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'CUP', b'CUP')], default=b'CUC', max_length=5),
        ),
        migrations.CreateModel(
            name='AgencyPackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SGL')),
                ('ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DBL')),
                ('ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='TPL')),
                ('ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='QAD')),
                ('ch_1_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_2_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_3_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
            ],
            options={
                'verbose_name': 'Agency Package Detail',
                'verbose_name_plural': 'Agencies Package Details',
            },
        ),
        migrations.CreateModel(
            name='AgencyPackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
            ],
            options={
                'verbose_name': 'Agency Package Service',
                'verbose_name_plural': 'Agency Packages Services',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], default='CUC', max_length=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], default='CUC', max_length=5),
        ),
        migrations.AddField(
            model_name='agencypackagedetail',
            name='agency_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.AgencyPackageService'),
        ),
        migrations.AlterUniqueTogether(
            name='agencypackageservice',
            unique_together=set([('agency', 'service', 'date_from', 'date_to')]),
        ),
        migrations.AddField(
            model_name='agencypackagedetail',
            name='pax_range_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencypackagedetail',
            name='pax_range_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='agencypackagedetail',
            unique_together=set([('agency_service', 'pax_range_min', 'pax_range_max')]),
        ),
        migrations.AddField(
            model_name='package',
            name='amounts_type',
            field=models.CharField(choices=[('F', 'Fixed'), ('P', 'By Pax')], default='P', max_length=5),
        ),
        migrations.AddField(
            model_name='package',
            name='has_pax_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='TTOO Ref'),
        ),
        migrations.AlterModelOptions(
            name='bookingpackageservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Package Service', 'verbose_name_plural': 'Bookingss Packages Services'},
        ),
        migrations.AlterModelOptions(
            name='bookingtransfer',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Transfer', 'verbose_name_plural': 'Bookings Transfers'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='quotepackageservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Package Service', 'verbose_name_plural': 'Quotes Packages Services'},
        ),
        migrations.AlterModelOptions(
            name='quoteservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Service', 'verbose_name_plural': 'Quote Services'},
        ),
    ]
