# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=250)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[(b'PD', b'Pending'), (b'RQ', b'Requested'), (b'OK', b'Confirmed'), (b'CN', b'Cancelled')], default=b'PD', max_length=5)),
                ('currency', models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR')], default=b'CUC', max_length=5)),
                ('currency_factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
                ('agency_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.AgencyInvoice')),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_name', models.CharField(max_length=50)),
                ('pax_age', models.SmallIntegerField(blank=True, null=True)),
                ('pax_group', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
            options={
                'verbose_name': 'Booking Pax',
                'verbose_name_plural': 'Bookings Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingPaxServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
                ('booking_pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingPax')),
            ],
            options={
                'verbose_name': 'Booking Pax Service Group',
                'verbose_name_plural': 'Bookings Paxes Services Groups',
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'PD', b'Pending'), (b'RQ', b'Requested'), (b'OK', b'Confirmed'), (b'CN', b'Cancelled')], default=b'PD', max_length=5)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
            ],
            options={
                'default_permissions': ('add', 'change'),
                'verbose_name': 'Booking Service',
                'verbose_name_plural': 'Bookings Services',
            },
        ),
        migrations.CreateModel(
            name='BookingServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Booking Service Group',
                'verbose_name_plural': 'Bookings Services Group',
            },
        ),
        migrations.CreateModel(
            name='BookingServiceSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Booking Service Supplement',
                'verbose_name_plural': 'Bookings Services Supplements',
            },
        ),
        migrations.CreateModel(
            name='ServiceSupplementBookingPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_qtty', models.SmallIntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
                ('booking_pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingPax')),
            ],
            options={
                'verbose_name': 'Service Supplement Booking Pax',
                'verbose_name_plural': 'Services Supplements Bookings Paxes',
            },
        ),
        migrations.CreateModel(
            name='BookingAllotment',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('board_type', models.CharField(choices=[(b'NB', b'None Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentRoomType')),
            ],
            options={
                'verbose_name': 'Booking Allotment',
                'verbose_name_plural': 'Bookings Allotments',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('extra_qtty', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Booking Extra',
                'verbose_name_plural': 'Bookings Extras',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingTransfer',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
            ],
            options={
                'verbose_name': 'Booking Transfer',
                'verbose_name_plural': 'Bookings Transfers',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingTransferSupplement',
            fields=[
                ('bookingservicesupplement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingServiceSupplement')),
                ('hours', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Booking Transfer Line Supplement',
                'verbose_name_plural': 'Bookings Transfers Lines Supplements',
            },
            bases=('booking.bookingservicesupplement',),
        ),
        migrations.AddField(
            model_name='servicesupplementbookingpax',
            name='service_supplment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingServiceSupplement'),
        ),
        migrations.AddField(
            model_name='bookingservicesupplement',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingService'),
        ),
        migrations.AddField(
            model_name='bookingservicesupplement',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceSupplement'),
        ),
        migrations.AddField(
            model_name='bookingservicegroup',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingService'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderInvoice'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Service'),
        ),
        migrations.AddField(
            model_name='bookingpaxservicegroup',
            name='service_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingServiceGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpax',
            unique_together=set([('booking', 'pax_name')]),
        ),
    ]
