# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebookingservice',
            name='base_category',
            field=models.CharField(blank=True, choices=[('BA', 'Booking Allotment'), ('BT', 'Booking Transfer'), ('BE', 'Booking Extra'), ('BP', 'Booking Package'), ('PA', 'Booking Package Allotment'), ('PT', 'Booking Package Transfer'), ('PE', 'Booking Package Extra')], max_length=5, null=True),
        ),
    ]
