# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('config', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservicesupplement',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceSupplement'),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='booking_pax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingPax'),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingService'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.Booking'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderInvoice'),
        ),
        migrations.AddField(
            model_name='bookingpax',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='booking.Booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency'),
        ),
        migrations.AddField(
            model_name='booking',
            name='agency_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.AgencyInvoice'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='config.Location'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='config.Location'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpax',
            unique_together=set([('booking', 'pax_name')]),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra'),
        ),
        migrations.AddField(
            model_name='bookingallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType'),
        ),
        migrations.AddField(
            model_name='bookingallotment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment'),
        ),
    ]
