# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
