# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180913_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpax',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='cost_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='price_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
