# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181003_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Service', 'verbose_name_plural': 'Booking Services'},
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service_type',
            field=models.CharField(blank=True, choices=[(b'E', b'Extra'), (b'A', b'Allotment'), (b'T', b'Transfer')], max_length=5, null=True),
        ),
    ]
