# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-12 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190411_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'default_permissions': ('add', 'change'), 'permissions': (('change_amounts', 'Can change amounts of Booking'),), 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
