# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models

from booking import constants

def update_cost_amount_to_pay(apps, schema_editor):
    BaseBookingService = apps.get_model('booking', 'BaseBookingService')

    for bbs in BaseBookingService.objects.all():
        if bbs.status in [
                constants.SERVICE_STATUS_PENDING, constants.SERVICE_STATUS_REQUEST,
                constants.SERVICE_STATUS_CANCELLED]:
            bbs.cost_amount_to_pay = 0.00
        elif bbs.cost_amount is None:
            bbs.cost_amount_to_pay = 0.00
        else:
            bbs.cost_amount_to_pay = bbs.cost_amount
        bbs.save(force_update=True, update_fields=['cost_amount_to_pay'])


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191008_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebookingservice',
            name='cost_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='basebookingservice',
            name='cost_amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='basebookingservice',
            name='has_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerbookingpaymentservice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='providerbookingpaymentservice',
            name='service_cost_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='providerbookingpaymentservice',
            name='service_cost_amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RunPython(update_cost_amount_to_pay, backwards_function),
    ]
