# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_office_default_office'),
        ('booking', '0003_auto_20190412_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackageservice',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='cost_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='manual_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='manual_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='p_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Private Notes'),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='price_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='provider_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.ProviderInvoice'),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='provider_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Provider Notes'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='manual_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='manual_price',
            field=models.BooleanField(default=False),
        ),
    ]
