# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-25 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180922_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpax',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='bookingpaxservicegroup',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpaxservicegroup',
            name='cost_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpaxservicegroup',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpaxservicegroup',
            name='price_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
