# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-16 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191012_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderBookingPaymentService',
        ),
        migrations.DeleteModel(
            name='ProviderBookingPayment',
        ),
        migrations.CreateModel(
            name='ProviderBookingPayment',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Withdraw')),
                ('provider', models.ForeignKey(on_delete=models.deletion.CASCADE, to='finance.Provider')),
            ],
            options={
                'verbose_name': 'Provider Booking Payment',
                'verbose_name_plural': 'Providers Bookings Payments',
            },
            bases=('finance.withdraw',),
        ),
        migrations.CreateModel(
            name='ProviderBookingPaymentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_cost_amount_to_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_cost_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provider_payment', models.ForeignKey(on_delete=models.deletion.CASCADE, to='booking.ProviderBookingPayment')),
                ('provider_service', models.ForeignKey(on_delete=models.deletion.CASCADE, to='booking.BaseBookingService')),
            ],
            options={
                'verbose_name': 'Provider Booking Payment',
                'verbose_name_plural': 'Providers Bookings Payments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='providerbookingpaymentservice',
            unique_together=set([('provider_payment', 'provider_service')]),
        ),
    ]
