# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180922_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingServicePax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comments', models.CharField(max_length=1000)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_comments', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Booking Pax Service Group',
                'verbose_name_plural': 'Bookings Paxes Services Groups',
            },
        ),
        migrations.RemoveField(
            model_name='bookingpaxservicegroup',
            name='booking_pax',
        ),
        migrations.RemoveField(
            model_name='bookingpaxservicegroup',
            name='service_group',
        ),
        migrations.RemoveField(
            model_name='bookingservicegroup',
            name='booking_service',
        ),
        migrations.AlterField(
            model_name='bookingpax',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='booking.Booking'),
        ),
        migrations.DeleteModel(
            name='BookingPaxServiceGroup',
        ),
        migrations.DeleteModel(
            name='BookingServiceGroup',
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='booking_pax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingPax'),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingService'),
        ),
    ]
