# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-16 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191012_0926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerbookingpaymentservice',
            unique_together=set([('provider_payment', 'provider_service')]),
        ),
    ]
