# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_office_default_office'),
        ('booking', '0004_auto_20190412_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
            ],
            options={
                'verbose_name': 'Provider Package Service',
                'verbose_name_plural': 'Providers Packages Services',
            },
        ),
        migrations.AlterUniqueTogether(
            name='providerpackageservice',
            unique_together=set([('provider', 'service', 'date_from', 'date_to')]),
        ),
    ]
