# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20191024_1432'),
        ('booking', '0004_auto_20191016_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.AgencyContact'),
        ),
    ]
