# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20181019_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingextra',
            name='parameter',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
