# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180925_1558'),
        ('booking', '0004_auto_20180925_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingextra',
            old_name='extra_qtty',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='bookingtransfersupplement',
            name='hours',
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='location_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='config.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='location_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='config.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingtransfersupplement',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
