# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180925_1558'),
        ('booking', '0004_auto_20180924_2207'),
    ]

    operations = [
    ]
