# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180925_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingservicepax',
            options={'verbose_name': 'Booking Service Pax', 'verbose_name_plural': 'Bookings Services Paxes'},
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='cost_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='price_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
