# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_agency_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingservice',
            old_name='datetime_from',
            new_name='datetime_from1',
        ),
        migrations.RenameField(
            model_name='bookingservice',
            old_name='datetime_to',
            new_name='datetime_to1',
        ),
        migrations.RenameField(
            model_name='bookingpackageservice',
            old_name='datetime_from',
            new_name='datetime_from1',
        ),
        migrations.RenameField(
            model_name='bookingpackageservice',
            old_name='datetime_to',
            new_name='datetime_to1',
        ),
        migrations.AddField(
            model_name='basebookingservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date From'),
        ),
        migrations.AddField(
            model_name='basebookingservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date To'),
        ),
        migrations.AlterModelOptions(
            name='bookingpackageservice',
            options={'ordering': ['datetime_from'], 'verbose_name': 'Booking Package Service', 'verbose_name_plural': 'Bookings Packages Services'},
        ),
    ]
