# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookingextra_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(b'PD', b'Pending'), (b'RQ', b'Requested'), (b'OK', b'Confirmed'), (b'CD', b'Coordinated'), (b'CN', b'Cancelled')], default=b'PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='status',
            field=models.CharField(choices=[(b'PD', b'Pending'), (b'RQ', b'Requested'), (b'PH', b'Phone Confirmed'), (b'OK', b'Confirmed'), (b'CD', b'Coordinated'), (b'CN', b'Cancelled')], default=b'PD', max_length=5),
        ),
    ]
