# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20181030_0937'),
        ('finance', '0002_finantialdocument_details'),
        ('booking', '0006_auto_20181029_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=250)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('currency_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_quantity', models.SmallIntegerField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order')),
            ],
            options={
                'verbose_name': 'Order Pax',
                'verbose_name_plural': 'Orders Paxes',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Booking Service', max_length=250)),
                ('service_type', models.CharField(blank=True, choices=[('E', 'Extra'), ('A', 'Allotment'), ('T', 'Transfer')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('datetime_from', models.DateTimeField(blank=True, null=True)),
                ('datetime_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Order Service',
                'verbose_name_plural': 'Order Services',
            },
        ),
        migrations.CreateModel(
            name='OrderServicePax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.OrderPax')),
            ],
            options={
                'verbose_name': 'Order Service Pax',
                'verbose_name_plural': 'Orders Services Paxes',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5),
        ),
        migrations.CreateModel(
            name='OrderAllotment',
            fields=[
                ('orderservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.OrderService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'verbose_name': 'Order Allotment',
                'verbose_name_plural': 'Orders Allotments',
            },
            bases=('booking.orderservice',),
        ),
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('orderservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.OrderService')),
                ('parameter', models.SmallIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
            ],
            options={
                'verbose_name': 'Order Extra',
                'verbose_name_plural': 'Orders Extras',
            },
            bases=('booking.orderservice',),
        ),
        migrations.CreateModel(
            name='OrderTransfer',
            fields=[
                ('orderservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.OrderService')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_location_to', to='config.Location', verbose_name='Location to')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'verbose_name': 'Order Transfer',
                'verbose_name_plural': 'Orders Transfers',
            },
            bases=('booking.orderservice',),
        ),
        migrations.AddField(
            model_name='orderservicepax',
            name='order_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.OrderService'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AlterUniqueTogether(
            name='orderpax',
            unique_together=set([('order', 'pax_quantity')]),
        ),
    ]
