# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models

from booking import constants

def update_base_booking_data(apps, schema_editor):
    BaseBookingService = apps.get_model('booking', 'BaseBookingService')
    BookingService = apps.get_model('booking', 'BookingService')
    BookingPackageService = apps.get_model('booking', 'BookingPackageService')

    for bbs in BaseBookingService.objects.all():
        if bbs.base_category in [
                constants.BASE_BOOKING_SERVICE_CATEGORY_BOOKING_ALLOTMENT,
                constants.BASE_BOOKING_SERVICE_CATEGORY_BOOKING_TRANSFER,
                constants.BASE_BOOKING_SERVICE_CATEGORY_BOOKING_EXTRA,
                constants.BASE_BOOKING_SERVICE_CATEGORY_BOOKING_PACKAGE]:
            bs = BookingService.objects.get(pk=bbs.id)
        elif bbs.base_category in [
                constants.BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_ALLOTMENT,
                constants.BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_TRANSFER,
                constants.BASE_BOOKING_SERVICE_CATEGORY_PACKAGE_EXTRA]:
            bs = BookingPackageService.objects.get(pk=bbs.id)
        else:
            continue
        bbs.datetime_from = bs.datetime_from1
        bbs.datetime_to = bs.datetime_to1
        bbs.save(update_fields=['datetime_from', 'datetime_to'])

def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20191028_1703'),
    ]

    operations = [

        migrations.RunPython(update_base_booking_data, backwards_function),

    ]
