# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190422_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteServicePaxVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_cost_single', models.BooleanField(default=False)),
                ('cost_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost SGL')),
                ('manual_cost_double', models.BooleanField(default=False)),
                ('cost_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost DBL')),
                ('manual_cost_triple', models.BooleanField(default=False)),
                ('cost_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost TPL')),
                ('manual_price_single', models.BooleanField(default=False)),
                ('price_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price SGL')),
                ('manual_price_double', models.BooleanField(default=False)),
                ('price_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price DBL')),
                ('manual_price_triple', models.BooleanField(default=False)),
                ('price_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price TPL')),
                ('price_percent', models.SmallIntegerField(blank=True, null=True, verbose_name='Price %')),
            ],
            options={
                'verbose_name': 'Quote Service Pax Variant',
                'verbose_name_plural': 'Quotes Services Paxes Variants',
            },
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='manual_cost_double',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='manual_cost_single',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='manual_cost_triple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='manual_price_double',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='manual_price_single',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='manual_price_triple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='quote_pax_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.QuotePaxVariant'),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='quote_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteservice_paxvariants', to='booking.QuoteService'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteservicepaxvariant',
            unique_together=set([('quote_pax_variant', 'quote_service')]),
        ),
    ]
