# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-28 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190424_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepaxvariant',
            name='manual_cost_double',
        ),
        migrations.RemoveField(
            model_name='quotepaxvariant',
            name='manual_cost_single',
        ),
        migrations.RemoveField(
            model_name='quotepaxvariant',
            name='manual_cost_triple',
        ),
        migrations.RemoveField(
            model_name='quotepaxvariant',
            name='manual_price_double',
        ),
        migrations.RemoveField(
            model_name='quotepaxvariant',
            name='manual_price_single',
        ),
        migrations.RemoveField(
            model_name='quotepaxvariant',
            name='manual_price_triple',
        ),
        migrations.RemoveField(
            model_name='quoteservicepaxvariant',
            name='manual_cost_double',
        ),
        migrations.RemoveField(
            model_name='quoteservicepaxvariant',
            name='manual_cost_single',
        ),
        migrations.RemoveField(
            model_name='quoteservicepaxvariant',
            name='manual_cost_triple',
        ),
        migrations.RemoveField(
            model_name='quoteservicepaxvariant',
            name='manual_price_double',
        ),
        migrations.RemoveField(
            model_name='quoteservicepaxvariant',
            name='manual_price_single',
        ),
        migrations.RemoveField(
            model_name='quoteservicepaxvariant',
            name='manual_price_triple',
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='manual_costs',
            field=models.BooleanField(default=False, verbose_name='Manual Costs'),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='manual_prices',
            field=models.BooleanField(default=False, verbose_name='Manual Prices'),
        ),
    ]
