# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20191028_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpackageservice',
            name='datetime_from1',
        ),
        migrations.RemoveField(
            model_name='bookingpackageservice',
            name='datetime_to1',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='datetime_from1',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='datetime_to1',
        ),
    ]
