# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20181030_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaxVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_quantity', models.SmallIntegerField()),
                ('cost_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_single_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_double_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_triple_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order')),
            ],
            options={
                'verbose_name': 'Order Pax',
                'verbose_name_plural': 'Orders Paxes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderpax',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderpax',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderservicepax',
            name='order_pax',
        ),
        migrations.RemoveField(
            model_name='orderservicepax',
            name='order_service',
        ),
        migrations.DeleteModel(
            name='OrderPax',
        ),
        migrations.DeleteModel(
            name='OrderServicePax',
        ),
        migrations.AlterUniqueTogether(
            name='orderpaxvariant',
            unique_together=set([('order', 'pax_quantity')]),
        ),
    ]
