# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


def update_base_booking_data(apps, schema_editor):
    BaseBookingService = apps.get_model('booking', 'BaseBookingService')
    BookingService = apps.get_model('booking', 'BookingService')
    BookingPackageService = apps.get_model('booking', 'BookingPackageService')

    for bs in BookingService.objects.all():
        bbs = BaseBookingService.objects.get(pk=bs.pk)
        bbs.booking_temp = bs.booking.pk
        bbs.save()
    for bps in BookingPackageService.objects.all():
        bbs = BaseBookingService.objects.get(pk=bps.id)
        bbs.booking_temp = bps.booking_package.booking_id
        bbs.save()


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20191028_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebookingservice',
            name='booking_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(update_base_booking_data, backwards_function),
    ]
