# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-28 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190428_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quoteservicepaxvariant',
            name='quote_pax_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.QuotePaxVariant', verbose_name='Pax Variant'),
        ),
    ]
