# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20181031_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed')], default='PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='cost_double_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Double'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='cost_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Single'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='cost_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Triple'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_double_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Double'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Single'),
        ),
        migrations.AlterField(
            model_name='orderpaxvariant',
            name='price_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Triple'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='name',
            field=models.CharField(default='Order Service', max_length=250),
        ),
    ]
