# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-10 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def update_base_booking_data(apps, schema_editor):
    BaseBookingService = apps.get_model('booking', 'BaseBookingService')

    for bbs in BaseBookingService.objects.all():
        bbs.booking_id = bbs.booking_temp
        bbs.save()


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_basebookingservice_booking_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='booking',
        ),
        migrations.AddField(
            model_name='basebookingservice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.Booking'),
        ),
        migrations.RunPython(update_base_booking_data, backwards_function),
    ]
