# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-30 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190428_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteservicepaxvariant',
            name='price_percent',
        ),
        migrations.AddField(
            model_name='quote',
            name='history',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='quote',
            name='program',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Program'),
        ),
    ]
