# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-10 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20191109_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basebookingservice',
            name='booking_temp',
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='booking',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.Booking'),
            preserve_default=False,
        ),
    ]
