# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20190503_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotepackageservicepaxvariant',
            old_name='quote_package_service',
            new_name='quotepackage_service',
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='quotepackage_pax_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.QuoteServicePaxVariant', verbose_name='Pax Variant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quotepackageservicepaxvariant',
            name='quote_pax_variant',
        ),
        migrations.AlterUniqueTogether(
            name='quotepackageservicepaxvariant',
            unique_together=set([('quotepackage_pax_variant', 'quotepackage_service')]),
        ),
    ]
