# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20181106_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='orderallotment',
            name='orderservice_ptr',
        ),
        migrations.RemoveField(
            model_name='orderallotment',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='orderallotment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='orderextra',
            name='orderservice_ptr',
        ),
        migrations.RemoveField(
            model_name='orderextra',
            name='service',
        ),
        migrations.AlterUniqueTogether(
            name='orderpaxvariant',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderpaxvariant',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='ordertransfer',
            name='location_from',
        ),
        migrations.RemoveField(
            model_name='ordertransfer',
            name='location_to',
        ),
        migrations.RemoveField(
            model_name='ordertransfer',
            name='orderservice_ptr',
        ),
        # Manually removed this to avoid
        # letting OrderTransfer field-less
        #
        # migrations.RemoveField(
        #     model_name='ordertransfer',
        #     name='service',
        # ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAllotment',
        ),
        migrations.DeleteModel(
            name='OrderExtra',
        ),
        migrations.DeleteModel(
            name='OrderPaxVariant',
        ),
        migrations.DeleteModel(
            name='OrderService',
        ),
        migrations.DeleteModel(
            name='OrderTransfer',
        ),
    ]
