# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-12 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20190503_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepaxvariant',
            name='free_quantity',
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_cost_double',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_cost_single',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_cost_triple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_free_double',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_free_triple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_price_single',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_cost_double',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_cost_single',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_cost_triple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_free_double',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_free_triple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_price_single',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_cost_double',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_cost_single',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_cost_triple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_free_double',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_free_triple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_price_single',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotepackage',
            name='price_by_package_catalogue',
            field=models.BooleanField(default=False, verbose_name='Prices By Catalogue'),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='quote_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotepackage_services', to='booking.QuotePackage'),
        ),
    ]
