# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-18 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20190511_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotepackageservicepaxvariant',
            old_name='free_free_double',
            new_name='free_price_double',
        ),
        migrations.RenameField(
            model_name='quotepackageservicepaxvariant',
            old_name='free_free_triple',
            new_name='free_price_triple',
        ),
        migrations.RenameField(
            model_name='quotepaxvariant',
            old_name='free_free_double',
            new_name='free_price_double',
        ),
        migrations.RenameField(
            model_name='quotepaxvariant',
            old_name='free_free_triple',
            new_name='free_price_triple',
        ),
        migrations.RenameField(
            model_name='quoteservicepaxvariant',
            old_name='free_free_double',
            new_name='free_price_double',
        ),
        migrations.RenameField(
            model_name='quoteservicepaxvariant',
            old_name='free_free_triple',
            new_name='free_price_triple',
        ),
    ]
