# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20181114_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='conf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
