# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_bookingservice_conf_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='cost_double_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost DBL'),
        ),
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='cost_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost SGL'),
        ),
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='cost_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost TPL'),
        ),
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='price_double_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price DBL'),
        ),
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='price_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price SGL'),
        ),
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='price_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price TPL'),
        ),
    ]
