# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20191122_1438'),
        ('booking', '0015_auto_20191121_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='bookingpackageextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackage_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='bookingpackageextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackage_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='packageextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='packageextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='quoteextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='quoteextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='quotepackageextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackage_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='quotepackageextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackage_pickup_office', to='config.CarRentalOffice'),
        ),
    ]
