# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-11 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20181120_1510'),
        ('booking', '0015_auto_20181118_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_pickup', to='config.Allotment'),
        ),
    ]
