# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20181210_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingallotment',
            options={'verbose_name': 'Booking Accomodation', 'verbose_name_plural': 'Bookings Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='bookingextra',
            options={'verbose_name': 'Booking Extra', 'verbose_name_plural': 'Bookings Extras'},
        ),
        migrations.AlterModelOptions(
            name='bookingtransfer',
            options={'verbose_name': 'Booking Transfer', 'verbose_name_plural': 'Bookings Transfers'},
        ),
        migrations.AlterModelOptions(
            name='quoteallotment',
            options={'verbose_name': 'Quote Accomodation', 'verbose_name_plural': 'Quotes Accomodations'},
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteextra',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='booking.BookingService'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
