# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20191122_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebookingservice',
            name='cost_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid'),
        ),
    ]
