# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20190126_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteextra',
            name='quantity',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date From'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date To'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date From'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='datetime_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date To'),
        ),
    ]
