# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20190616_0752'),
        ('booking', '0017_auto_20190610_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_format',
            field=models.CharField(choices=[('C', 'Compact'), ('D', 'Detail')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='invoice_booking',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookingpackageallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='packageallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quoteallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quotepackageallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('invoice',)]),
        ),
    ]
