# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models

from datetime import time

def update_time_new(apps, schema_editor):
    PackageAllotment = apps.get_model('booking', 'PackageAllotment')
    PackageTransfer = apps.get_model('booking', 'PackageTransfer')
    PackageExtra = apps.get_model('booking', 'PackageExtra')
    QuoteAllotment = apps.get_model('booking', 'QuoteAllotment')
    QuoteTransfer = apps.get_model('booking', 'QuoteTransfer')
    QuoteExtra = apps.get_model('booking', 'QuoteExtra')
    QuotePackage = apps.get_model('booking', 'QuotePackage')
    QuotePackageAllotment = apps.get_model('booking', 'QuotePackageAllotment')
    QuotePackageTransfer = apps.get_model('booking', 'QuotePackageTransfer')
    QuotePackageExtra = apps.get_model('booking', 'QuotePackageExtra')
    BookingAllotment = apps.get_model('booking', 'BookingAllotment')
    BookingTransfer = apps.get_model('booking', 'BookingTransfer')
    BookingExtra = apps.get_model('booking', 'BookingExtra')
    BookingPackage = apps.get_model('booking', 'BookingPackage')
    BookingPackageAllotment = apps.get_model('booking', 'BookingPackageAllotment')
    BookingPackageTransfer = apps.get_model('booking', 'BookingPackageTransfer')
    BookingPackageExtra = apps.get_model('booking', 'BookingPackageExtra')

    entity_models = [
        PackageTransfer, PackageExtra,
        QuoteTransfer, QuoteExtra, QuotePackage, QuotePackageTransfer, QuotePackageExtra,
        BookingTransfer, BookingExtra, BookingPackage, BookingPackageTransfer, BookingPackageExtra,
    ]
    for entity_model in entity_models:
        for reg in entity_model.objects.all():
            reg.time_new = reg.time
            reg.save()
    entity_models = [
        PackageAllotment,
        QuoteAllotment, QuotePackageAllotment,
        BookingAllotment, BookingPackageAllotment,
    ]
    for entity_model in entity_models:
        for reg in entity_model.objects.all():
            reg.time_new = time(23, 59, 59)
            reg.save()


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20191201_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebookingservice',
            name='time_new',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='time_new',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotepackageservice',
            name='time_new',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteservice',
            name='time_new',
            field=models.TimeField(blank=True, null=True),
        ),

        migrations.RunPython(update_time_new, backwards_function),

    ]
