# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0017_auto_20190610_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingallotment',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookingpackageallotment',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='packageallotment',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quoteallotment',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quotepackageallotment',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
    ]
