# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20190128_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteextra',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
