# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20191205_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingextra',
            name='time',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='time',
        ),
        migrations.RemoveField(
            model_name='bookingpackageextra',
            name='time',
        ),
        migrations.RemoveField(
            model_name='bookingpackagetransfer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='bookingtransfer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='packageextra',
            name='time',
        ),
        migrations.RemoveField(
            model_name='packagetransfer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quoteextra',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quotepackage',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quotepackageextra',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quotepackagetransfer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quotetransfer',
            name='time',
        ),
        migrations.RenameField(
            model_name='basebookingservice',
            old_name='time_new',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='packageservice',
            old_name='time_new',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='quotepackageservice',
            old_name='time_new',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='quoteservice',
            old_name='time_new',
            new_name='time',
        ),
    ]
