# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-10 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20191205_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'default_permissions': ('add', 'change'), 'permissions': (('change_amounts', 'Can change amounts of Booking'), ('change_services_amounts', 'Can select services to change amounts'), ('view_agency_payments', 'Can view agency payment details')), 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
