# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20190616_0752'),
        ('booking', '0019_merge_20190618_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
            ],
            options={
                'verbose_name': 'Package Provider',
                'verbose_name_plural': 'Packages Providers',
            },
        ),
        migrations.AlterField(
            model_name='bookingallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookingpackageallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='packageallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quoteallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quotepackageallotment',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='packageprovider',
            unique_together=set([('service', 'provider')]),
        ),
    ]
