# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20190205_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingextra',
            name='parameter',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingextra',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
