# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-20 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20190619_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Office'),
        ),
    ]
