# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_merge_20190619_1811'),
        ('booking', '0021_auto_20190619_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='invoice_format',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='invoice_office',
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='format',
            field=models.CharField(choices=[('C', 'Compact'), ('D', 'Detail')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Office'),
        ),
    ]
