# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-19 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20200105_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_qpl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price TPL'),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='cost_qdrple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost QPL'),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_cost_qdrple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='free_price_qdrple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepackageservicepaxvariant',
            name='price_qdrple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price QPL'),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='cost_qdrple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost QPL'),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='extra_qdrple_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Extra QPL'),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_cost_qdrple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='free_price_qdrple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='price_qdrple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price QPL'),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='cost_qdrple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost QPL'),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_cost_qdrple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='free_price_qdrple',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteservicepaxvariant',
            name='price_qdrple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price QPL'),
        ),
    ]
