# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20190205_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservicepax',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Cost'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='group',
            field=models.SmallIntegerField(verbose_name=b'Room'),
        ),
        migrations.AlterField(
            model_name='bookingservicepax',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Price'),
        ),
    ]
