# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20200119_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBooking',
            fields=[
            ],
            options={
                'verbose_name': 'Export Booking',
                'verbose_name_plural': 'Export Bookings',
                'permissions': (),
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
            },
            bases=('booking.booking',),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_qpl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price QUAD'),
        ),
    ]
