# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def update_base_service_data(apps, schema_editor):
    QuoteAllotment = apps.get_model('booking', 'QuoteAllotment')
    QuoteTransfer = apps.get_model('booking', 'QuoteTransfer')
    QuoteExtra = apps.get_model('booking', 'QuoteExtra')
    QuotePackage = apps.get_model('booking', 'QuotePackage')
    QuotePackageAllotment = apps.get_model('booking', 'QuotePackageAllotment')
    QuotePackageTransfer = apps.get_model('booking', 'QuotePackageTransfer')
    QuotePackageExtra = apps.get_model('booking', 'QuotePackageExtra')
    BookingAllotment = apps.get_model('booking', 'BookingAllotment')
    BookingTransfer = apps.get_model('booking', 'BookingTransfer')
    BookingExtra = apps.get_model('booking', 'BookingExtra')
    BookingPackage = apps.get_model('booking', 'BookingPackage')
    BookingPackageAllotment = apps.get_model('booking', 'BookingPackageAllotment')
    BookingPackageTransfer = apps.get_model('booking', 'BookingPackageTransfer')
    BookingPackageExtra = apps.get_model('booking', 'BookingPackageExtra')

    entity_models = [
        QuoteAllotment, QuoteTransfer, QuoteExtra, QuotePackage,
        QuotePackageAllotment, QuotePackageTransfer, QuotePackageExtra,
        BookingAllotment, BookingTransfer, BookingExtra, BookingPackage,
        BookingPackageAllotment, BookingPackageTransfer, BookingPackageExtra,
    ]
    for entity_model in entity_models:
        for reg in entity_model.objects.all():
            reg.base_service = reg.service
            reg.base_location = reg.service.location
            if not reg.base_location and hasattr(reg, 'location_from'):
                reg.base_location = reg.location_from
            reg.save()


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_auto_20200216_1330'),
    ]

    operations = [

        migrations.RunPython(update_base_service_data, backwards_function),

        migrations.AlterField(
            model_name='basebookingservice',
            name='base_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_base_service', to='config.Service'),
            preserve_default=False,
        ),
    ]
