# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_auto_20190215_1522'),
        ('booking', '0025_auto_20190215_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_to', to='config.Schedule'),
        ),
    ]
