# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20200217_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebookingservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='base_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_base_service', to='config.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='base_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackage_base_service', to='config.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='base_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_base_service', to='config.Service', verbose_name='Service'),
        ),
    ]
