# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20190215_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransfer',
            name='dropoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
