# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20200328_2020'),
        ('booking', '0026_auto_20200217_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingServiceBookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Detail', max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('datetime_from', models.DateField(blank=True, null=True, verbose_name='From')),
                ('datetime_to', models.DateField(blank=True, null=True, verbose_name='To')),
            ],
            options={
                'verbose_name': 'Booking Service Book Detail',
                'verbose_name_plural': 'Bookings Services Book Details',
            },
        ),
        migrations.CreateModel(
            name='QuoteServiceBookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Detail', max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('datetime_from', models.DateField(blank=True, null=True, verbose_name='From')),
                ('datetime_to', models.DateField(blank=True, null=True, verbose_name='To')),
            ],
            options={
                'verbose_name': 'Quote Service Book Detail',
                'verbose_name_plural': 'Quotes Services Bookk Details',
            },
        ),
        migrations.AlterModelOptions(
            name='basebookingservice',
            options={'ordering': ['provider', 'base_service__service_type'], 'verbose_name': 'Base Booking Service', 'verbose_name_plural': 'Base Bookings Services'},
        ),
        migrations.RemoveField(
            model_name='basebookingservice',
            name='service_location',
        ),
        migrations.RemoveField(
            model_name='basebookingservice',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='bookingextra',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='bookingpackageextra',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='packageextra',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='service_location',
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quoteextra',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='quotepackageextra',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='quotepackageservice',
            name='service_location',
        ),
        migrations.RemoveField(
            model_name='quotepackageservice',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='quoteservice',
            name='service_location',
        ),
        migrations.RemoveField(
            model_name='quoteservice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='packageservice',
            name='base_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packageservice_base_service', to='config.Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_pickup', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='schedule_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='schedule_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotepackagetransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_pickup', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='schedule_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='schedule_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotetransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basebookingservice_base_location', to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='base_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basebookingservice_base_service', to='config.Service'),
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='name',
            field=models.CharField(default='Detail', max_length=250),
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='service_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basebookingservice_service_addon', to='config.Addon', verbose_name='Addon'),
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('NS', 'No Show'), ('CN', 'Cancelled')], default='PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('NS', 'No Show'), ('CN', 'Cancelled')], default='PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='bookingallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingallotment_room_type', to='config.RoomType'),
        ),
        migrations.AlterField(
            model_name='bookingextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='bookingextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='bookingextra',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingextra_service', to='config.Extra'),
        ),
        migrations.AlterField(
            model_name='bookingpackageallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackageallotment_room_type', to='config.RoomType'),
        ),
        migrations.AlterField(
            model_name='bookingpackageextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackageextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='bookingpackageextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackageextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='bookingpackageextra',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackageextra_service', to='config.Extra'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_pickup', to='config.Allotment'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_place_from', to='config.Place'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_place_to', to='config.Place'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AlterField(
            model_name='bookingpackagetransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingpackagetransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_pickup', to='config.Allotment'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_place_from', to='config.Place'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_place_to', to='config.Place'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingtransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AlterField(
            model_name='packageallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageallotment_room_type', to='config.RoomType'),
        ),
        migrations.AlterField(
            model_name='packageextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='packageextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='packageextra',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageextra_service', to='config.Extra'),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageservice_base_location', to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='name',
            field=models.CharField(default='Detail', max_length=250),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='service_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageservice_service_addon', to='config.Addon', verbose_name='Addon'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_pickup', to='config.Allotment'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_place_from', to='config.Place'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_place_to', to='config.Place'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AlterField(
            model_name='packagetransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagetransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AlterField(
            model_name='quoteallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteallotment_room_type', to='config.RoomType'),
        ),
        migrations.AlterField(
            model_name='quoteextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='quoteextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='quoteextra',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteextra_service', to='config.Extra'),
        ),
        migrations.AlterField(
            model_name='quotepackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotepackage_service', to='booking.Package'),
        ),
        migrations.AlterField(
            model_name='quotepackageallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageallotment_room_type', to='config.RoomType'),
        ),
        migrations.AlterField(
            model_name='quotepackageextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='quotepackageextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AlterField(
            model_name='quotepackageextra',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageextra_service', to='config.Extra'),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageservice_base_location', to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='base_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageservice_base_service', to='config.Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='name',
            field=models.CharField(default='Detail', max_length=250),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='quote_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageservice_quote_package', to='booking.QuotePackage'),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='service_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotepackageservice_service_addon', to='config.Addon', verbose_name='Addon'),
        ),
        migrations.AlterField(
            model_name='quotepackageservice',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('RD', 'Ready')], default='DR', max_length=5),
        ),
        migrations.AlterField(
            model_name='quotepackagetransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='quotepackagetransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotepackagetransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservice_base_location', to='config.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='base_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservice_base_service', to='config.Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='name',
            field=models.CharField(default='Detail', max_length=250),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='service_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservice_service_addon', to='config.Addon', verbose_name='Addon'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('RD', 'Ready')], default='DR', max_length=5),
        ),
        migrations.AlterField(
            model_name='quotetransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='quotetransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotetransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.CreateModel(
            name='BookingServiceBookDetailAllotment',
            fields=[
                ('bookingservicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingServiceBookDetail')),
                ('board_type', models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailallotment_room_type', to='config.RoomType')),
            ],
            options={
                'verbose_name': 'Booking Service Book Detail Allotment',
                'verbose_name_plural': 'Bookings Services Book Details Allotments',
            },
            bases=('booking.bookingservicebookdetail', models.Model),
        ),
        migrations.CreateModel(
            name='BookingServiceBookDetailExtra',
            fields=[
                ('bookingservicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingServiceBookDetail')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
                ('pickup_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailextra_pickup_office', to='config.CarRentalOffice')),
                ('dropoff_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailextra_dropoff_office', to='config.CarRentalOffice')),
            ],
            options={
                'verbose_name': 'Booking Service Book Detail Extra',
                'verbose_name_plural': 'Bookings Services Book Details Extras',
            },
            bases=('booking.bookingservicebookdetail', models.Model),
        ),
        migrations.CreateModel(
            name='BookingServiceBookDetailTransfer',
            fields=[
                ('bookingservicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingServiceBookDetail')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('schedule_time_from', models.TimeField(blank=True, null=True)),
                ('schedule_time_to', models.TimeField(blank=True, null=True)),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
                ('dropoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_dropoff', to='config.Allotment')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_location_to', to='config.Location', verbose_name='Location to')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_pickup', to='config.Allotment')),
                ('place_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_place_from', to='config.Place')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_place_to', to='config.Place')),
                ('schedule_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_schedule_from', to='config.Schedule')),
                ('schedule_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetailtransfer_schedule_to', to='config.Schedule')),
            ],
            options={
                'verbose_name': 'Booking Service Book Detail Transfer',
                'verbose_name_plural': 'Bookings Services Book Details Transfers',
            },
            bases=('booking.bookingservicebookdetail', models.Model),
        ),
        migrations.CreateModel(
            name='QuoteServiceBookDetailAllotment',
            fields=[
                ('quoteservicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteServiceBookDetail')),
                ('board_type', models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailallotment_room_type', to='config.RoomType')),
            ],
            options={
                'verbose_name': 'Quote Service Book Detail Allotment',
                'verbose_name_plural': 'Quotes Services Book Details Allotments',
            },
            bases=('booking.quoteservicebookdetail', models.Model),
        ),
        migrations.CreateModel(
            name='QuoteServiceBookDetailExtra',
            fields=[
                ('quoteservicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteServiceBookDetail')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
                ('dropoff_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailextra_dropoff_office', to='config.CarRentalOffice')),
                ('pickup_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailextra_pickup_office', to='config.CarRentalOffice')),
            ],
            options={
                'verbose_name': 'Quote Service Book Detail Extra',
                'verbose_name_plural': 'Quotes Services Book Details Extras',
            },
            bases=('booking.quoteservicebookdetail', models.Model),
        ),
        migrations.CreateModel(
            name='QuoteServiceBookDetailTransfer',
            fields=[
                ('quoteservicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteServiceBookDetail')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('schedule_time_from', models.TimeField(blank=True, null=True)),
                ('schedule_time_to', models.TimeField(blank=True, null=True)),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
                ('dropoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_dropoff', to='config.Allotment')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_location_to', to='config.Location', verbose_name='Location to')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_pickup', to='config.Allotment')),
                ('place_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_place_from', to='config.Place')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_place_to', to='config.Place')),
                ('schedule_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_schedule_from', to='config.Schedule')),
                ('schedule_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetailtransfer_schedule_to', to='config.Schedule')),
            ],
            options={
                'verbose_name': 'Quote Service Book Detail Transfer',
                'verbose_name_plural': 'Quotes Services Book Details Transfers',
            },
            bases=('booking.quoteservicebookdetail', models.Model),
        ),
        migrations.AddField(
            model_name='quoteservicebookdetail',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetail_base_location', to='config.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='quoteservicebookdetail',
            name='base_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetail_base_service', to='config.Service'),
        ),
        migrations.AddField(
            model_name='quoteservicebookdetail',
            name='quote_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.QuoteService'),
        ),
        migrations.AddField(
            model_name='quoteservicebookdetail',
            name='service_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoteservicebookdetail_service_addon', to='config.Addon', verbose_name='Addon'),
        ),
        migrations.AddField(
            model_name='bookingservicebookdetail',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetail_base_location', to='config.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='bookingservicebookdetail',
            name='base_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetail_base_service', to='config.Service'),
        ),
        migrations.AddField(
            model_name='bookingservicebookdetail',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetail_booking_service', to='booking.BookingService'),
        ),
        migrations.AddField(
            model_name='bookingservicebookdetail',
            name='service_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingservicebookdetail_service_addon', to='config.Addon', verbose_name='Addon'),
        ),
    ]
