# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def update_base_service_data(apps, schema_editor):
    QuoteAllotment = apps.get_model('booking', 'QuoteAllotment')
    QuoteTransfer = apps.get_model('booking', 'QuoteTransfer')
    QuoteExtra = apps.get_model('booking', 'QuoteExtra')
    QuotePackage = apps.get_model('booking', 'QuotePackage')
    QuotePackageAllotment = apps.get_model('booking', 'QuotePackageAllotment')
    QuotePackageTransfer = apps.get_model('booking', 'QuotePackageTransfer')
    QuotePackageExtra = apps.get_model('booking', 'QuotePackageExtra')
    BookingAllotment = apps.get_model('booking', 'BookingAllotment')
    BookingTransfer = apps.get_model('booking', 'BookingTransfer')
    BookingExtra = apps.get_model('booking', 'BookingExtra')
    BookingPackage = apps.get_model('booking', 'BookingPackage')
    BookingPackageAllotment = apps.get_model('booking', 'BookingPackageAllotment')
    BookingPackageTransfer = apps.get_model('booking', 'BookingPackageTransfer')
    BookingPackageExtra = apps.get_model('booking', 'BookingPackageExtra')

    entity_models = [
        QuoteAllotment, QuoteTransfer, QuoteExtra, QuotePackage,
        QuotePackageAllotment, QuotePackageTransfer, QuotePackageExtra,
        BookingAllotment, BookingTransfer, BookingExtra, BookingPackage,
        BookingPackageAllotment, BookingPackageTransfer, BookingPackageExtra,
    ]
    for entity_model in entity_models:
        for reg in entity_model.objects.all():
            reg.base_service = reg.service
            reg.save()

    QuoteServiceBookDetailAllotment = apps.get_model('booking', 'QuoteServiceBookDetailAllotment')
    QuoteServiceBookDetailTransfer = apps.get_model('booking', 'QuoteServiceBookDetailTransfer')
    QuoteServiceBookDetailExtra = apps.get_model('booking', 'QuoteServiceBookDetailExtra')
    BookingServiceBookDetailAllotment = apps.get_model('booking', 'BookingServiceBookDetailAllotment')
    BookingServiceBookDetailTransfer = apps.get_model('booking', 'BookingServiceBookDetailTransfer')
    BookingServiceBookDetailExtra = apps.get_model('booking', 'BookingServiceBookDetailExtra')
    ServiceBookDetailAllotment = apps.get_model('config', 'ServiceBookDetailAllotment')
    ServiceBookDetailTransfer = apps.get_model('config', 'ServiceBookDetailTransfer')
    ServiceBookDetailExtra = apps.get_model('config', 'ServiceBookDetailExtra')

    entity_models = [
        QuoteServiceBookDetailAllotment, BookingServiceBookDetailAllotment,
        QuoteServiceBookDetailTransfer, BookingServiceBookDetailTransfer,
        QuoteServiceBookDetailExtra, BookingServiceBookDetailExtra,
        ServiceBookDetailAllotment, ServiceBookDetailTransfer, ServiceBookDetailExtra
    ]
    for entity_model in entity_models:
        for reg in entity_model.objects.all():
            reg.base_service = reg.book_service
            reg.save()

def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20200328_2216'),
    ]

    operations = [

        migrations.RunPython(update_base_service_data, backwards_function),

    ]
