# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20190215_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtransfer',
            name='dropoff_time',
        ),
        migrations.RemoveField(
            model_name='bookingtransfer',
            name='pickup_time',
        ),
    ]
