# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_bookinginvoicedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginvoice',
            old_name='format',
            new_name='content_format',
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='issued_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
