# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-05 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20200328_2020'),
        ('booking', '0028_custom_20200329_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basebookingservice',
            options={'ordering': ['provider', 'base_service__category'], 'verbose_name': 'Base Booking Service', 'verbose_name_plural': 'Base Bookings Services'},
        ),
    ]
