# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_transfer_operation_cost'),
        ('booking', '0028_auto_20190217_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInvoice',
            fields=[
                ('agencyinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AgencyInvoice')),
                ('booking_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=25, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking Invoice',
                'verbose_name_plural': 'Bookings Invoices',
            },
            bases=('finance.agencyinvoice',),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='agency_invoice',
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInvoice'),
        ),
    ]
