# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-02 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20190702_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginvoicepartial',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
