# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20190219_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('detail1', models.CharField(blank=True, max_length=100, null=True)),
                ('detail2', models.CharField(blank=True, max_length=100, null=True)),
                ('qtty', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInvoice')),
            ],
            options={
                'verbose_name': 'Booking Invoice Line',
                'verbose_name_plural': 'Bookings Invoices Lines',
            },
        ),
        migrations.CreateModel(
            name='BookingInvoicePartial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail1', models.CharField(blank=True, max_length=100, null=True)),
                ('detail2', models.CharField(blank=True, max_length=100, null=True)),
                ('partial_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInvoice')),
            ],
            options={
                'verbose_name': 'Booking Invoice Partial',
                'verbose_name_plural': 'Bookings Invoices Partials',
            },
        ),
    ]
