# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_bookinginvoiceline_bookinginvoicepartial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginvoiceline',
            old_name='detail1',
            new_name='bookingservice_name',
        ),
        migrations.RenameField(
            model_name='bookinginvoiceline',
            old_name='line_amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bookinginvoiceline',
            old_name='detail2',
            new_name='service_name',
        ),
    ]
