# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-03 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_bookinginvoice_cash_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotepaxvariant',
            name='extra_double_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Extra DBL'),
        ),
        migrations.AddField(
            model_name='quotepaxvariant',
            name='extra_single_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Extra SGL'),
        ),
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='price_triple_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Extra TPL'),
        ),
    ]
