# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 02:16
from __future__ import unicode_literals

from django.db import migrations


def migrate_new_data(apps, schema_editor):
    """
    Migrates quote services except quote_packages that has to be migrated with package
    """
    QuoteAllotment = apps.get_model('booking', 'QuoteAllotment')
    QuoteTransfer = apps.get_model('booking', 'QuoteTransfer')
    QuoteExtra = apps.get_model('booking', 'QuoteExtra')
    NewQuoteAllotment = apps.get_model('booking', 'NewQuoteAllotment')
    NewQuoteTransfer = apps.get_model('booking', 'NewQuoteTransfer')
    NewQuoteExtra = apps.get_model('booking', 'NewQuoteExtra')

    for service in QuoteAllotment.objects.all():
        new_service = NewQuoteAllotment()
        build_new_quote_allotment(new_service, service)
        new_service.save()

    for service in QuoteTransfer.objects.all():
        new_service = NewQuoteTransfer()
        build_new_quote_transfer(new_service, service)
        new_service.save()

    for service in QuoteExtra.objects.all():
        new_service = NewQuoteExtra()
        build_new_quote_extra(new_service, service)
        new_service.save()

def copy_quote_service(new_service, service):

    new_service.pk = service.pk
    new_service.base_service_id = service.base_service_id
    new_service.name = service.name
    new_service.description = service.description
    new_service.time = service.time
    new_service.datetime_from = service.datetime_from
    new_service.datetime_to = service.datetime_to
    new_service.status = service.status
    new_service.base_location_id = service.base_location_id
    new_service.service_addon_id = service.service_addon_id


def build_new_quote_allotment(new_service, service):

    copy_quote_service(new_service, service)
    new_service.quote_id = service.quote_id
    new_service.provider_id = service.provider_id

    new_service.service_id = service.service_id
    new_service.room_type_id = service.room_type_id
    new_service.board_type = service.board_type
    return new_service


def build_new_quote_transfer(new_service, service):

    copy_quote_service(new_service, service)
    new_service.quote_id = service.quote_id
    new_service.provider_id = service.provider_id

    new_service.service_id = service.service_id
    new_service.pickup_id = service.pickup_id
    new_service.dropoff_id = service.dropoff_id
    new_service.location_from_id = service.location_from_id
    new_service.location_to_id = service.location_to_id
    new_service.place_from_id = service.place_from_id
    new_service.place_to_id = service.place_to_id
    new_service.schedule_from_id = service.schedule_from_id
    new_service.schedule_to_id = service.schedule_to_id
    new_service.schedule_time_from = service.schedule_time_from
    new_service.schedule_time_to = service.schedule_time_to
    new_service.quantity = service.quantity
    return new_service


def build_new_quote_extra(new_service, service):

    copy_quote_service(new_service, service)
    new_service.quote_id = service.quote_id
    new_service.provider_id = service.provider_id

    new_service.service_id = service.service_id
    new_service.pickup_office_id = service.pickup_office_id
    new_service.dropoff_office_id = service.dropoff_office_id
    new_service.parameter = service.parameter
    new_service.quantity = service.quantity
    return new_service


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20200530_0818'),
        ('config', '0018_custom_20200530_0900'),
    ]

    operations = [

        migrations.RunPython(migrate_new_data, backwards_function),

    ]
