# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-03 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20190703_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotepaxvariant',
            name='extra_triple_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Extra TPL'),
        ),
        migrations.AlterField(
            model_name='quotepaxvariant',
            name='price_triple_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price TPL'),
        ),
    ]
