# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-20 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20200521_2140'),
        ('config', '0017_auto_20200521_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='newquotepackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquotepackage_service', to='config.NewPackage'),
        ),
        migrations.AddField(
            model_name='newbookingpackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package'),
        ),
        migrations.AddField(
            model_name='bookingprovidedservice',
            name='booking_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.NewBookingPackage'),
        ),
        migrations.AddField(
            model_name='bookingprovidedservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='bookingbookdetail',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetail_booking_service', to='booking.BookingProvidedService'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_pickup', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquotetransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='newquotetransfer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='book_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_pickup', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailtransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailtransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailextra',
            name='book_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailallotment',
            name='book_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='newquoteservicebookdetailallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetailallotment_room_type', to='config.RoomType'),
        ),
        migrations.AddField(
            model_name='newquoteextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='newquoteextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newquoteextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='newquoteextra',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquoteextra_service', to='config.Extra'),
        ),
        migrations.AddField(
            model_name='newquoteallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquoteallotment_room_type', to='config.RoomType'),
        ),
        migrations.AddField(
            model_name='newquoteallotment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='book_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_pickup', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailtransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailtransfer_schedule_to', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailextra',
            name='book_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailextra',
            name='dropoff_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailextra_dropoff_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailextra',
            name='pickup_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailextra_pickup_office', to='config.CarRentalOffice'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailallotment',
            name='book_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='bookingbookdetailallotment',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingbookdetailallotment_room_type', to='config.RoomType'),
        ),
    ]
