# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20190219_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginvoicepartial',
            old_name='detail1',
            new_name='pax_name',
        ),
    ]
