# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-16 15:48
from __future__ import unicode_literals

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_auto_20190703_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingallotment',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingpackageallotment',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingpackageextra',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingpackagetransfer',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingpax',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingservicepax',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='bookingtransfer',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='content_format',
            field=models.CharField(choices=[('C', 'Compact'), ('S', 'Services'), ('D', 'Details')], default='C', max_length=1),
        ),
    ]
