# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-24 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_auto_20190219_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotepaxvariant',
            name='price_percent',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Price %'),
        ),
    ]
