# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_auto_20190219_1026'),
        ('finance', '0013_auto_20190219_1436'),
        ('booking', '0033_quotepaxvariant_price_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.Service')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
            bases=('config.service',),
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Base Service', max_length=250)),
                ('days_after', models.SmallIntegerField(default=0, blank=True, null=True, verbose_name='Days after')),
                ('days_duration', models.SmallIntegerField(default=0, blank=True, null=True, verbose_name='Days duration')),
                ('service_type', models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Package Service',
                'verbose_name_plural': 'Packages Services',
            },
        ),
        migrations.CreateModel(
            name='QuotePackage',
            fields=[
                ('quoteservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuoteService')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
            ],
            options={
                'verbose_name': 'Quote Package',
                'verbose_name_plural': 'Quotes Packages',
            },
            bases=('booking.quoteservice',),
        ),
        migrations.CreateModel(
            name='QuotePackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Base Service', max_length=250)),
                ('service_type', models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('datetime_from', models.DateField(blank=True, null=True, verbose_name='Date From')),
                ('datetime_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Quote Package Service',
                'verbose_name_plural': 'Quotes Packages Services',
            },
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='name',
            field=models.CharField(default='Base Service', max_length=250),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='service_type',
            field=models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='bookingtransfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='name',
            field=models.CharField(default='Base Service', max_length=250),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='service_type',
            field=models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='PackageAllotment',
            fields=[
                ('packageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.PackageService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'verbose_name': 'Package Accomodation',
                'verbose_name_plural': 'Packages Accomodations',
            },
            bases=('booking.packageservice', models.Model),
        ),
        migrations.CreateModel(
            name='PackageExtra',
            fields=[
                ('packageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.PackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
            ],
            options={
                'verbose_name': 'Package Extra',
                'verbose_name_plural': 'Packages Extras',
            },
            bases=('booking.packageservice', models.Model),
        ),
        migrations.CreateModel(
            name='PackageTransfer',
            fields=[
                ('packageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.PackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_location_to', to='config.Location', verbose_name='Location to')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'verbose_name': 'Package Transfer',
                'verbose_name_plural': 'Packages Transfers',
            },
            bases=('booking.packageservice', models.Model),
        ),
        migrations.CreateModel(
            name='QuotePackageAllotment',
            fields=[
                ('quotepackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuotePackageService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'verbose_name': 'Quote Package Accomodation',
                'verbose_name_plural': 'Quotes Packages Accomodations',
            },
            bases=('booking.quotepackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='QuotePackageExtra',
            fields=[
                ('quotepackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuotePackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
            ],
            options={
                'verbose_name': 'Quote Extra',
                'verbose_name_plural': 'Quotes Extras',
            },
            bases=('booking.quotepackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='QuotePackageTransfer',
            fields=[
                ('quotepackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.QuotePackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_package_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_package_location_to', to='config.Location', verbose_name='Location to')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'verbose_name': 'Quote Package Transfer',
                'verbose_name_plural': 'Quotes Packages Transfers',
            },
            bases=('booking.quotepackageservice', models.Model),
        ),
        migrations.AddField(
            model_name='quotepackageservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='quotepackageservice',
            name='quote_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_package_services', to='booking.QuotePackage'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='booking.Package'),
        ),
        migrations.AddField(
            model_name='packageservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
    ]
