# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_auto_20200610_1646'),
        ('booking', '0034_custom_20200530_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteservice',
            name='base_category',
            field=models.CharField(blank=True, choices=[('QA', 'Quote Allotment'), ('QT', 'Quote Transfer'), ('QE', 'Quote Extra'), ('QP', 'Quote Package'), ('PA', 'Quote Package Allotment'), ('PT', 'Quote Package Transfer'), ('PE', 'Quote Package Extra'), ('DA', 'Quote Detail Allotment'), ('DT', 'Quote Detail Transfer'), ('DE', 'Quote Detail Extra')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='base_category',
            field=models.CharField(blank=True, choices=[('BA', 'Booking Allotment'), ('BT', 'Booking Transfer'), ('BE', 'Booking Extra'), ('BP', 'Booking Package'), ('PA', 'Booking Package Allotment'), ('PT', 'Booking Package Transfer'), ('PE', 'Booking Package Extra'), ('DA', 'Booking Detail Allotment'), ('DT', 'Booking Detail Transfer'), ('DE', 'Booking Detail Extra')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basebookingservicepax',
            name='booking_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='booking.BaseBookingService'),
        ),
        migrations.AlterField(
            model_name='newquoteservicebookdetail',
            name='quote_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newquoteservicebookdetail_provided', to='booking.QuoteProvidedService'),
        ),
    ]
