# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_auto_20190219_1026'),
        ('booking', '0034_auto_20190301_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetransfer',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_dropoff', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_pickup', to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_place_from', to='config.Place'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_place_to', to='config.Place'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='schedule_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_schedule_from', to='config.Schedule'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='schedule_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_schedule_to', to='config.Schedule'),
        ),
    ]
