# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_auto_20190717_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackagetransfer',
            name='schedule_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingpackagetransfer',
            name='schedule_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
