# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_auto_20190302_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_package_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_dbl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_sgl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_tpl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
