# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_new_data(apps, schema_editor):

    NewQuoteAllotment = apps.get_model('booking', 'NewQuoteAllotment')
    NewQuoteTransfer = apps.get_model('booking', 'NewQuoteTransfer')
    NewQuoteExtra = apps.get_model('booking', 'NewQuoteExtra')
    QuoteExtraPackage = apps.get_model('booking', 'QuoteExtraPackage')

    for service in NewQuoteAllotment.objects.all():
        if service.quote_package:
            service.base_category = "PA"
        else:
            service.base_category = "QA"
        service.save(force_update=True, update_fields=("base_category",))
    for service in NewQuoteTransfer.objects.all():
        if service.quote_package:
            service.base_category = "PT"
        else:
            service.base_category = "QT"
        service.save(force_update=True, update_fields=("base_category",))
    for service in NewQuoteExtra.objects.all():
        if service.quote_package:
            service.base_category = "PE"
        else:
            service.base_category = "QE"
        service.save(force_update=True, update_fields=("base_category",))
    for service in QuoteExtraPackage.objects.all():
        service.base_category = "QP"
        service.save(force_update=True, update_fields=("base_category",))


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_auto_20200610_1646'),
    ]

    operations = [

        migrations.RunPython(migrate_new_data, backwards_function),

    ]
