# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_auto_20200610_1646'),
        ('booking', '0036_custom_20200610_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basebookingservice',
            name='new_provider',
        ),
        migrations.RemoveField(
            model_name='quoteservice',
            name='new_provider',
        ),
        migrations.AlterField(
            model_name='basebookingservice',
            name='base_category',
            field=models.CharField(choices=[('BA', 'Booking Allotment'), ('BT', 'Booking Transfer'), ('BE', 'Booking Extra'), ('BP', 'Booking Package'), ('PA', 'Booking Package Allotment'), ('PT', 'Booking Package Transfer'), ('PE', 'Booking Package Extra'), ('DA', 'Booking Detail Allotment'), ('DT', 'Booking Detail Transfer'), ('DE', 'Booking Detail Extra')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='base_category',
            field=models.CharField(choices=[('QA', 'Quote Allotment'), ('QT', 'Quote Transfer'), ('QE', 'Quote Extra'), ('QP', 'Quote Package'), ('PA', 'Quote Package Allotment'), ('PT', 'Quote Package Transfer'), ('PE', 'Quote Package Extra'), ('DA', 'Quote Detail Allotment'), ('DT', 'Quote Detail Transfer'), ('DE', 'Quote Detail Extra')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
