# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_auto_20190309_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_package_price',
            field=models.BooleanField(default=False, verbose_name='Package Price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_dbl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price DBL'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_sgl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price SGL'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_tpl_price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price TPL'),
        ),
    ]
