# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-27 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_auto_20190805_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingallotment',
            options={'verbose_name': 'Booking Accomodation', 'verbose_name_plural': 'Bookings Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='bookingextra',
            options={'verbose_name': 'Booking Extra', 'verbose_name_plural': 'Booking Extras'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackage',
            options={'verbose_name': 'Booking Package', 'verbose_name_plural': 'Bookings Packages'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackageallotment',
            options={'verbose_name': 'Booking Package Accomodation', 'verbose_name_plural': 'Bookings Packages Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackageextra',
            options={'verbose_name': 'Booking Package Extra', 'verbose_name_plural': 'Bookings Packages Extras'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackageservice',
            options={'verbose_name': 'Booking Package Service', 'verbose_name_plural': 'Bookingss Packages Services'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackagetransfer',
            options={'verbose_name': 'Booking Package Transfer', 'verbose_name_plural': 'Bookingss Packages Transfers'},
        ),
        migrations.AlterModelOptions(
            name='bookingservice',
            options={'ordering': ['datetime_from'], 'verbose_name': 'Booking Service', 'verbose_name_plural': 'Booking Services'},
        ),
        migrations.AlterModelOptions(
            name='bookingtransfer',
            options={'verbose_name': 'Booking Transfer', 'verbose_name_plural': 'Booking Transfers'},
        ),
    ]
