# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 17:22
from __future__ import unicode_literals

from django.db import migrations


def migrate_PD_QuoteServices(apps, schema_editor):

    QuoteService = apps.get_model('booking', 'QuoteService')

    for quote_service in QuoteService.objects.filter(status__in=['PD', 'CN']):
        quote_service.status = 'DR'
        quote_service.save()


def backwards_function(apps, schema_editor):
    QuoteService = apps.get_model('booking', 'QuoteService')

    for quote_service in QuoteService.objects.filter(status='DR'):
        quote_service.status = 'PD'
        quote_service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_auto_20200612_1024'),
    ]

    operations = [
        migrations.RunPython(migrate_PD_QuoteServices, backwards_function),
    ]
