# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_booking_p_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='p_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'Private Notes'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='provider_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'Provider Notes'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='v_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'Voucher Notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'Private Notes'),
        ),
    ]
