# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_custom_20200905_0900'),
        ('booking', '0039_auto_20200904_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteextrapackage',
            name='price_by_catalog',
            field=models.BooleanField(default=False, verbose_name='Use Catalog Price'),
        ),
        migrations.AlterField(
            model_name='quoteprovidedservice',
            name='cost_by_catalog',
            field=models.BooleanField(default=False, verbose_name='Use Catalog Cost'),
        ),
        migrations.AlterField(
            model_name='quoteprovidedservice',
            name='price_by_catalog',
            field=models.BooleanField(default=False, verbose_name='Use Catalog Price'),
        ),

        migrations.DeleteModel(
            name='ProviderBookingPaymentService',
        ),
        migrations.DeleteModel(
            name='AgencyPackageDetail',
        ),
        migrations.DeleteModel(
            name='AgencyPackageService',
        ),

        migrations.DeleteModel(
            name='QuotePackageServicePaxVariant',
        ),
        migrations.DeleteModel(
            name='QuoteServiceBookDetailAllotment',
        ),
        migrations.DeleteModel(
            name='QuoteServiceBookDetailTransfer',
        ),
        migrations.DeleteModel(
            name='QuoteServiceBookDetailExtra',
        ),
        migrations.DeleteModel(
            name='QuoteServiceBookDetail',
        ),
        migrations.DeleteModel(
            name='QuotePackageAllotment',
        ),
        migrations.DeleteModel(
            name='QuotePackageTransfer',
        ),
        migrations.DeleteModel(
            name='QuotePackageExtra',
        ),
        migrations.DeleteModel(
            name='QuotePackageService',
        ),
        migrations.DeleteModel(
            name='QuoteAllotment',
        ),
        migrations.DeleteModel(
            name='QuoteTransfer',
        ),
        migrations.DeleteModel(
            name='QuoteExtra',
        ),
        migrations.DeleteModel(
            name='QuotePackage',
        ),

        migrations.DeleteModel(
            name='BookingServicePax',
        ),
        migrations.DeleteModel(
            name='BookingServiceBookDetailAllotment',
        ),
        migrations.DeleteModel(
            name='BookingServiceBookDetailTransfer',
        ),
        migrations.DeleteModel(
            name='BookingServiceBookDetailExtra',
        ),
        migrations.DeleteModel(
            name='BookingServiceBookDetail',
        ),
        migrations.DeleteModel(
            name='BookingPackageAllotment',
        ),
        migrations.DeleteModel(
            name='BookingPackageTransfer',
        ),
        migrations.DeleteModel(
            name='BookingPackageExtra',
        ),
        migrations.DeleteModel(
            name='BookingPackageService',
        ),
        migrations.DeleteModel(
            name='BookingAllotment',
        ),
        migrations.DeleteModel(
            name='BookingTransfer',
        ),
        migrations.DeleteModel(
            name='BookingExtra',
        ),
        migrations.DeleteModel(
            name='BookingPackage',
        ),
        migrations.DeleteModel(
            name='BookingService',
        ),

        migrations.DeleteModel(
            name='ProviderPackageService',
        ),
        migrations.DeleteModel(
            name='PackageProvider',
        ),
        migrations.DeleteModel(
            name='PackageAllotment',
        ),
        migrations.DeleteModel(
            name='PackageTransfer',
        ),
        migrations.DeleteModel(
            name='PackageExtra',
        ),
        migrations.DeleteModel(
            name='PackageService',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
