# Generated by Django 2.2.16 on 2020-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_auto_20200913_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebookingservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
