# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_service_infant_age'),
        ('finance', '0013_auto_20190219_1436'),
        ('booking', '0040_auto_20190322_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('bookingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingService')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
            ],
            options={
                'verbose_name': 'Booking Package',
                'verbose_name_plural': 'Bookings Packages',
            },
            bases=('booking.bookingservice',),
        ),
        migrations.CreateModel(
            name='BookingPackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateField(blank=True, null=True, verbose_name='Date From')),
                ('datetime_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('name', models.CharField(default='Base Service', max_length=250)),
                ('service_type', models.CharField(blank=True, choices=[('A', 'Allotment'), ('T', 'Transfer'), ('E', 'Extra'), ('P', 'Package')], max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('CN', 'Cancelled')], default='PD', max_length=5)),
            ],
            options={
                'verbose_name': 'Booking Package Service',
                'verbose_name_plural': 'Bookingss Packages Services',
            },
        ),
        migrations.CreateModel(
            name='BookingPackageAllotment',
            fields=[
                ('bookingpackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingPackageService')),
                ('board_type', models.CharField(choices=[('NB', 'None Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.RoomType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
            ],
            options={
                'verbose_name': 'Booking Package Accomodation',
                'verbose_name_plural': 'Bookings Packages Accomodations',
            },
            bases=('booking.bookingpackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='BookingPackageExtra',
            fields=[
                ('bookingpackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingPackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
            ],
            options={
                'verbose_name': 'Booking Extra',
                'verbose_name_plural': 'Bookings Extras',
            },
            bases=('booking.bookingpackageservice', models.Model),
        ),
        migrations.CreateModel(
            name='BookingPackageTransfer',
            fields=[
                ('bookingpackageservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BookingPackageService')),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('dropoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_transfer_dropoff', to='config.Allotment')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_location_to', to='config.Location', verbose_name='Location to')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_transfer_pickup', to='config.Allotment')),
                ('place_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_place_from', to='config.Place')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_place_to', to='config.Place')),
                ('schedule_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_schedule_from', to='config.Schedule')),
                ('schedule_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_schedule_to', to='config.Schedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
            ],
            options={
                'verbose_name': 'Booking Package Transfer',
                'verbose_name_plural': 'Bookingss Packages Transfers',
            },
            bases=('booking.bookingpackageservice', models.Model),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='booking_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package_services', to='booking.BookingPackage'),
        ),
        migrations.AddField(
            model_name='bookingpackageservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
    ]
