# Generated by Django 2.2.16 on 2021-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_auto_20201207_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='booked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
