# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_auto_20190322_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackageservice',
            name='conf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
