# Generated by Django 2.2.24 on 2023-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_auto_20210716_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebookingservice',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('PH', 'Phone Confirmed'), ('OH', 'On Hold'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('NS', 'No Show'), ('CR', 'Cancellation Requested'), ('CN', 'Cancelled')], default='PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RQ', 'Requested'), ('OH', 'On Hold'), ('OK', 'Confirmed'), ('CD', 'Coordinated'), ('NS', 'No Show'), ('CN', 'Cancelled')], default='PD', max_length=5),
        ),
    ]
