# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_bookingpackageservice_conf_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotepackageextra',
            options={'verbose_name': 'Quote Package Extra', 'verbose_name_plural': 'Quotes Packages Extras'},
        ),
    ]
