# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_auto_20190323_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingpackageextra',
            options={'verbose_name': 'Booking Package Extra', 'verbose_name_plural': 'Bookings Packages Extras'},
        ),
    ]
