# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20190402_0637'),
        ('booking', '0045_auto_20190327_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SGL')),
                ('ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DBL')),
                ('ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='TPL')),
                ('ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='QAD')),
                ('ch_1_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_2_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_3_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
            ],
            options={
                'verbose_name': 'Agency Package Detail',
                'verbose_name_plural': 'Agencies Package Details',
            },
        ),
        migrations.CreateModel(
            name='AgencyPackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Package')),
            ],
            options={
                'verbose_name': 'Agency Package Service',
                'verbose_name_plural': 'Agency Packages Services',
            },
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='priceByPackageCatalogue',
            field=models.BooleanField(default=False, verbose_name='By Catalogue'),
        ),
        migrations.AddField(
            model_name='quotepackage',
            name='priceByPackageCatalogue',
            field=models.BooleanField(default=False, verbose_name='By Catalogue'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], default='CUC', max_length=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], default='CUC', max_length=5),
        ),
        migrations.AddField(
            model_name='agencypackagedetail',
            name='agency_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.AgencyPackageService'),
        ),
        migrations.AlterUniqueTogether(
            name='agencypackageservice',
            unique_together=set([('agency', 'service', 'date_from', 'date_to')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencypackagedetail',
            unique_together=set([('agency_service',)]),
        ),
    ]
