# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_auto_20190402_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingpackage',
            old_name='priceByPackageCatalogue',
            new_name='price_by_package_catalogue',
        ),
        migrations.RenameField(
            model_name='quotepackage',
            old_name='priceByPackageCatalogue',
            new_name='price_by_package_catalogue',
        ),
    ]
