# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_auto_20190404_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amounts_type',
            field=models.CharField(choices=[('F', 'Fixed'), ('P', 'By Pax')], default='P', max_length=5),
        ),
        migrations.AddField(
            model_name='package',
            name='has_pax_range',
            field=models.BooleanField(default=False),
        ),
    ]
