# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_auto_20190404_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypackagedetail',
            name='pax_range_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencypackagedetail',
            name='pax_range_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
