# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-09 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_auto_20190405_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingallotment',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Accomodation', 'verbose_name_plural': 'Bookings Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='bookingextra',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Extra', 'verbose_name_plural': 'Bookings Extras'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackage',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Package', 'verbose_name_plural': 'Bookings Packages'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackageallotment',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Package Accomodation', 'verbose_name_plural': 'Bookings Packages Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackageextra',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Package Extra', 'verbose_name_plural': 'Bookings Packages Extras'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackageservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Package Service', 'verbose_name_plural': 'Bookingss Packages Services'},
        ),
        migrations.AlterModelOptions(
            name='bookingpackagetransfer',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Package Transfer', 'verbose_name_plural': 'Bookingss Packages Transfers'},
        ),
        migrations.AlterModelOptions(
            name='bookingtransfer',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Booking Transfer', 'verbose_name_plural': 'Bookings Transfers'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='quoteallotment',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Accomodation', 'verbose_name_plural': 'Quotes Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='quoteextra',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Extra', 'verbose_name_plural': 'Quotes Extras'},
        ),
        migrations.AlterModelOptions(
            name='quotepackage',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Package', 'verbose_name_plural': 'Quotes Packages'},
        ),
        migrations.AlterModelOptions(
            name='quotepackageallotment',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Package Accomodation', 'verbose_name_plural': 'Quotes Packages Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='quotepackageextra',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Package Extra', 'verbose_name_plural': 'Quotes Packages Extras'},
        ),
        migrations.AlterModelOptions(
            name='quotepackageservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Package Service', 'verbose_name_plural': 'Quotes Packages Services'},
        ),
        migrations.AlterModelOptions(
            name='quotepackagetransfer',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Package Transfer', 'verbose_name_plural': 'Quotes Packages Transfers'},
        ),
        migrations.AlterModelOptions(
            name='quoteservice',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Service', 'verbose_name_plural': 'Quote Services'},
        ),
        migrations.AlterModelOptions(
            name='quotetransfer',
            options={'default_permissions': ('add', 'change'), 'verbose_name': 'Quote Transfer', 'verbose_name_plural': 'Quotes Transfers'},
        ),
        migrations.AlterField(
            model_name='bookingpackage',
            name='price_by_package_catalogue',
            field=models.BooleanField(default=True, verbose_name='Use Catalogue Price'),
        ),
    ]
