# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[(b'CUC', b'cuc'), (b'USD', b'usd'), (b'EUR', b'eur')], max_length=5)),
                ('ammount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
