# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='ammount',
            new_name='balance',
        ),
    ]
