# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20170415_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='caja',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 15, 11, 51, 22, 140745)),
        ),
        migrations.AddField(
            model_name='caja',
            name='modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 15, 11, 51, 22, 140773)),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('DEPOSITED', 'Deposited'), ('WITHDRAWN', 'Withdrawn')], default='Withdrawn', max_length=30),
        ),
        migrations.AlterField(
            model_name='caja',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='current_balance'),
        ),
    ]
