
STATUS_DRAFT = 'D'
STATUS_READY = 'R'
STATUS_CANCELLED = 'C'
STATUSES = (
    (STATUS_DRAFT, 'Draft'),
    (STATUS_READY, 'Ready'),
    (STATUS_CANCELLED, 'Cancelled'),
)
OPERATION_CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE'
OPERATION_TRANSFER = 'TRANSFER'
OPERATION_LOAN = 'LOAN'
OPERATION_DEVOLUTION = 'DEVOLUTION'
OPERATION_INVOICE_EMITTED = 'INVOICE_EMITTED'
OPERATION_INVOICE_MODIFIED = 'INVOICE_MODIFIED'
OPERATION_INVOICE_CANCELLED = 'INVOICE_CANCELLED'
OPERATION_SERVICE_CONFIRMED = 'SERVICE_CONFIRMED'
OPERATION_SERVICE_MODIFIED = 'SERVICE_MODIFIED'
OPERATION_SERVICE_CANCELLED = 'SERVICE_CANCELLED'
OPERATION_INCOME = 'INCOME'
OPERATION_CONSUMPTION = 'CONSUMPTION'
OPERATIONS = (
    (OPERATION_CURRENCY_EXCHANGE, 'Currency Exchange'),
    (OPERATION_TRANSFER, 'Transfer'),
    (OPERATION_LOAN, 'Loan'),
    (OPERATION_DEVOLUTION, 'Devolution'),
    (OPERATION_INCOME, 'Income'),
    (OPERATION_CONSUMPTION, 'Consumption'),
    (OPERATION_INVOICE_EMITTED, 'Currency Conversion'),
    (OPERATION_INVOICE_MODIFIED, 'Transfer'),
    (OPERATION_INVOICE_CANCELLED, 'Loan'),
    (OPERATION_SERVICE_CONFIRMED, 'Devolution'),
    (OPERATION_SERVICE_MODIFIED, 'Income'),
    (OPERATION_SERVICE_CANCELLED, 'Consumption'),
)
MANUAL_OPERATIONS = (
    (OPERATION_CURRENCY_EXCHANGE, 'Currency Exchange'),
    (OPERATION_TRANSFER, 'Transfer'),
    (OPERATION_LOAN, 'Loan'),
    (OPERATION_DEVOLUTION, 'Devolution'),
    (OPERATION_INCOME, 'Income'),
    (OPERATION_CONSUMPTION, 'Consumption'),
)
