
STATUS_DRAFT = 'D'
STATUS_READY = 'R'
STATUS_CANCELLED = 'C'
STATUS_DICT = {
    STATUS_DRAFT : 'Draft',
    STATUS_READY : 'Ready',
    STATUS_CANCELLED : 'Cancelled',
}
STATUSES = (
    (STATUS_DRAFT, STATUS_DICT[STATUS_DRAFT]),
    (STATUS_READY, STATUS_DICT[STATUS_READY]),
    (STATUS_CANCELLED, STATUS_DICT[STATUS_CANCELLED]),
)
OPERATION_CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE'
OPERATION_TRANSFER = 'TRANSFER'
OPERATION_LOAN = 'LOAN'
OPERATION_LOAN_DEVOLUTION = 'LOAN_DEVOLUTION'
OPERATION_LOAN_ACCOUNT = 'LOAN_ACCOUNT'
OPERATION_LOAN_ACCOUNT_DEVOLUTION = 'LOAN_ACCOUNT_DEVOLUTION'
OPERATION_INCOME = 'INCOME'
OPERATION_SPEND = 'SPEND'
OPERATION_AGENCY_INVOICE = 'AGENCY_INVOICE'
OPERATION_PROVIDER_INVOICE = 'PROVIDER_INVOICE'
OPERATION_DICT = {
    OPERATION_CURRENCY_EXCHANGE : 'Currency Exchange',
    OPERATION_TRANSFER : 'Transfer',
    OPERATION_LOAN : 'Loan',
    OPERATION_LOAN_DEVOLUTION : 'Loan Devolution',
    OPERATION_LOAN_ACCOUNT : 'Loan Account',
    OPERATION_LOAN_ACCOUNT_DEVOLUTION : 'Loan Account Devolution',
    OPERATION_INCOME : 'Income',
    OPERATION_SPEND : 'Spend',
    OPERATION_AGENCY_INVOICE : 'Agency Invoice',
    OPERATION_PROVIDER_INVOICE : 'Provider Invoice',
}
OPERATIONS = (
    (OPERATION_CURRENCY_EXCHANGE, OPERATION_DICT[OPERATION_CURRENCY_EXCHANGE]),
    (OPERATION_TRANSFER, OPERATION_DICT[OPERATION_TRANSFER]),
    (OPERATION_LOAN, OPERATION_DICT[OPERATION_LOAN]),
    (OPERATION_LOAN_DEVOLUTION, OPERATION_DICT[OPERATION_LOAN_DEVOLUTION]),
    (OPERATION_LOAN_ACCOUNT, OPERATION_DICT[OPERATION_LOAN_ACCOUNT]),
    (OPERATION_LOAN_ACCOUNT_DEVOLUTION, OPERATION_DICT[OPERATION_LOAN_ACCOUNT_DEVOLUTION]),
    (OPERATION_INCOME, OPERATION_DICT[OPERATION_INCOME]),
    (OPERATION_SPEND, OPERATION_DICT[OPERATION_SPEND]),
    (OPERATION_AGENCY_INVOICE, OPERATION_DICT[OPERATION_AGENCY_INVOICE]),
    (OPERATION_PROVIDER_INVOICE, OPERATION_DICT[OPERATION_PROVIDER_INVOICE]),
)
