# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPriceCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
            ],
            options={
                'verbose_name': 'Agency Price Catalogue',
                'verbose_name_plural': 'Agencies Prices Catalogues',
            },
        ),
        migrations.CreateModel(
            name='AllotmentBoardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[(b'NB', b'None Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5)),
            ],
            options={
                'verbose_name': 'Allotment Board Type',
                'verbose_name_plural': 'Alloments Boards Types',
            },
        ),
        migrations.CreateModel(
            name='AllotmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Allotment Cost',
                'verbose_name_plural': 'Allotments Costs',
            },
        ),
        migrations.CreateModel(
            name='AllotmentCostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentBoardType')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentCost')),
            ],
            options={
                'verbose_name': 'Allotment Cost Detail',
                'verbose_name_plural': 'Allotments Costs Details',
            },
        ),
        migrations.CreateModel(
            name='AllotmentCostDetailPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pax_2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pax_3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Allotment Cost Detail Price',
                'verbose_name_plural': 'Allotments Costs Details Prices',
            },
        ),
        migrations.CreateModel(
            name='AllotmentRoomAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.SmallIntegerField(default=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Allotment Availability',
                'verbose_name_plural': 'Allotments Availabilities',
            },
        ),
        migrations.CreateModel(
            name='AllotmentRoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Allotment Room Type',
                'verbose_name_plural': 'Allotments Rooms Types',
            },
        ),
        migrations.CreateModel(
            name='AllotmentSupplementCostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_type', models.CharField(choices=[(b'F', b'Fixed'), (b'P', b'By Pax'), (b'D', b'By Day'), (b'PD', b'By Pax Day')], max_length=10)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentCost')),
            ],
            options={
                'verbose_name': 'Allotment Supplement Cost Detail',
                'verbose_name_plural': 'Allotments Supplements Costs Details',
            },
        ),
        migrations.CreateModel(
            name='AllotmentSupplementCostDetailPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Allotment Supplement Cost Detail Price',
                'verbose_name_plural': 'Allotments Supplements Costs Details Prices',
            },
        ),
        migrations.CreateModel(
            name='ExtraCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Extra Cost',
                'verbose_name_plural': 'Extras Costs',
            },
        ),
        migrations.CreateModel(
            name='ExtraCostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ExtraCost')),
            ],
            options={
                'verbose_name': 'Extra Cost Detail',
                'verbose_name_plural': 'Extras Costs Details',
            },
        ),
        migrations.CreateModel(
            name='ExtraCostDetailPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pax_2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pax_3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Extra Cost Detail Price',
                'verbose_name_plural': 'Extras Costs Details Prices',
            },
        ),
        migrations.CreateModel(
            name='ExtraSupplementCostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ExtraCost')),
            ],
            options={
                'verbose_name': 'Extra Supplement Cost Detail',
                'verbose_name_plural': 'Extras Supplement Costs Details',
            },
        ),
        migrations.CreateModel(
            name='ExtraSupplementCostDetailPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Extra Supplement Cost Detail Price',
                'verbose_name_plural': 'Extras Supplements Costs Details Prices',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='PriceCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Price Catalogue',
                'verbose_name_plural': 'Prices Catalogues',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[(b'E', b'Extra'), (b'A', b'Allotment'), (b'T', b'Transfer')], max_length=5)),
                ('grouping', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Services Providers',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue')),
            ],
            options={
                'verbose_name': 'Price Catalogue',
                'verbose_name_plural': 'Prices Catalogues',
            },
        ),
        migrations.CreateModel(
            name='ServiceSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('automatic', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Supplement',
                'verbose_name_plural': 'Services Supplements',
            },
        ),
        migrations.CreateModel(
            name='TransferCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Transfer Cost',
                'verbose_name_plural': 'Transfers Costs',
            },
        ),
        migrations.CreateModel(
            name='TransferCostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_1_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_2_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_3_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.TransferCost')),
            ],
            options={
                'verbose_name': 'Transfer Cost Detail',
                'verbose_name_plural': 'Transfers Costs Details',
            },
        ),
        migrations.CreateModel(
            name='TransferCostDetailPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pax_2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pax_3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue')),
                ('cost_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.TransferCostDetail')),
            ],
            options={
                'verbose_name': 'Transfer Cost Detail Price',
                'verbose_name_plural': 'Transfer Costs Details Prices',
            },
        ),
        migrations.CreateModel(
            name='TransferSupplementCostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ch_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_type', models.CharField(choices=[(b'F', b'Fixed'), (b'H', b'By Hours')], max_length=10)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.TransferCost')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceSupplement')),
            ],
            options={
                'verbose_name': 'Transfer Supplement',
                'verbose_name_plural': 'Transfers Supplements',
            },
        ),
        migrations.CreateModel(
            name='TransferSupplementCostDetailPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue')),
                ('supplement_cost_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.TransferSupplementCostDetail')),
            ],
            options={
                'verbose_name': 'Transfer Supplement Cost Detail Price',
                'verbose_name_plural': 'Transfers Supplements Costs Details Prices',
            },
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.Service')),
                ('time_from', models.TimeField(default=b'16:00')),
                ('time_to', models.TimeField(default=b'12:00')),
            ],
            options={
                'verbose_name': 'Allotment',
                'verbose_name_plural': 'Allotments',
            },
            bases=('config.service',),
        ),
        migrations.CreateModel(
            name='AllotmentServiceProvider',
            fields=[
                ('serviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceProvider')),
                ('cost_type', models.CharField(choices=[(b'F', b'Fixed'), (b'P', b'By Pax')], max_length=5)),
            ],
            options={
                'verbose_name': 'Allotment Service Provider',
                'verbose_name_plural': 'Allotments Services Providers',
            },
            bases=('config.serviceprovider',),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.Service')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
            },
            bases=('config.service',),
        ),
        migrations.CreateModel(
            name='ExtraServiceProvider',
            fields=[
                ('serviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceProvider')),
                ('cost_type', models.CharField(choices=[(b'P', b'By Pax'), (b'E', b'By Extra'), (b'PE', b'By Pax Extra')], max_length=5)),
            ],
            options={
                'verbose_name': 'Extra Service Provider',
                'verbose_name_plural': 'Extras Services Providers',
            },
            bases=('config.serviceprovider',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.Service')),
            ],
            bases=('config.service',),
        ),
        migrations.CreateModel(
            name='TransferServiceProvider',
            fields=[
                ('serviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceProvider')),
                ('cost_type', models.CharField(choices=[(b'F', b'Fixed'), (b'P', b'By Pax')], max_length=5)),
            ],
            options={
                'verbose_name': 'Transfer Service Provider',
                'verbose_name_plural': 'Transfers Services Providers',
            },
            bases=('config.serviceprovider',),
        ),
        migrations.AddField(
            model_name='transfercost',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='servicesupplement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Service'),
        ),
        migrations.AddField(
            model_name='serviceproviderprice',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('category', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='pricecatalogue',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='extrasupplementcostdetailprice',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue'),
        ),
        migrations.AddField(
            model_name='extrasupplementcostdetailprice',
            name='supplement_cost_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ExtraSupplementCostDetail'),
        ),
        migrations.AddField(
            model_name='extrasupplementcostdetail',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceSupplement'),
        ),
        migrations.AddField(
            model_name='extracostdetailprice',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue'),
        ),
        migrations.AddField(
            model_name='extracostdetailprice',
            name='cost_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ExtraCostDetail'),
        ),
        migrations.AddField(
            model_name='extracost',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='allotmentsupplementcostdetailprice',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue'),
        ),
        migrations.AddField(
            model_name='allotmentsupplementcostdetailprice',
            name='supplement_cost_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentSupplementCostDetail'),
        ),
        migrations.AddField(
            model_name='allotmentsupplementcostdetail',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceSupplement'),
        ),
        migrations.AddField(
            model_name='allotmentroomavailability',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentRoomType'),
        ),
        migrations.AddField(
            model_name='allotmentcostdetailprice',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue'),
        ),
        migrations.AddField(
            model_name='allotmentcostdetailprice',
            name='cost_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentCostDetail'),
        ),
        migrations.AddField(
            model_name='allotmentcostdetail',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AllotmentRoomType'),
        ),
        migrations.AddField(
            model_name='allotmentcost',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='agencypricecatalogue',
            name='price_catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.PriceCatalogue'),
        ),
        migrations.AlterUniqueTogether(
            name='transfersupplementcostdetail',
            unique_together=set([('cost', 'supplement')]),
        ),
        migrations.AlterUniqueTogether(
            name='transfercostdetailprice',
            unique_together=set([('catalogue', 'cost_detail')]),
        ),
        migrations.AlterUniqueTogether(
            name='transfercostdetail',
            unique_together=set([('cost',)]),
        ),
        migrations.AddField(
            model_name='transfer',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='config.Location'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='config.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='servicesupplement',
            unique_together=set([('service', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='serviceproviderprice',
            unique_together=set([('catalogue', 'service_provider')]),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprovider',
            unique_together=set([('service', 'provider')]),
        ),
        migrations.AlterUniqueTogether(
            name='extrasupplementcostdetail',
            unique_together=set([('cost', 'supplement')]),
        ),
        migrations.AlterUniqueTogether(
            name='extracostdetailprice',
            unique_together=set([('catalogue', 'cost_detail')]),
        ),
        migrations.AlterUniqueTogether(
            name='extracostdetail',
            unique_together=set([('cost',)]),
        ),
        migrations.AlterUniqueTogether(
            name='allotmentsupplementcostdetail',
            unique_together=set([('cost', 'supplement')]),
        ),
        migrations.AddField(
            model_name='allotmentroomtype',
            name='allotment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment'),
        ),
        migrations.AlterUniqueTogether(
            name='allotmentcostdetailprice',
            unique_together=set([('catalogue', 'cost_detail')]),
        ),
        migrations.AlterUniqueTogether(
            name='allotmentcostdetail',
            unique_together=set([('cost', 'room_type', 'board_type')]),
        ),
        migrations.AddField(
            model_name='allotmentboardtype',
            name='allotment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='agencypricecatalogue',
            unique_together=set([('agency',)]),
        ),
        migrations.AlterUniqueTogether(
            name='allotmentroomtype',
            unique_together=set([('allotment', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='allotmentboardtype',
            unique_together=set([('allotment', 'board_type')]),
        ),
    ]
