# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-07 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotmentroomtype',
            name='enabled',
        ),
    ]
