# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='cost_type',
            field=models.CharField(choices=[('F', 'Fixed'), ('P', 'By Pax')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='cost_type',
            field=models.CharField(choices=[('F', 'Fixed'), ('P', 'By Pax')], max_length=5),
        ),
    ]
