# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
