# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='location_from',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='location_to',
        ),
    ]
