# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-06 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180827_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentroomtype',
            name='room_type',
            field=models.CharField(choices=[('SNGL', 'Single'), ('DBL', 'Double'), ('TRPL', 'Triple'), ('QDRPL', 'Quadruple'), ('MLTPL', 'Multiple')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
