# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-25 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20191025_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuptime',
            options={'verbose_name': 'Pickup Time', 'verbose_name_plural': 'Pickups Times'},
        ),
    ]
