# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20181019_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'SGL'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'DBL'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'TPL'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'QAD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_1_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_1_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_1_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_1_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_1_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_2_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_2_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_2_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_2_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_2_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_3_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_3_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_3_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_3_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='ch_3_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'SGL'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'DBL'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'TPL'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'QAD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_1_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_1_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_1_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_1_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_1_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_2_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_2_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_2_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_2_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_2_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_3_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_3_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_3_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_3_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='ch_3_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='a_location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_location_from', to='config.Location', verbose_name=b'Location from'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='a_location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_location_to', to='config.Location', verbose_name=b'Location to'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'SGL'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'DBL'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'TPL'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'QAD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_1_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_1_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_1_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_1_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_1_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_2_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_2_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_2_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_2_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_2_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_3_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_3_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_3_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_3_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='ch_3_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'SGL'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'DBL'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'TPL'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'QAD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_1_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_1_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_1_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_1_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_1_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_2_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_2_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_2_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_2_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_2_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_3_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_3_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_3_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_3_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='ch_3_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'SGL'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'DBL'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'TPL'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'QAD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_1_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_1_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_1_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_1_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_1_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_2_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_2_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_2_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_2_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_2_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_3_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_3_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_3_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_3_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='ch_3_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'SGL'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'DBL'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'TPL'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'QAD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_1_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_1_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_1_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_1_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_1_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'1st CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_2_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_2_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_2_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_2_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_2_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'2nd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_3_ad_0_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_3_ad_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_3_ad_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_3_ad_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='ch_3_ad_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'3rd CHD'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='p_location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_location_from', to='config.Location', verbose_name=b'Location from'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='p_location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_location_to', to='config.Location', verbose_name=b'Location to'),
        ),
    ]
