# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-06 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_allotmentroomtype_room_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allotmentroomtype',
            unique_together=set([('allotment', 'name', 'room_type')]),
        ),
    ]
