# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20191028_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allotment',
            old_name='location',
            new_name='location_a',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='location',
            new_name='location_e',
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Location'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='location_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_a', to='config.Location'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='location_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_e', to='config.Location'),
        ),
    ]
