# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20190503_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='allotmentboardtype',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='board_type',
            field=models.CharField(choices=[(b'NB', b'No Board'), (b'BB', b'Breakfast Board'), (b'HB', b'Half Board'), (b'FB', b'Full Board'), (b'AI', b'All Included')], max_length=5),
        ),
    ]
