# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20180906_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotmentSupplement',
            fields=[
                ('servicesupplement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceSupplement')),
            ],
            options={
                'verbose_name': 'Allotment Supplement',
                'verbose_name_plural': 'Allotments Supplements',
            },
            bases=('config.servicesupplement',),
        ),
    ]
