# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 21:03
from __future__ import unicode_literals

from django.db import migrations


def update_service_data(apps, schema_editor):
    Allotment = apps.get_model('config', 'Allotment')
    Extra = apps.get_model('config', 'Extra')

    for allotment in Allotment.objects.all():
        allotment.location = allotment.location_a
        allotment.save(update_fields=['location'])
    for extra in Extra.objects.all():
        extra.location = extra.location_e
        extra.save(update_fields=['location'])

def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20191028_1934'),
    ]

    operations = [

        migrations.RunPython(update_service_data, backwards_function),

    ]
