# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-18 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20190614_1410'),
        ('config', '0005_auto_20190616_0752'),
    ]

    operations = [
    ]
