# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_allotmentsupplement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSupplement',
            fields=[
                ('servicesupplement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceSupplement')),
            ],
            options={
                'verbose_name': 'Extra Supplement',
                'verbose_name_plural': 'Extras Supplements',
            },
            bases=('config.servicesupplement',),
        ),
        migrations.CreateModel(
            name='TransferSupplement',
            fields=[
                ('servicesupplement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceSupplement')),
            ],
            options={
                'verbose_name': 'Transfer Supplement',
                'verbose_name_plural': 'Transfers Supplements',
            },
            bases=('config.servicesupplement',),
        ),
    ]
