# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-28 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20191028_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotment',
            name='location_a',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='location_e',
        ),
    ]
