# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20181114_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='allotment',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
