# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_merge_20190618_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='allotmentboardtype',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='board_type',
            field=models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5),
        ),
    ]
