# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20190619_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Service')),
            ],
            options={
                'verbose_name': 'Service Addon',
                'verbose_name_plural': 'Services Addons',
            },
        ),
        migrations.AddField(
            model_name='agencyallotmentdetail',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AddField(
            model_name='agencytransferdetail',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AddField(
            model_name='providerallotmentdetail',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AddField(
            model_name='providertransferdetail',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyallotmentdetail',
            unique_together=set([('agency_service', 'room_type', 'board_type', 'addon')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencytransferdetail',
            unique_together=set([('agency_service', 'a_location_from', 'a_location_to', 'addon')]),
        ),
        migrations.AlterUniqueTogether(
            name='providerallotmentdetail',
            unique_together=set([('provider_service', 'room_type', 'board_type', 'addon')]),
        ),
        migrations.AlterUniqueTogether(
            name='providertransferdetail',
            unique_together=set([('provider_service', 'p_location_from', 'p_location_to', 'addon')]),
        ),
        migrations.AlterUniqueTogether(
            name='serviceaddon',
            unique_together=set([('service', 'addon')]),
        ),
    ]
