# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20191028_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
