# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20181120_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyextradetail',
            name='pax_range_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyextradetail',
            name='pax_range_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='has_pax_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerextradetail',
            name='pax_range_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerextradetail',
            name='pax_range_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
