# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20181213_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyextradetail',
            options={'verbose_name': 'Agency Extra Detail', 'verbose_name_plural': 'Agencies Extra Details'},
        ),
    ]
