# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20190624_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyallotmentdetail',
            name='pax_range_max',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agencyallotmentdetail',
            name='pax_range_min',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agencytransferdetail',
            name='pax_range_max',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agencytransferdetail',
            name='pax_range_min',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerallotmentdetail',
            name='pax_range_max',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerallotmentdetail',
            name='pax_range_min',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providertransferdetail',
            name='pax_range_max',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providertransferdetail',
            name='pax_range_min',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='pax_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='agencyallotmentdetail',
            unique_together=set([('agency_service', 'room_type', 'board_type', 'addon', 'pax_range_min', 'pax_range_max')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencytransferdetail',
            unique_together=set([('agency_service', 'a_location_from', 'a_location_to', 'addon', 'pax_range_min', 'pax_range_max')]),
        ),
        migrations.AlterUniqueTogether(
            name='providerallotmentdetail',
            unique_together=set([('provider_service', 'room_type', 'board_type', 'addon', 'pax_range_min', 'pax_range_max')]),
        ),
        migrations.AlterUniqueTogether(
            name='providertransferdetail',
            unique_together=set([('provider_service', 'p_location_from', 'p_location_to', 'addon', 'pax_range_min', 'pax_range_max')]),
        ),
    ]
