# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20191114_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Car Rental',
                'verbose_name_plural': 'Cars Rentals',
            },
        ),
        migrations.CreateModel(
            name='CarRentalOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=30)),
                ('car_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.CarRental')),
            ],
            options={
                'verbose_name': 'Car Rental Office',
                'verbose_name_plural': 'Cars Rentals Offices',
            },
        ),
        migrations.AlterUniqueTogether(
            name='carrental',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='extra',
            name='car_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.CarRental'),
        ),
        migrations.AlterUniqueTogether(
            name='carrentaloffice',
            unique_together=set([('car_rental', 'office')]),
        ),
    ]
