# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-27 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20190625_2303'),
        ('config', '0009_auto_20190625_1144'),
    ]

    operations = [
    ]
