# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20190625_1144'),
        ('config', '0009_auto_20190625_2303'),
    ]

    operations = [
    ]
