# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20190201_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agencyextradetail',
            unique_together=set([('agency_service', 'pax_range_min', 'pax_range_max')]),
        ),
    ]
