# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_transfer_is_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentaloffice',
            name='office',
            field=models.CharField(max_length=60),
        ),
    ]
