# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-28 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20190626_2324'),
        ('config', '0010_merge_20190626_2228'),
    ]

    operations = [
    ]
