# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-09 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_service_child_discount_percent'),
        ('config', '0011_auto_20200106_1118'),
    ]

    operations = [
    ]
