# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20190201_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Location'),
            preserve_default=False,
        ),
    ]
