# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_extra_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
            },
        ),
        migrations.CreateModel(
            name='ExtraAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Addon')),
            ],
            options={
                'verbose_name': 'Extra Addon',
                'verbose_name_plural': 'Extras Addons',
            },
        ),
        migrations.AlterField(
            model_name='extra',
            name='parameter_type',
            field=models.CharField(choices=[('H', 'Hours'), ('D', 'Days'), ('N', 'Nights'), ('S', 'Stay')], max_length=5),
        ),
        migrations.AddField(
            model_name='extraaddon',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra'),
        ),
        migrations.AlterUniqueTogether(
            name='addon',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='extraaddon',
            unique_together=set([('extra', 'addon')]),
        ),
    ]
