# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_merge_20200109_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='config.Extra')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='config.Extra')),
            ],
            options={
                'verbose_name': 'Extra Component',
                'verbose_name_plural': 'Extras Components',
            },
        ),
        migrations.AlterUniqueTogether(
            name='extracomponent',
            unique_together=set([('extra', 'component')]),
        ),
    ]
