# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20190205_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyextradetail',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AddField(
            model_name='providerextradetail',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
    ]
