# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20190720_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('E', 'Extra'), ('A', 'Allotment'), ('T', 'Transfer'), ('P', 'Package')], max_length=5),
        ),
    ]
