# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20190205_1410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agencyextradetail',
            unique_together=set([('agency_service', 'addon', 'pax_range_min', 'pax_range_max')]),
        ),
        migrations.AlterUniqueTogether(
            name='providerextradetail',
            unique_together=set([('provider_service', 'addon', 'pax_range_min', 'pax_range_max')]),
        ),
    ]
