# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20190722_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerallotmentdetail',
            name='single_supplement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerallotmentdetail',
            name='third_pax_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
