# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-09 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20200309_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providertransferdetail',
            old_name='p_location_from',
            new_name='location_from',
        ),
        migrations.RenameField(
            model_name='providertransferdetail',
            old_name='p_location_to',
            new_name='location_to',
        ),
        migrations.RenameField(
            model_name='agencytransferdetail',
            old_name='a_location_from',
            new_name='location_from',
        ),
        migrations.RenameField(
            model_name='agencytransferdetail',
            old_name='a_location_to',
            new_name='location_to',
        ),
    ]
