# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20190802_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='single_supplement',
            field=models.IntegerField(blank=True, null=True, verbose_name='SGL Suppl.'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='third_pax_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='TPL Dscnt %'),
        ),
    ]
