# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_custom_20200327_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencytransferdetail_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencytransferdetail_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providertransferdetail_location_from', to='config.Location', verbose_name='Location from'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providertransferdetail_location_to', to='config.Location', verbose_name='Location to'),
        ),
        migrations.DeleteModel(
            name='ExtraAddon',
        ),
        migrations.DeleteModel(
            name='ServiceDetailAllotment',
        ),
        migrations.DeleteModel(
            name='ServiceDetailExtra',
        ),
        migrations.DeleteModel(
            name='ServiceDetailTransfer',
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
        migrations.CreateModel(
            name='ServiceBookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_after', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Days after')),
                ('days_duration', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Days duration')),
                ('name', models.CharField(default='Detail', max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service Detail',
                'verbose_name_plural': 'Services Details',
            },
        ),
        migrations.CreateModel(
            name='ServiceBookDetailAllotment',
            fields=[
                ('servicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceBookDetail')),
                ('board_type', models.CharField(choices=[('NB', 'No Board'), ('BB', 'Breakfast Board'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Included')], max_length=5)),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Allotment')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailallotment_room_type', to='config.RoomType')),
            ],
            options={
                'verbose_name': 'Service Book Detail Accomodation',
                'verbose_name_plural': 'Services Book Details Accomodations',
            },
            bases=('config.servicebookdetail', models.Model),
        ),
        migrations.CreateModel(
            name='ServiceBookDetailExtra',
            fields=[
                ('servicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceBookDetail')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('parameter', models.SmallIntegerField(default=0, verbose_name='Hours')),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Extra')),
                ('dropoff_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailextra_dropoff_office', to='config.CarRentalOffice')),
                ('pickup_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailextra_pickup_office', to='config.CarRentalOffice')),
            ],
            options={
                'verbose_name': 'Service Book Detail Extra',
                'verbose_name_plural': 'Services Book Details Extras',
            },
            bases=('config.servicebookdetail', models.Model),
        ),
        migrations.CreateModel(
            name='ServiceBookDetailTransfer',
            fields=[
                ('servicebookdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.ServiceBookDetail')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('schedule_time_from', models.TimeField(blank=True, null=True)),
                ('schedule_time_to', models.TimeField(blank=True, null=True)),
                ('book_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Transfer')),
                ('dropoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_dropoff', to='config.Allotment')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_location_from', to='config.Location', verbose_name='Location from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_location_to', to='config.Location', verbose_name='Location to')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_pickup', to='config.Allotment')),
                ('place_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_place_from', to='config.Place')),
                ('place_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_place_to', to='config.Place')),
                ('schedule_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_schedule_from', to='config.Schedule')),
                ('schedule_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetailtransfer_schedule_to', to='config.Schedule')),
            ],
            options={
                'verbose_name': 'Service Book Detail Transfer',
                'verbose_name_plural': 'Services Book Details Transfers',
            },
            bases=('config.servicebookdetail', models.Model),
        ),
        migrations.AddField(
            model_name='servicebookdetail',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetail_base_location', to='config.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='servicebookdetail',
            name='base_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetail_base_service', to='config.Service'),
        ),
        migrations.AddField(
            model_name='servicebookdetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetail_service', to='config.Service'),
        ),
        migrations.AddField(
            model_name='servicebookdetail',
            name='service_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetail_service_addon', to='config.Addon', verbose_name='Addon'),
        ),
    ]
