# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-20 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_office_bank_details'),
        ('booking', '0031_auto_20200521_2140'),
        ('config', '0016_auto_20200328_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAgencyPackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SGL')),
                ('ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DBL')),
                ('ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='TPL')),
                ('ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='QAD')),
                ('ch_1_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_1_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='1st CHD')),
                ('ch_2_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_2_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='2nd CHD')),
                ('ch_3_ad_0_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('ch_3_ad_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='3rd CHD')),
                ('pax_range_min', models.SmallIntegerField(blank=True, null=True)),
                ('pax_range_max', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agency Package Detail',
                'verbose_name_plural': 'Agencies Package Details',
            },
        ),
        migrations.CreateModel(
            name='NewAgencyPackageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Agency')),
            ],
            options={
                'verbose_name': 'Agency Package Service',
                'verbose_name_plural': 'Agency Packages Services',
            },
        ),
        migrations.CreateModel(
            name='NewPackage',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.Service')),
                ('amounts_type', models.CharField(choices=[('F', 'Fixed'), ('P', 'By Pax')], default='P', max_length=5)),
                ('has_pax_range', models.BooleanField(default=False)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['name'],
            },
            bases=('config.service',),
        ),
        migrations.RemoveField(
            model_name='allotmentroomavailability',
            name='room_type',
        ),
        migrations.AlterUniqueTogether(
            name='extracomponent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='extracomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='extracomponent',
            name='extra',
        ),
        migrations.AlterUniqueTogether(
            name='servicesupplement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicesupplement',
            name='service',
        ),
        migrations.DeleteModel(
            name='AllotmentRoomAvailability',
        ),
        migrations.DeleteModel(
            name='AllotmentSupplement',
        ),
        migrations.DeleteModel(
            name='ExtraComponent',
        ),
        migrations.DeleteModel(
            name='ExtraSupplement',
        ),
        migrations.DeleteModel(
            name='TransferSupplement',
        ),
        migrations.DeleteModel(
            name='ServiceSupplement',
        ),
    ]
