# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-06 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20200328_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencytransferdetail',
            name='not_reversible',
            field=models.BooleanField(default=False),
        ),
    ]
