# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20190805_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['name'], 'verbose_name': 'Addon', 'verbose_name_plural': 'Addons'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['name'], 'verbose_name': 'Room Type', 'verbose_name_plural': 'Rooms Types'},
        ),
        migrations.AddField(
            model_name='allotment',
            name='cost_type',
            field=models.CharField(choices=[('F', 'Fixed'), ('P', 'By Pax')], default='P', max_length=5),
        ),
    ]
