# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_auto_20190924_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='agencyallotmentdetail',
            name='addon',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterField(
            model_name='agencyextradetail',
            name='addon',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterField(
            model_name='agencytransferdetail',
            name='addon',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterField(
            model_name='providerallotmentdetail',
            name='addon',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterField(
            model_name='providerextradetail',
            name='addon',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
        migrations.AlterField(
            model_name='providertransferdetail',
            name='addon',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='config.Addon'),
        ),
    ]
