# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 02:16
from __future__ import unicode_literals

from django.db import migrations


def migrate_package(apps, schema_editor):

    Package = apps.get_model('booking', 'Package')
    PackageAllotment = apps.get_model('booking', 'PackageAllotment')
    PackageTransfer = apps.get_model('booking', 'PackageTransfer')
    PackageExtra = apps.get_model('booking', 'PackageExtra')
    Extra = apps.get_model('config', 'Extra')
    ServiceBookDetailAllotment = apps.get_model('config', 'ServiceBookDetailAllotment')
    ServiceBookDetailTransfer = apps.get_model('config', 'ServiceBookDetailTransfer')
    ServiceBookDetailExtra = apps.get_model('config', 'ServiceBookDetailExtra')
    AgencyPackageService = apps.get_model('booking', 'AgencyPackageService')
    AgencyPackageDetail = apps.get_model('booking', 'AgencyPackageDetail')
    AgencyExtraService = apps.get_model('config', 'AgencyExtraService')
    AgencyExtraDetail = apps.get_model('config', 'AgencyExtraDetail')

    for package in Package.objects.all():
        new_extra = Extra()
        build_new_extra(new_extra, package)
        new_extra.save()
        for package_service in PackageAllotment.objects.filter(package=package):
            new_detail = ServiceBookDetailAllotment()
            build_new_book_detail_allotment(new_detail, package_service)
            new_detail.service_id = new_extra.id
            new_detail.save()
        for package_service in PackageTransfer.objects.filter(package=package):
            new_detail = ServiceBookDetailTransfer()
            build_new_book_detail_transfer(new_detail, package_service)
            new_detail.service_id = new_extra.id
            new_detail.save()
        for package_service in PackageExtra.objects.filter(package=package):
            new_detail = ServiceBookDetailExtra()
            build_new_book_detail_extra(new_detail, package_service)
            new_detail.service_id = new_extra.id
            new_detail.save()

        for agency_service in AgencyPackageService.objects.filter(service=package):
            new_agency_service = AgencyExtraService()
            build_new_agency_extra_service(new_agency_service, agency_service)
            new_agency_service.service_id = new_extra.id
            new_agency_service.save()

            for agency_detail in AgencyPackageDetail.objects.filter(agency_service=agency_service):
                new_agency_detail = AgencyExtraDetail()
                build_new_agency_extra_detail(new_agency_detail, agency_detail)
                new_agency_detail.agency_service_id = new_agency_service.id
                new_agency_detail.save()


def build_new_extra(new_extra, package):

    new_extra.pk = package.pk
    new_extra.name = package.name + ' (PACKAGE)'
    new_extra.description = package.description
    new_extra.service_category_id = package.service_category_id
    new_extra.category = 'E' # extra
    new_extra.grouping = package.grouping
    new_extra.pax_range = package.pax_range
    new_extra.child_age = package.child_age
    new_extra.child_discount_percent = package.child_discount_percent
    new_extra.infant_age = package.infant_age
    new_extra.location_id = package.location_id
    new_extra.new_time = package.time
    new_extra.enabled = package.enabled

    new_extra.cost_type = package.amounts_type
    new_extra.has_pax_range = package.has_pax_range
    new_extra.max_capacity = None
    new_extra.car_rental = None
    new_extra.parameter_type = 'S' # stay

    return new_extra


def copy_package_service(new_detail, service):

    new_detail.name = service.name
    new_detail.description = service.description
    new_detail.days_after = service.days_after
    new_detail.days_duration = service.days_duration
    new_detail.service_addon_id = service.service_addon_id
    new_detail.time = service.time
    new_detail.base_location_id = service.base_location_id
    new_detail.base_service_id = service.base_service_id


def build_new_book_detail_allotment(new_detail, package_service):

    copy_package_service(new_detail, package_service)

    new_detail.book_service_id = package_service.service_id
    new_detail.room_type_id = package_service.room_type_id
    new_detail.board_type = package_service.board_type
    return new_detail


def build_new_book_detail_transfer(new_detail, package_service):

    copy_package_service(new_detail, package_service)

    new_detail.book_service_id = package_service.service_id
    new_detail.pickup_id = package_service.pickup_id
    new_detail.dropoff_id = package_service.dropoff_id
    new_detail.location_from_id = package_service.location_from_id
    new_detail.location_to_id = package_service.location_to_id
    new_detail.place_from_id = package_service.place_from_id
    new_detail.place_to_id = package_service.place_to_id
    new_detail.schedule_from_id = package_service.schedule_from_id
    new_detail.schedule_to_id = package_service.schedule_to_id
    new_detail.schedule_time_from = package_service.schedule_time_from
    new_detail.schedule_time_to = package_service.schedule_time_to
    new_detail.quantity = package_service.quantity
    return new_detail


def build_new_book_detail_extra(new_detail, package_service):

    copy_package_service(new_detail, package_service)

    new_detail.book_service_id = package_service.service_id
    new_detail.pickup_office_id = package_service.pickup_office_id
    new_detail.dropoff_office_id = package_service.dropoff_office_id
    new_detail.parameter = package_service.parameter
    new_detail.quantity = package_service.quantity
    return new_detail


def build_new_agency_extra_service(new_agency_service, agency_service):

    new_agency_service.pk = None
    new_agency_service.id = None
    new_agency_service.agency_id = agency_service.agency_id
    new_agency_service.date_from = agency_service.date_from
    new_agency_service.date_to = agency_service.date_to
    return new_agency_service


def build_new_agency_extra_detail(new_agency_detail, agency_detail):

    new_agency_detail.pk = None
    new_agency_detail.id = None
    new_agency_detail.addon_id = 80
    new_agency_detail.pax_range_min = agency_detail.pax_range_min
    if new_agency_detail.pax_range_min is None:
        new_agency_detail.pax_range_min = 0
    new_agency_detail.pax_range_max = agency_detail.pax_range_max
    if new_agency_detail.pax_range_max is None:
        new_agency_detail.pax_range_max = 0
    new_agency_detail.ad_1_amount = agency_detail.ad_1_amount
    new_agency_detail.ad_2_amount = agency_detail.ad_2_amount
    new_agency_detail.ad_3_amount = agency_detail.ad_3_amount
    new_agency_detail.ad_4_amount = agency_detail.ad_4_amount
    new_agency_detail.ch_1_ad_0_amount = agency_detail.ch_1_ad_0_amount
    new_agency_detail.ch_1_ad_1_amount = agency_detail.ch_1_ad_1_amount
    new_agency_detail.ch_1_ad_2_amount = agency_detail.ch_1_ad_2_amount
    new_agency_detail.ch_1_ad_3_amount = agency_detail.ch_1_ad_3_amount
    new_agency_detail.ch_1_ad_4_amount = agency_detail.ch_1_ad_4_amount
    new_agency_detail.ch_2_ad_0_amount = agency_detail.ch_2_ad_0_amount
    new_agency_detail.ch_2_ad_1_amount = agency_detail.ch_2_ad_1_amount
    new_agency_detail.ch_2_ad_2_amount = agency_detail.ch_2_ad_2_amount
    new_agency_detail.ch_2_ad_3_amount = agency_detail.ch_2_ad_3_amount
    new_agency_detail.ch_2_ad_4_amount = agency_detail.ch_2_ad_4_amount
    new_agency_detail.ch_3_ad_0_amount = agency_detail.ch_3_ad_0_amount
    new_agency_detail.ch_3_ad_1_amount = agency_detail.ch_3_ad_1_amount
    new_agency_detail.ch_3_ad_2_amount = agency_detail.ch_3_ad_2_amount
    new_agency_detail.ch_3_ad_3_amount = agency_detail.ch_3_ad_3_amount
    new_agency_detail.ch_3_ad_4_amount = agency_detail.ch_3_ad_4_amount
    return new_agency_detail


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20200530_0818'),
        ('config', '0017_auto_20200530_0818'),
    ]

    operations = [

        migrations.RunPython(migrate_package, backwards_function),

    ]
