# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20200530_0818'),
        ('finance', '0013_auto_20200530_0818'),
        ('config', '0017_agencytransferdetail_not_reversible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotmentroomavailability',
            name='room_type',
        ),
        migrations.AlterUniqueTogether(
            name='extracomponent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='extracomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='extracomponent',
            name='extra',
        ),
        migrations.AlterUniqueTogether(
            name='servicesupplement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicesupplement',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='new_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebookdetail',
            name='new_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicebookdetail_provider', to='finance.Provider'),
        ),
        migrations.DeleteModel(
            name='AllotmentRoomAvailability',
        ),
        migrations.DeleteModel(
            name='AllotmentSupplement',
        ),
        migrations.DeleteModel(
            name='ExtraComponent',
        ),
        migrations.DeleteModel(
            name='ExtraSupplement',
        ),
        migrations.DeleteModel(
            name='TransferSupplement',
        ),
        migrations.DeleteModel(
            name='ServiceSupplement',
        ),
    ]
