# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_auto_20190215_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('is_arrival', models.BooleanField()),
                ('time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Location')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='TransferInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Location')),
                ('t_location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_location_from', to='config.Location', verbose_name='Location From')),
            ],
            options={
                'verbose_name': 'Transfer Interval',
                'verbose_name_plural': 'Transfers Intervals',
            },
        ),
        migrations.AlterUniqueTogether(
            name='transferinterval',
            unique_together=set([('location', 't_location_from')]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('location', 'number', 'is_arrival')]),
        ),
    ]
