# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-20 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_auto_20200521_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='newagencypackagedetail',
            name='agency_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.NewAgencyPackageService'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newagencypackageservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.NewPackage'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='newagencypackagedetail',
            unique_together=set([('agency_service', 'pax_range_min', 'pax_range_max')]),
        ),
        migrations.AlterUniqueTogether(
            name='newagencypackageservice',
            unique_together=set([('agency', 'service', 'date_from', 'date_to')]),
        ),
    ]
