# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-29 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_package(apps, schema_editor):

    Package = apps.get_model('booking', 'Package')
    PackageAllotment = apps.get_model('booking', 'PackageAllotment')
    PackageTransfer = apps.get_model('booking', 'PackageTransfer')
    PackageExtra = apps.get_model('booking', 'PackageExtra')
    AgencyPackageService = apps.get_model('booking', 'AgencyPackageService')
    AgencyPackageDetail = apps.get_model('booking', 'AgencyPackageDetail')

    for package in Package.objects.all():
        new_package = build_new_package(apps, package)
        new_package.save()
        for package_service in PackageAllotment.objects.filter(package=package):
            new_package_service = build_new_package_allotment(apps, package_service)
            new_package_service.save()
        for package_service in PackageTransfer.objects.filter(package=package):
            new_package_service = build_new_package_transfer(apps, package_service)
            new_package_service.save()
        for package_service in PackageExtra.objects.filter(package=package):
            new_package_service = build_new_package_extra(apps, package_service)
            new_package_service.save()

        for agency_service in AgencyPackageService.objects.filter(service=package):
            new_agency_service = build_new_agency_package_service(apps, agency_service)
            new_agency_service.save()

            for agency_detail in AgencyPackageDetail.objects.filter(agency_service=agency_service):
                new_agency_detail = build_new_agency_package_detail(apps, agency_detail)
                new_agency_detail.save()

def build_new_package(apps, package):

    NewPackage = apps.get_model('config', 'NewPackage')

    new_package = NewPackage()

    new_package.pk = package.pk
    new_package.name = package.name
    new_package.description = package.description
    new_package.location_id = package.location_id
    new_package.category = package.category
    new_package.service_category_id = package.service_category_id
    new_package.grouping = package.grouping
    new_package.child_age = package.child_age
    new_package.infant_age = package.infant_age
    new_package.child_discount_percent = package.child_discount_percent
    new_package.enabled = package.enabled
    new_package.pax_range = package.pax_range
    new_package.amounts_type = package.amounts_type
    new_package.has_pax_range = package.has_pax_range
    new_package.time = package.time
    return new_package


def copy_package_service(new_service, service):

    new_service.pk = service.pk
    new_service.service_id = service.package_id
    new_service.name = service.name
    new_service.description = service.description
    new_service.days_after = service.days_after
    new_service.days_duration = service.days_duration
    new_service.service_addon_id = service.service_addon_id
    new_service.time = service.time
    new_service.base_location_id = service.base_location_id
    new_service.base_service_id = service.base_service_id


def build_new_package_allotment(apps, package_service):

    ServiceBookDetailAllotment = apps.get_model('config', 'ServiceBookDetailAllotment')

    new_service = ServiceBookDetailAllotment()
    copy_package_service(new_service, package_service)

    new_service.book_service_id = package_service.service_id
    new_service.room_type_id = package_service.room_type_id
    new_service.board_type = package_service.board_type
    return new_service


def build_new_package_transfer(apps, package_service):

    ServiceBookDetailTransfer = apps.get_model('config', 'ServiceBookDetailTransfer')

    new_service = ServiceBookDetailTransfer()
    copy_package_service(new_service, package_service)

    new_service.book_service_id = package_service.service_id
    new_service.pickup_id = package_service.pickup_id
    new_service.dropoff_id = package_service.dropoff_id
    new_service.location_from_id = package_service.location_from_id
    new_service.location_to_id = package_service.location_to_id
    new_service.place_from_id = package_service.place_from_id
    new_service.place_to_id = package_service.place_to_id
    new_service.schedule_from_id = package_service.schedule_from_id
    new_service.schedule_to_id = package_service.schedule_to_id
    new_service.schedule_time_from = package_service.schedule_time_from
    new_service.schedule_time_to = package_service.schedule_time_to
    new_service.quantity = package_service.quantity
    return new_service


def build_new_package_extra(apps, package_service):

    ServiceBookDetailTransfer = apps.get_model('config', 'ServiceBookDetailExtra')

    new_service = ServiceBookDetailTransfer()
    copy_package_service(new_service, package_service)

    new_service.book_service_id = package_service.service_id
    new_service.pickup_office_id = package_service.pickup_office_id
    new_service.dropoff_office_id = package_service.dropoff_office_id
    new_service.parameter = package_service.parameter
    new_service.quantity = package_service.quantity
    return new_service


def build_new_agency_package_service(apps, agency_service):

    NewAgencyPackageService = apps.get_model('config', 'NewAgencyPackageService')

    new_agency_service = NewAgencyPackageService()
    new_agency_service.id = agency_service.id
    new_agency_service.agency_id = agency_service.agency_id
    new_agency_service.service_id = agency_service.service_id
    new_agency_service.date_from = agency_service.date_from
    new_agency_service.date_to = agency_service.date_to
    return new_agency_service


def build_new_agency_package_detail(apps, agency_detail):
    
    NewAgencyPackageDetail = apps.get_model('config', 'NewAgencyPackageDetail')

    new_agency_detail = NewAgencyPackageDetail()
    new_agency_detail.id = agency_detail.id
    new_agency_detail.agency_service_id = agency_detail.agency_service_id
    new_agency_detail.pax_range_min = agency_detail.pax_range_min
    new_agency_detail.pax_range_max = agency_detail.pax_range_max
    new_agency_detail.ad_1_amount = agency_detail.ad_1_amount
    new_agency_detail.ad_2_amount = agency_detail.ad_2_amount
    new_agency_detail.ad_3_amount = agency_detail.ad_3_amount
    new_agency_detail.ad_4_amount = agency_detail.ad_4_amount
    new_agency_detail.ch_1_ad_0_amount = agency_detail.ch_1_ad_0_amount
    new_agency_detail.ch_1_ad_1_amount = agency_detail.ch_1_ad_1_amount
    new_agency_detail.ch_1_ad_2_amount = agency_detail.ch_1_ad_2_amount
    new_agency_detail.ch_1_ad_3_amount = agency_detail.ch_1_ad_3_amount
    new_agency_detail.ch_1_ad_4_amount = agency_detail.ch_1_ad_4_amount
    new_agency_detail.ch_2_ad_0_amount = agency_detail.ch_2_ad_0_amount
    new_agency_detail.ch_2_ad_1_amount = agency_detail.ch_2_ad_1_amount
    new_agency_detail.ch_2_ad_2_amount = agency_detail.ch_2_ad_2_amount
    new_agency_detail.ch_2_ad_3_amount = agency_detail.ch_2_ad_3_amount
    new_agency_detail.ch_2_ad_4_amount = agency_detail.ch_2_ad_4_amount
    new_agency_detail.ch_3_ad_0_amount = agency_detail.ch_3_ad_0_amount
    new_agency_detail.ch_3_ad_1_amount = agency_detail.ch_3_ad_1_amount
    new_agency_detail.ch_3_ad_2_amount = agency_detail.ch_3_ad_2_amount
    new_agency_detail.ch_3_ad_3_amount = agency_detail.ch_3_ad_3_amount
    new_agency_detail.ch_3_ad_4_amount = agency_detail.ch_3_ad_4_amount
    return new_agency_detail


def backwards_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_auto_20200521_2140'),
        ('config', '0018_auto_20200521_2250'),
    ]

    operations = [

        migrations.RunPython(migrate_package, backwards_function),

    ]
