# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_auto_20190215_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='is_shared_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
