# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_custom_20200530_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('E', 'Extra'), ('A', 'Allotment'), ('T', 'Transfer')], max_length=5),
        ),
    ]
