# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_auto_20190313_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='infant_age',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
