# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20200530_0818'),
        ('config', '0020_auto_20200610_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebookdetail',
            name='new_provider',
        ),
        migrations.AddField(
            model_name='servicebookdetail',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
    ]
