# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_auto_20200612_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_as_package',
            field=models.BooleanField(default=False),
        ),
    ]
