# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_service_default_as_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
