# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-10 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_custom_20200905_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='included_services',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
