# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-21 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_service_included_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
