# Generated by Django 2.2.16 on 2020-11-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_auto_20200921_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Chain',
                'verbose_name_plural': 'Chains',
            },
        ),
        migrations.AlterModelOptions(
            name='agencyallotmentdetail',
            options={'verbose_name': 'Accomodation Price Detail', 'verbose_name_plural': 'Accomodation Price Details'},
        ),
        migrations.AlterModelOptions(
            name='agencyallotmentservice',
            options={'verbose_name': 'Accomodation Price', 'verbose_name_plural': 'Accomodation Prices'},
        ),
        migrations.AlterModelOptions(
            name='agencyextradetail',
            options={'verbose_name': 'Extra Price Detail', 'verbose_name_plural': 'Extra Price Details'},
        ),
        migrations.AlterModelOptions(
            name='agencyextraservice',
            options={'verbose_name': 'Extra Price', 'verbose_name_plural': 'Extras Prices'},
        ),
        migrations.AlterModelOptions(
            name='agencytransferdetail',
            options={'verbose_name': 'Transfer Price Detail', 'verbose_name_plural': 'Transfer Price Details'},
        ),
        migrations.AlterModelOptions(
            name='agencytransferservice',
            options={'verbose_name': 'Transfer Price', 'verbose_name_plural': 'Transfer Prices'},
        ),
        migrations.AlterModelOptions(
            name='allotment',
            options={'verbose_name': 'Accomodation', 'verbose_name_plural': 'Accomodations'},
        ),
        migrations.AlterModelOptions(
            name='providerallotmentdetail',
            options={'verbose_name': 'Accomodation Cost Detail', 'verbose_name_plural': 'Accomodation Cost Details'},
        ),
        migrations.AlterModelOptions(
            name='providerallotmentservice',
            options={'verbose_name': 'Accomodation Cost', 'verbose_name_plural': 'Accomodation Costs'},
        ),
        migrations.AlterModelOptions(
            name='providerextradetail',
            options={'verbose_name': 'Extra Cost Detail', 'verbose_name_plural': 'Extra Cost Details'},
        ),
        migrations.AlterModelOptions(
            name='providerextraservice',
            options={'verbose_name': 'Extra Cost', 'verbose_name_plural': 'Extra Costs'},
        ),
        migrations.AlterModelOptions(
            name='providertransferdetail',
            options={'verbose_name': 'Transfer Cost Detail', 'verbose_name_plural': 'Transfer Cost Details'},
        ),
        migrations.AlterModelOptions(
            name='providertransferservice',
            options={'verbose_name': 'Transfer Cost', 'verbose_name_plural': 'Transfer Cost'},
        ),
        migrations.AlterField(
            model_name='service',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='No Voucher'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Chain'),
        ),
    ]
