# Generated by Django 2.2.16 on 2020-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_auto_20201123_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyallotmentservice',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyallotmentservice',
            name='booked_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyallotmentservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='agencyextraservice',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyextraservice',
            name='booked_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyextraservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='agencytransferservice',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencytransferservice',
            name='booked_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencytransferservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='providerallotmentservice',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerallotmentservice',
            name='booked_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerallotmentservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='providerextraservice',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerextraservice',
            name='booked_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerextraservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='providertransferservice',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providertransferservice',
            name='booked_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providertransferservice',
            name='contract_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
