# Generated by Django 2.2.16 on 2020-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20200706_1734'),
        ('config', '0028_auto_20201207_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyallotmentservice',
            name='contract_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='agencyextraservice',
            name='contract_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='agencytransferservice',
            name='contract_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='providerallotmentservice',
            name='contract_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='providerextraservice',
            name='contract_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='providertransferservice',
            name='contract_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='agencyallotmentservice',
            unique_together={('agency', 'service', 'date_from', 'date_to', 'contract_code')},
        ),
        migrations.AlterUniqueTogether(
            name='agencyextraservice',
            unique_together={('agency', 'service', 'date_from', 'date_to', 'contract_code')},
        ),
        migrations.AlterUniqueTogether(
            name='agencytransferservice',
            unique_together={('agency', 'service', 'date_from', 'date_to', 'contract_code')},
        ),
        migrations.AlterUniqueTogether(
            name='providerallotmentservice',
            unique_together={('provider', 'service', 'date_from', 'date_to', 'contract_code')},
        ),
        migrations.AlterUniqueTogether(
            name='providerextraservice',
            unique_together={('provider', 'service', 'date_from', 'date_to', 'contract_code')},
        ),
        migrations.AlterUniqueTogether(
            name='providertransferservice',
            unique_together={('provider', 'service', 'date_from', 'date_to', 'contract_code')},
        ),
    ]
