# Generated by Django 2.2.24 on 2023-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_auto_20201215_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='voucher_notes',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
