"""
Config Constants
"""

SERVICE_CATEGORY_EXTRA = 'E'
SERVICE_CATEGORY_ALLOTMENT = 'A'
SERVICE_CATEGORY_TRANSFER = 'T'
SERVICE_CATEGORIES = (
    (SERVICE_CATEGORY_EXTRA, 'Extra'),
    (SERVICE_CATEGORY_ALLOTMENT, 'Allotment'),
    (SERVICE_CATEGORY_TRANSFER, 'Transfer'),
)

EXTRA_COST_TYPE_BY_PAX = 'P'
EXTRA_COST_TYPE_BY_EXTRA = 'E'
EXTRA_COST_TYPE_BY_PAX_EXTRA = 'PE'
EXTRA_COST_TYPES = (
    (EXTRA_COST_TYPE_BY_PAX, 'By Pax'),
    (EXTRA_COST_TYPE_BY_EXTRA, 'By Extra'),
    (EXTRA_COST_TYPE_BY_PAX_EXTRA, 'By Pax Extra'),
)

ALLOTMENT_COST_TYPE_FIXED = 'F'
ALLOTMENT_COST_TYPE_BY_PAX = 'P'
ALLOTMENT_COST_TYPES = (
    (ALLOTMENT_COST_TYPE_FIXED, 'Fixed'),
    (ALLOTMENT_COST_TYPE_BY_PAX, 'By Pax'),
)

ALLOTMENT_SUPPLEMENT_COST_TYPE_FIXED = 'F'
ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX = 'P'
ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_DAY = 'D'
ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX_DAY = 'PD'
ALLOTMENT_SUPPLEMENT_COST_TYPES = (
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_FIXED, 'Fixed'),
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX, 'By Pax'),
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_DAY, 'By Day'),
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX_DAY, 'By Pax Day'),
)

TRANSFER_COST_TYPE_FIXED = 'F'
TRANSFER_COST_TYPE_BY_PAX = 'P'
TRANSFER_COST_TYPES = (
    (TRANSFER_COST_TYPE_FIXED, 'Fixed'),
    (TRANSFER_COST_TYPE_BY_PAX, 'By Pax'),
)

TRANSFER_SUPPLEMENT_COST_TYPE_FIXED = 'F'
TRANSFER_SUPPLEMENT_COST_TYPE_BYHOURS = 'H'
TRANSFER_SUPPLEMENT_COST_TYPES = (
    (TRANSFER_SUPPLEMENT_COST_TYPE_FIXED, 'Fixed'),
    (TRANSFER_SUPPLEMENT_COST_TYPE_BYHOURS, 'By Hours'),
)

ROOM_TYPE_SINGLE = 'S'
ROOM_TYPE_DOUBLE = 'D'
ROOM_TYPE_TRIPLE = 'T'
ROOM_TYPES = (
    (ROOM_TYPE_SINGLE, 'Single'),
    (ROOM_TYPE_DOUBLE, 'Double'),
    (ROOM_TYPE_TRIPLE, 'Triple'),
)

BOARD_TYPE_NB = 'NB'
BOARD_TYPE_BB = 'BB'
BOARD_TYPE_HB = 'HB'
BOARD_TYPE_FB = 'FB'
BOARD_TYPE_AI = 'AI'
BOARD_TYPES = (
    (BOARD_TYPE_NB, 'None Board'),
    (BOARD_TYPE_BB, 'Breakfast Board'),
    (BOARD_TYPE_HB, 'Half Board'),
    (BOARD_TYPE_FB, 'Full Board'),
    (BOARD_TYPE_AI, 'All Included'),
)

PAX_TYPE_BABY = 'B'
PAX_TYPE_CHILD = 'C'
PAX_TYPE_ADULT = 'A'
PAX_TYPE_SENIOR = 'S'
PAX_TYPES = (
    (PAX_TYPE_BABY, 'Baby'),
    (PAX_TYPE_CHILD, 'Child'),
    (PAX_TYPE_ADULT, 'Adult'),
    (PAX_TYPE_SENIOR, 'Senior'),
)
