"""
Config Constants
"""

SERVICE_CATEGORY_EXTRA = 'E'
SERVICE_CATEGORY_ALLOTMENT = 'A'
SERVICE_CATEGORY_TRANSFER = 'T'
SERVICE_CATEGORIES = (
    (SERVICE_CATEGORY_EXTRA, 'Extra'),
    (SERVICE_CATEGORY_ALLOTMENT, 'Allotment'),
    (SERVICE_CATEGORY_TRANSFER, 'Transfer'),
)

EXTRA_COST_TYPE_BY_PAX = 'P'
EXTRA_COST_TYPE_BY_EXTRA = 'E'
EXTRA_COST_TYPE_BY_PAX_EXTRA = 'PE'
EXTRA_COST_TYPES = (
    (EXTRA_COST_TYPE_BY_PAX, 'By Pax'),
    (EXTRA_COST_TYPE_BY_EXTRA, 'By Extra'),
    (EXTRA_COST_TYPE_BY_PAX_EXTRA, 'By Pax Extra'),
)

ALLOTMENT_COST_TYPE_FIXED = 'F'
ALLOTMENT_COST_TYPE_BY_PAX = 'P'
ALLOTMENT_COST_TYPES = (
    (ALLOTMENT_COST_TYPE_FIXED, 'Fixed'),
    (ALLOTMENT_COST_TYPE_BY_PAX, 'By Pax'),
)

ALLOTMENT_SUPPLEMENT_COST_TYPE_FIXED = 'F'
ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX = 'P'
ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_DAY = 'D'
ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX_DAY = 'PD'
ALLOTMENT_SUPPLEMENT_COST_TYPES = (
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_FIXED, 'Fixed'),
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX, 'By Pax'),
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_DAY, 'By Day'),
    (ALLOTMENT_SUPPLEMENT_COST_TYPE_BY_PAX_DAY, 'By Pax Day'),
)

TRANSFER_COST_TYPE_FIXED = 'F'
TRANSFER_COST_TYPE_BY_PAX = 'P'
TRANSFER_COST_TYPES = (
    (TRANSFER_COST_TYPE_FIXED, 'Fixed'),
    (TRANSFER_COST_TYPE_BY_PAX, 'By Pax'),
)

TRANSFER_SUPPLEMENT_COST_TYPE_FIXED = 'F'
TRANSFER_SUPPLEMENT_COST_TYPE_BYHOURS = 'H'
TRANSFER_SUPPLEMENT_COST_TYPES = (
    (TRANSFER_SUPPLEMENT_COST_TYPE_FIXED, 'Fixed'),
    (TRANSFER_SUPPLEMENT_COST_TYPE_BYHOURS, 'By Hours'),
)

ROOM_CAPACITY_SINGLE = '1'
ROOM_CAPACITY_DOUBLE = '2'
ROOM_CAPACITY_TRIPLE = '3'
ROOM_CAPACITY_QDRPLE = '4'
ROOM_CAPACITY_MLTPLE = '5'
ROOM_CAPACITIES = (
    (ROOM_CAPACITY_SINGLE, 'SGL'),
    (ROOM_CAPACITY_DOUBLE, 'DBL'),
    (ROOM_CAPACITY_TRIPLE, 'TPL'),
    (ROOM_CAPACITY_QDRPLE, 'QPL'),
    (ROOM_CAPACITY_MLTPLE, 'MPL'),
)

BOARD_TYPE_NB = 'NB'
BOARD_TYPE_BB = 'BB'
BOARD_TYPE_HB = 'HB'
BOARD_TYPE_FB = 'FB'
BOARD_TYPE_AI = 'AI'
BOARD_TYPES = (
    (BOARD_TYPE_NB, 'None Board'),
    (BOARD_TYPE_BB, 'Breakfast Board'),
    (BOARD_TYPE_HB, 'Half Board'),
    (BOARD_TYPE_FB, 'Full Board'),
    (BOARD_TYPE_AI, 'All Included'),
)

PAX_TYPE_CHILD = 'C'
PAX_TYPE_ADULT = 'A'
PAX_TYPES = (
    (PAX_TYPE_CHILD, 'Child'),
    (PAX_TYPE_ADULT, 'Adult'),
)

ERROR_INVALID_SERVICE_CATEGORY = 'Invalid Service Category %s'
ERROR_NO_EXTRA_COST_FOUND = 'Cost Not Found for Service %s - Provider %s - Date %s'
