# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-03 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(choices=[(b'CUC', b'CUC'), (b'USD', b'USD'), (b'EUR', b'EUR')], default=b'CUC', max_length=5)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('concept', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
                ('user', models.ForeignKey(help_text=b'User who did the operation.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='OperationMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[(b'D', b'Deposit'), (b'W', b'Withdraw')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Operation Movement',
                'verbose_name_plural': 'Operations Movements',
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'currency')]),
        ),
    ]
