# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR')], default='CUC', max_length=5)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('concept', models.CharField(choices=[('-------', '-------'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('CURRENCY_EXCHANGE', 'Currency Exchange'), ('TRANSFER', 'Transfer'), ('LOAN_ENTITY_DEPOSIT', 'Loan Entity Deposit'), ('LOAN_ENTITY_WITHDRAW', 'Loan Entity Withdraw'), ('LOAN_ACCOUNT_DEPOSIT', 'Loan Account Deposit'), ('LOAN_ACCOUNT_WITHDRAW', 'Loan Account Withdraw'), ('AGENCY_INVOICE', 'Agency Invoice'), ('AGENCY_PAYMENT', 'Agency Payment'), ('AGENCY_DEVOLUTION', 'Agency Devolution'), ('AGENCY_DISCOUNT', 'Agency Discount'), ('PROVIDER_INVOICE', 'Provider Invoice'), ('PROVIDER_PAYMENT', 'Provider Payment'), ('PROVIDER_DEVOLUTION', 'Provider Devolution'), ('PROVIDER_DISCOUNT', 'Provider Discount'), ('DEPOSIT_REVERTION', 'Revertion of Deposit'), ('WITHDRAW_REVERTION', 'Revertion of Withdraw'), ('CURRENCY_EXCHANGE_REVERTION', 'Revertion of Currency Exchange'), ('TRANSFER_REVERTION', 'Revertion of Transfer'), ('LOAN_ENTITY_DEPOSIT_REVERTION', 'Revertion of Loan Entity Deposit'), ('LOAN_ENTITY_WITHDRAW_REVERTION', 'Revertion of Loan Entity Withdraw'), ('LOAN_ACCOUNT_DEPOSIT_REVERTION', 'Revertion of Loan Account Deposit'), ('LOAN_ACCOUNT_WITHDRAW_REVERTION', 'Revertion of Loan Account Withdraw'), ('AGENCY_INVOICE_REVERTION', 'Revertion of Agency Invoice'), ('AGENCY_PAYMENT_REVERTION', 'Revertion of Agency Payment'), ('AGENCY_DEVOLUTION_REVERTION', 'Revertion of Agency Devolution'), ('AGENCY_DISCOUNT_REVERTION', 'Revertion of Agency Discount'), ('PROVIDER_INVOICE_REVERTION', 'Revertion of Provider Invoice'), ('PROVIDER_PAYMENT_REVERTION', 'Revertion of Provider Payment'), ('PROVIDER_DEVOLUTION_REVERTION', 'Revertion of Provider Devolution'), ('PROVIDER_DISCOUNT_REVERTION', 'Revertion of Provider Discount')], max_length=50)),
                ('detail', models.CharField(max_length=200)),
                ('user', models.ForeignKey(help_text='User who did the operation.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='OperationMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('I', 'Input'), ('O', 'Output')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Operation')),
            ],
            options={
                'verbose_name': 'Operation Movement',
                'verbose_name_plural': 'Operations Movements',
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'currency')]),
        ),
    ]
