# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-01 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'default_permissions': ('view',), 'verbose_name': 'Operation', 'verbose_name_plural': 'Operations'},
        ),
        migrations.AlterModelOptions(
            name='operationmovement',
            options={'default_permissions': ('view',), 'verbose_name': 'Operation Movement', 'verbose_name_plural': 'Operations Movements'},
        ),
    ]
