# Generated by Django 2.2.24 on 2022-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20191101_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmovement',
            name='final_account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
