# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20190327_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CUP', 'CUP')], default='CUC', max_length=5),
        ),
    ]
