# Generated by Django 2.2.24 on 2023-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_custom_20221021_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmovement',
            name='final_account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balance After'),
        ),
    ]
